import type { Locale } from "@/lib/i18n/config";
import type { HubKey } from "@/lib/i18n/hub";

export const HUB_KEYWORDS: Record<Locale, Record<HubKey, string[]>> = {
  en: {
    naamJaap: [
      "online naam jaap",
      "digital jaap counter",
      "108 mala online",
      "ram naam jaap",
      "hare krishna mahamantra counter",
      "om namah shivaya japa counter",
      "radhe radhe jaap online",
      "free online japa mala",
      "mantra chanting counter",
      "digital bead counter 108",
      "daily sadhana jaap tracker",
      "free japa counter app",
    ],
    mala: [
      "mala jaap online",
      "108 beads counter",
      "japa mala counter",
      "tulsi mala online counter",
      "rudraksha mala jaap counter",
      "digital mala 108 count",
      "mantra bead tracker",
      "digital japa mala free",
    ],
    katha: [
      "katha stories",
      "hindu mythological stories",
      "ramayana katha in english",
      "mahabharata stories",
      "bhagavata purana katha",
      "shiv purana stories",
      "sacred hindu tales",
      "vedic stories online",
      "satyanarayan katha",
      "vrat katha online",
    ],
    yatra: [
      "sacred yatra guides",
      "char dham yatra guide",
      "12 jyotirlinga yatra route",
      "hindu pilgrimage destinations in india",
      "ayodhya ram mandir darshan guide",
      "kedarnath yatra route and tips",
      "kashi vishwanath yatra varanasi",
      "tirupati balaji darshan guide",
      "puri jagannath yatra",
      "vaishno devi yatra guide",
    ],
    planner: [
      "yatra planner",
      "pilgrimage trip planner",
      "temple itinerary planner india",
      "char dham route planner",
      "hindu temple tour plan",
      "darshan travel planner",
    ],
    sadhana: [
      "daily sadhana",
      "hindu daily spiritual practice",
      "morning puja routine for householders",
      "naam jaap routine",
      "home shrine daily sadhana",
      "daily prayer and meditation",
    ],
    sankalp: [
      "global ram naam sankalp",
      "devotee prayer pledge",
      "collective japa sankalp",
      "hindu sankalp online",
      "ram naam chanting movement",
    ],
    diary: [
      "bhakti diary",
      "spiritual journal online",
      "daily sadhana tracker",
      "japa log for devotees",
      "daily devotional log book",
    ],
    blog: [
      "bhakti blog",
      "hindu spirituality articles",
      "sacred yatra travelogues",
      "mantra meanings and benefits",
      "sanatan dharma blog",
      "vedic wisdom essays",
      "devotional articles in english",
    ],
    temples: [
      "hindu temples in india",
      "ancient hindu temples list",
      "12 jyotirlinga temples",
      "51 shakti peeth list with location",
      "famous temples in india",
      "temple darshan timings",
      "historical mandir guide",
    ],
    festivals: [
      "hindu festivals 2026",
      "upcoming hindu festivals 2026",
      "diwali 2026 date and time",
      "holi 2026 date",
      "maha shivratri 2026",
      "navratri 2026 dates calendar",
      "raksha bandhan 2026",
      "janmashtami 2026 date",
      "hindu tyohar calendar 2026",
    ],
    mantras: [
      "hindu mantras with meaning",
      "vedic mantras in english",
      "gayatri mantra lyrics and meaning",
      "maha mrityunjaya mantra chanting",
      "powerful peace mantras",
      "wealth and prosperity mantras",
      "morning mantras to chant",
      "sanskrit slokas with english translation",
    ],
    spirituality: [
      "spiritual knowledge",
      "sanatan dharma philosophy",
      "vedanta teachings for beginners",
      "karma yoga principles",
      "bhakti yoga guide",
      "householder spiritual sadhana",
      "hindu philosophical texts",
    ],
    community: [
      "devotee community",
      "hindu satsang online",
      "bhakti sangha groups",
      "spiritual discussion forum",
      "devotional groups for householders",
    ],
    store: [
      "bhakti store",
      "buy authentic tulsi mala online",
      "108 jaap mala beads",
      "brass puja diya online",
      "pooja items online india",
      "sacred spiritual tools store",
    ],
    tithi: [
      "aaj ki tithi",
      "today tithi in english",
      "today tithi kya hai",
      "today tithi timing",
      "aaj ki tithi hindu calendar 2026",
      "hindu lunar date today",
      "shukla paksha krishna paksha today",
      "tithi timings by city",
      "today ekadashi purnima amavasya",
    ],
    quotes: [
      "daily devotional quotes",
      "aaj ka suvichar english mein",
      "spiritual quotes in english",
      "bhagavad gita quotes chapter wise",
      "bhagavad gita inspirational quotes",
      "hindu suvichar status",
      "peaceful wisdom quotes for whatsapp",
      "positive spiritual thoughts",
    ],
    bhajan: [
      "bhajan and kirtan lyrics",
      "krishna bhajans with english lyrics",
      "shiva bhajans with meaning",
      "ram bhajan sangrah",
      "devotional songs lyrics",
      "morning bhajans lyrics",
      "popular traditional kirtan",
    ],
    aarti: [
      "aarti chants lyrics",
      "daily aarti sangrah in english",
      "om jai jagdish hare aarti lyrics",
      "hanuman aarti lyrics",
      "ganesh aarti lyrics and meaning",
      "shiv aarti with meaning",
      "durga aarti lyrics",
      "laxmi aarti lyrics english",
    ],
    chalisa: [
      "chalisa sangrah",
      "hanuman chalisa lyrics in english",
      "hanuman chalisa lyrics and meaning",
      "shiv chalisa with meaning",
      "durga chalisa lyrics",
      "shani chalisa english",
      "krishna chalisa",
      "40 verses devotional prayer",
    ],
    more: [
      "spiritual tools directory",
      "hindu calculators online",
      "bhakti voice explore",
      "sanatan dharma companions",
    ],
    library: [
      "spiritual library",
      "sacred knowledge repository",
      "vedic wisdom books",
      "spiritual scriptures guide",
      "divine signs and guidance",
    ],
    angelNumbers: [
      "angel numbers",
      "angel numbers meaning",
      "repeating numbers spiritual meaning",
      "angel number 555",
      "angel number 777",
      "angel number 500",
      "twin flame numbers",
      "numerology sequences",
      "seeing repeating numbers",
    ],
  },
  hi: {
    naamJaap: [
      "ऑनलाइन नाम जप",
      "डिजिटल जप काउंटर",
      "१०८ माला जप ऑनलाइन",
      "राम नाम जप",
      "हरे कृष्ण महामंत्र जप",
      "ॐ नमः शिवाय जप काउंटर",
      "राधे राधे जप ऑनलाइन",
      "मुफ्त डिजिटल माला",
      "नाम जप माला काउंटर",
      "दैनिक साधना जप ट्रैकर",
      "मंत्र जाप काउंटर",
      "माला सिमरन काउंटर",
    ],
    mala: [
      "माला जप ऑनलाइन",
      "१०८ मनके डिजिटल काउंटर",
      "तुलसी माला जप",
      "रुद्राक्ष माला जप",
      "डिजिटल सिमरन माला",
      "१०८ माला काउंटर",
      "जाप माला ऑनलाइन",
    ],
    katha: [
      "पौराणिक कथाएं",
      "धार्मिक कथाएं हिंदी में",
      "रामायण कथा",
      "महाभारत कथाएं",
      "भागवत कथा",
      "शिव पुराण कथा",
      "व्रत कथा संग्रह",
      "सत्यनारायण भगवान की कथा",
      "एकादशी व्रत कथा",
      "भक्ति कथाएं हिंदी में",
    ],
    yatra: [
      "तीर्थ यात्रा गाइड",
      "चार धाम यात्रा सम्पूर्ण जानकारी",
      "१२ ज्योतिर्लिंग यात्रा मार्ग",
      "अयोध्या राम मंदिर दर्शन गाइड",
      "केदारनाथ यात्रा रूट और नियम",
      "काशी विश्वनाथ दर्शन वाराणसी",
      "तिरुपति बालाजी दर्शन विधि",
      "जगन्नाथ पुरी यात्रा",
      "वैष्णो देवी यात्रा गाइड",
      "प्रमुख हिन्दू तीर्थ स्थल",
    ],
    planner: [
      "तीर्थ यात्रा प्लानर",
      "मंदिर यात्रा रूट प्लानर",
      "चार धाम यात्रा योजना",
      "दर्शन यात्रा समय सारणी",
      "धार्मिक यात्रा टूर प्लान",
    ],
    sadhana: [
      "दैनिक साधना",
      "नित्य पूजा विधि",
      "गृहस्थ आध्यात्मिक साधना",
      "नाम जप नियम",
      "दैनिक भक्ति अभ्यास",
      "प्रातः पूजा और ध्यान",
    ],
    sankalp: [
      "वैश्विक राम नाम संकल्प",
      "भक्त संकल्प ऑनलाइन",
      "सामूहिक राम नाम जप",
      "अखंड राम नाम साधना",
    ],
    diary: [
      "भक्ति डायरी",
      "दैनिक साधना लॉग",
      "नाम जप डायरी",
      "आध्यात्मिक डायरी ऑनलाइन",
    ],
    blog: [
      "भक्ति ब्लॉग",
      "सनातन धर्म लेख",
      "तीर्थ यात्रा वृत्तांत",
      "मंत्र रहस्य एवं अर्थ",
      "धार्मिक एवं आध्यात्मिक ज्ञान",
      "वैदिक संस्कृति ब्लॉग",
    ],
    temples: [
      "हिन्दू मंदिर सूची",
      "भारत के प्राचीन मंदिर",
      "१२ ज्योतिर्लिंग मंदिर",
      "५१ शक्तिपीठ सूची व स्थान",
      "भारत के प्रसिद्ध मंदिर",
      "मंदिर दर्शन समय व नियम",
      "ऐतिहासिक मन्दिर गाइड",
    ],
    festivals: [
      "हिन्दू त्यौहार 2026",
      "व्रत एवं त्यौहार कैलेंडर 2026",
      "दिवाली 2026 कब है",
      "होली 2026 तिथि",
      "महाशिवरात्रि 2026",
      "नवरात्रि 2026 तिथियां",
      "रक्षाबंधन 2026",
      "कृष्ण जन्माष्टमी 2026",
      "हिन्दू पंचांग त्यौहार सूची",
    ],
    mantras: [
      "वैदिक मंत्र संग्रह",
      "गायत्री मंत्र अर्थ सहित",
      "महामृत्युंजय मंत्र जप विधि",
      "शांति मंत्र संस्कृत",
      "दैनिक प्रातः मंत्र",
      "धन प्राप्ति महालक्ष्मी मंत्र",
      "शक्तिशाली संस्कृत मंत्र",
      "मंत्र जाप के लाभ",
    ],
    spirituality: [
      "आध्यात्मिक ज्ञान",
      "सनातन धर्म दर्शन",
      "वेदान्त ज्ञान सरल हिंदी में",
      "कर्म योग गीता",
      "भक्ति मार्ग नियम",
      "गृहस्थ जीवन में साधना",
      "उपनिषद ज्ञान",
    ],
    community: [
      "भक्त समुदाय",
      "सत्संग मंडल ऑनलाइन",
      "भक्ति संघ",
      "धार्मिक चर्चा मंच",
    ],
    store: [
      "भक्ति स्टोर",
      "असली तुलसी माला ऑनलाइन खरीदें",
      "१०८ मनके जप माला",
      "पीतल पूजा दीपक",
      "पूजा सामग्री ऑनलाइन",
      "आध्यात्मिक पूजा उपकरण",
    ],
    tithi: [
      "आज की तिथि",
      "आज की तिथि क्या है",
      "आज की तिथि हिन्दू कैलेंडर 2026",
      "आज कौन सी तिथि है",
      "शुक्ल पक्ष कृष्ण पक्ष समय",
      "दैनिक तिथि पंचांग",
      "आज एकादशी है या पूर्णिमा",
    ],
    quotes: [
      "दैनिक सुविचार",
      "आज का सुविचार प्रेमानंद जी महाराज",
      "आज का सुविचार दो लाइन",
      "सुप्रभात भक्ति सुविचार",
      "आध्यात्मिक सुविचार हिंदी में",
      "भगवद्गीता अनमोल वचन",
      "धार्मिक विचार व्हाट्सएप स्टेटस",
      "प्रेरणादायक भक्ति वचन",
      "आज का विचार",
    ],
    bhajan: [
      "भजन और कीर्तन लिरिक्स",
      "कृष्ण भजन लिरिक्स",
      "शिव भजन बोल सहित",
      "राम भजन संग्रह",
      "दैनिक प्रातः भजन",
      "पारंपरिक आरती एवं कीर्तन",
      "सुप्रसिद्ध भजन लिरिक्स",
    ],
    aarti: [
      "आरती संग्रह",
      "दैनिक आरती लिरिक्स",
      "ॐ जय जगदीश हरे आरती",
      "हनुमान जी की आरती",
      "शिव जी की आरती",
      "गणेश जी की आरती बोल सहित",
      "दुर्गा मां की आरती",
      "लक्ष्मी जी की आरती",
    ],
    chalisa: [
      "चालीसा संग्रह",
      "श्री हनुमान चालीसा लिरिक्स",
      "हनुमान चालीसा हिंदी अर्थ सहित",
      "श्री हनुमान चालीसा हिंदी",
      "शिव चालीसा अर्थ सहित",
      "दुर्गा चालीसा पाठ",
      "शनि चालीसा हिंदी",
      "कृष्ण चालीसा",
      "दैनिक चालीसा पाठ विधि",
    ],
    more: [
      "आध्यात्मिक टूल्स",
      "वैदिक कैलकुलेटर ऑनलाइन",
      "भक्ति वॉइस सुविधाएं",
    ],
    library: [
      "आध्यात्मिक लाइब्रेरी",
      "धार्मिक ज्ञान संग्रह",
      "सनातन ज्ञान भंडार",
      "दिव्य मार्गदर्शन ग्रंथ",
    ],
    angelNumbers: [
      "एंजेल नंबर्स",
      "एंजेल नंबर का अर्थ",
      "संख्याओं का आध्यात्मिक अर्थ",
      "एंजेल नंबर 555",
      "एंजेल नंबर 777",
      "संख्या 500 का अर्थ",
      "अंक ज्योतिष मार्गदर्शन",
    ],
  },
  te: {
    naamJaap: [
      "ఆన్‌లైన్ నామ జపం",
      "డిజిటల్ జప కౌంటర్",
      "108 మాల జపం ఆన్‌లైన్",
      "రామ నామ జపం",
      "హరే కృష్ణ మహామంత్రం",
      "ఓం నమః శివాయ జప కౌంటర్",
      "రాధే రాధే జపం",
      "ఉచిత డిజిటల్ జపమాల",
      "దైవిక నామ జప సాధన",
      "నిత్య జప సాధన కౌంటర్",
    ],
    mala: [
      "మాల జపం ఆన్‌లైన్",
      "108 పూసల డిజిటల్ కౌంటర్",
      "తులసి మాల జపం",
      "రుద్రాక్ష మాల జపం",
      "డిజిటల్ జపమాల తెలుగు",
    ],
    katha: [
      "పౌరాణిక గాథలు",
      "భక్తి కథలు తెలుగులో",
      "రామాయణ కథలు",
      "మహాభారత కథలు",
      "శ్రీమద్భాగవత కథలు",
      "శివ పురాణ కథలు",
      "వ్రత కథలు",
      "సత్యనారాయణ వ్రత కథ",
    ],
    yatra: [
      "పుణ్య క్షేత్రాల యాత్ర గైడ్",
      "చార్ ధామ్ యాత్ర తెలుగు",
      "12 జ్యోతిర్లింగ దర్శన యాత్ర",
      "తిరుపతి బాలాజీ దర్శనం గైడ్",
      "అయోధ్య రామ మందిరం యాత్ర",
      "కాశీ యాత్ర విశేషాలు",
      "కేదార్‌నాథ్ యాత్ర మార్గం",
      "హిందూ పుణ్యక్షేత్రాలు",
    ],
    planner: [
      "యాత్రా ప్లానర్",
      "తీర్థయాత్రల ప్రణాళిక",
      "దేవాలయ దర్శన ప్లానర్",
      "క్షేత్ర యాత్ర మార్గం",
    ],
    sadhana: [
      "నిత్య దిన సాధన",
      "గృహ పూజా విధానం",
      "నామ జప సాధన నియమాలు",
      "భక్తి ఆచరణలు తెలుగులో",
    ],
    sankalp: [
      "రామ నామ సంకల్పం",
      "భక్తుల మహా సంకల్పం",
      "సామూహిక నామ జపం",
    ],
    diary: [
      "భక్తి డైరీ",
      "దిన సాధన రికార్డు",
      "నామ జప డైరీ",
    ],
    blog: [
      "ఆధ్యాత్మిక బ్లాగులు",
      "భక్తి వ్యాసాలు",
      "పుణ్యక్షేత్ర యాత్రా విశేషాలు",
      "వేద ధర్మ విశేషాలు తెలుగులో",
      "మంత్ర మహిమలు",
    ],
    temples: [
      "హిందూ దేవాలయాలు",
      "పురాతన ఆలయాలు జాబితా",
      "12 జ్యోతిర్లింగ ఆలయాలు",
      "శక్తిపీఠాల జాబితా",
      "ప్రసిద్ధ దేవాలయాల దర్శన సమయాలు",
    ],
    festivals: [
      "హిందూ పండుగలు 2026",
      "పండుగల క్యాలెండర్ 2026",
      "సంక్రాంతి పండుగ 2026",
      "మహా శివరాత్రి 2026",
      "ఉగాది పండుగ తేదీ",
      "వినాయక చవితి 2026",
      "దీపావళి 2026 తేదీ",
    ],
    mantras: [
      "వేద మంత్రాలు",
      "గాయత్రీ మంత్రం అర్థం",
      "మహామృత్యుంజయ మంత్రం",
      "శాంతి మంత్రాలు",
      "శక్తివంతమైన సంస్కృత మంత్రాలు",
      "నిత్య పారాయణ మంత్రాలు",
    ],
    spirituality: [
      "ఆధ్యాత్మిక జ్ఞానం",
      "సనాతన ధర్మ విజ్ఞానం",
      "వేదాంత దర్శనం తెలుగులో",
      "భక్తి మార్గం సూత్రాలు",
      "కర్మ సిద్ధాంతం",
    ],
    community: [
      "భక్త సమాజం",
      "ఆధ్యాత్మిక సత్సంగం",
      "భక్తి మండలి",
    ],
    store: [
      "భక్తి స్టోర్",
      "తులసి మాల ఆన్‌లైన్",
      "108 పూసల జపమాల",
      "పూజా సామాగ్రి ఆన్‌లైన్",
      "ఇత్తడి పూజా దీపాలు",
    ],
    tithi: [
      "నేటి తిథి",
      "ఈరోజు తిథి ఏమిటి",
      "ఈరోజు పంచాంగం తెలుగు మంచి సమయం",
      "ఈరోజు తిథి పంచాంగం good time",
      "శుక్ల పక్షం కృష్ణ పక్షం సమయం",
      "నేటి దిన తిథి వివరాలు",
    ],
    quotes: [
      "దైవిక సువిచారాలు",
      "ఆధ్యాత్మిక సూక్తులు",
      "భగవద్గీత సందేశాలు",
      "మంచి మాటలు తెలుగులో",
      "భక్తి వాక్యాలు స్టేటస్",
    ],
    bhajan: [
      "భజనలు & కీర్తనలు",
      "శ్రీకృష్ణ భజనలు లిరిక్స్",
      "శివ భక్తి గీతాలు",
      "రామ సంకీర్తనలు",
      "నిత్య భజన గీతాలు తెలుగులో",
    ],
    aarti: [
      "హారతి పాటలు",
      "నిత్య హారతులు",
      "ఓం జై జగదీశ హరే హారతి",
      "శ్రీ హనుమాన్ హారతి",
      "శివ హారతి పాటలు",
      "గణపతి హారతి తెలుగులో",
      "లక్ష్మీ దేవి హారతి",
    ],
    chalisa: [
      "చాలీసా సంగ్రహం",
      "శ్రీ హనుమాన్ చాలీసా తెలుగు",
      "శ్రీ హనుమాన్ చాలీసా లిరిక్స్ తెలుగు",
      "శివ చాలీసా అర్థం",
      "దుర్గా చాలీసా",
      "శని చాలీసా",
      "చాలీసా స్తోత్రాలు",
    ],
    more: [
      "ఆధ్యాత్మిక సాధనాలు",
      "వైదిక కాలిక్యులేటర్లు",
      "భక్తి వాయిస్ విశేషాలు",
    ],
    library: [
      "ఆధ్యాత్మిక లైబ్రరీ",
      "దివ్య జ్ఞాన సంపద",
      "వేద జ్ఞాన గ్రంథాలు",
      "ఆధ్యాత్మిక మార్గదర్శనం",
    ],
    angelNumbers: [
      "దేవదూత సంఖ్యలు",
      "ఏంజెల్ నంబర్స్ అర్థం",
      "పునరావృత సంఖ్యల అర్థాలు",
      "సంఖ్యా శాస్త్రం ఆధ్యాత్మికం",
      "ఏంజెల్ నంబర్ 555",
      "ఏంజెల్ నంబర్ 777",
    ],
  },
};
