export const PATHS = {
  naamJaap: "/naam-jaap",
  mala: "/naam-jaap/mala",
  katha: "/katha-stories",
  yatra: "/sacred-yatra-guides",
  yatraPlanner: "/sacred-yatra-guides/planner",
  sadhana: "/daily-sadhana",
  sankalp: "/daily-sadhana/sankalp",
  diary: "/daily-sadhana/diary",
  blog: "/bhakti-blog",
  temples: "/hindu-temples",
  festivals: "/hindu-festivals",
  mantras: "/mantras-for-naam-jaap",
  spirituality: "/spiritual-knowledge",
  community: "/devotee-community",
  store: "/bhakti-store",
  bhajan: "/bhajan-and-kirtan",
  aarti: "/aarti-chants",
  tithi: "/aaj-ki-tithi",
  quotes: "/daily-quotes",
  more: "/more",
} as const;
