export const PATHS = {
  naamJaap: "/naam-jaap",
  mala: "/naam-jaap/mala",
  katha: "/katha",
  yatra: "/yatra",
  yatraPlanner: "/yatra/planner",
  sadhana: "/sadhana",
  sankalp: "/sadhana/sankalp",
  diary: "/sadhana/diary",
  blog: "/blog",
  temples: "/temples",
  festivals: "/festivals",
  mantras: "/mantras",
  spirituality: "/spiritual-knowledge",
  community: "/community",
  store: "/store",
  bhajan: "/bhajans",
  aarti: "/aarti",
  chalisa: "/chalisa",
  tithi: "/tithi-today",
  quotes: "/quotes",
  more: "/more",
  spiritualTools: "/spiritual-tools",
  panchang: "/panchang",
  panchangToday: "/panchang/today",
  panchangTomorrow: "/panchang/tomorrow",
  panchangYesterday: "/panchang/yesterday",
  regionalPanchang: (slug: string) => `/panchang/${slug}`,
  calendar: "/calendar",
  kundli: "/kundli",
  kundliMilan: "/kundli/milan",
  suvicharMaker: "/spiritual-tools/suvichar-maker",
  gita: "/gita",
  muhurat: "/muhurat",
  shubhDates: (slug: string) => `/muhurat/shubh-dates/${slug}`,
  vratUpavas: "/vrat",
  grahan: "/grahan",
  choghadiya: "/muhurat/choghadiya",
  panchak: "/muhurat/panchak",
  bhadra: "/muhurat/bhadra",
  hora: "/muhurat/hora",
  gowriPanchangam: "/muhurat/gowri",
  babyNames: "/spiritual-tools/baby-names",
  printableCalendar: "/calendar/printable",
  grahaSthiti: "/panchang/graha-sthiti",
  gochar: "/panchang/gochar",
  sadeSati: "/kundli/sade-sati",
  ekadashi: "/vrat/ekadashi",
  tarabalam: "/panchang/tarabalam",
  manglikDosha: "/kundli/manglik-dosha",
  kaalSarpDosha: "/kundli/kaal-sarp-dosha",
  library: "/library",
  angelNumbers: "/library/angel-numbers",
  angelNumberDetail: (slug: string) => `/library/angel-numbers/${slug}`,
  dakshina: "/dakshina",
} as const;

