export const PATHS = {
  naamJaap: "/naam-jaap",
  mala: "/naam-jaap/mala",
  katha: "/katha-stories",
  yatra: "/sacred-yatra-guides",
  yatraPlanner: "/sacred-yatra-guides/planner",
  sadhana: "/daily-sadhana",
  sankalp: "/daily-sadhana/sankalp",
  diary: "/daily-sadhana/diary",
  blog: "/bhakti-blog",
  temples: "/hindu-temples",
  festivals: "/hindu-festivals",
  mantras: "/mantras-for-naam-jaap",
  spirituality: "/spiritual-knowledge",
  community: "/devotee-community",
  store: "/bhakti-store",
  bhajan: "/bhajan-and-kirtan",
  aarti: "/aarti-chants",
  chalisa: "/chalisa",
  tithi: "/aaj-ki-tithi",
  quotes: "/daily-quotes",
  more: "/more",
  spiritualTools: "/spiritual-tools",
  panchang: "/panchang",
  panchangToday: "/panchang/today",
  panchangTomorrow: "/panchang/tomorrow",
  panchangYesterday: "/panchang/yesterday",
  regionalPanchang: (slug: string) => `/panchang/${slug}`,
  calendar: "/hindu-calendar",
  kundli: "/kundli",
  kundliMilan: "/kundli-milan",
  suvicharMaker: "/suvichar-card-maker",
  gita: "/bhagavad-gita",
  muhurat: "/muhurat",
  shubhDates: (slug: string) => `/shubh-dates/${slug}`,
  vratUpavas: "/vrat-upavas",
  grahan: "/grahan",
  choghadiya: "/choghadiya",
  panchak: "/panchak",
  bhadra: "/bhadra",
  hora: "/hora",
  gowriPanchangam: "/gowri-panchangam",
  babyNames: "/baby-names",
  printableCalendar: "/printable-calendar",
  grahaSthiti: "/panchang/graha-sthiti",
  gochar: "/panchang/gochar",
  sadeSati: "/kundli/sade-sati",
  ekadashi: "/vrat-upavas/ekadashi",
  tarabalam: "/panchang/tarabalam",
  manglikDosha: "/kundli/manglik-dosha",
  kaalSarpDosha: "/kundli/kaal-sarp-dosha",
  library: "/library",
  angelNumbers: "/library/angel-numbers",
  angelNumberDetail: (slug: string) => `/library/angel-numbers/${slug}`,
} as const;

