export type GrahanType = "solar_total" | "solar_annular" | "solar_partial" | "lunar_total" | "lunar_partial" | "lunar_penumbral";

export interface EclipseEvent {
  id: string;
  year: number;
  dateString: string; // YYYY-MM-DD
  kind: "solar" | "lunar";
  type: GrahanType;
  title: string;
  titleHi: string;
  tithi: string;
  tithiHi: string;
  rashi: string;
  rashiHi: string;
  nakshatra: string;
  nakshatraHi: string;
  sparshaUtc: string; // Start (HH:MM IST/UTC)
  madhyaUtc: string;  // Peak (HH:MM IST/UTC)
  mokshaUtc: string;  // End (HH:MM IST/UTC)
  durationHours: string;
  sutakHoursPrior: number; // 12 for solar, 9 for lunar
  sutakStartIst: string;
  sutakEndIst: string;
  visibleInIndia: boolean;
  sutakApplicableInIndia: boolean;
  visibilityRegions: string;
  visibilityRegionsHi: string;
  spiritualSignificance: string;
  spiritualSignificanceHi: string;
  guidelines: {
    pregnantWomen: string;
    pregnantWomenHi: string;
    mantra: string;
    daan: string;
    daanHi: string;
  };
}

export const ECLIPSE_DATABASE: EclipseEvent[] = [
  // 2025
  {
    id: "lunar-2025-03-14",
    year: 2025,
    dateString: "2025-03-14",
    kind: "lunar",
    type: "lunar_total",
    title: "Total Lunar Eclipse (पूर्ण चंद्र ग्रहण)",
    titleHi: "पूर्ण चंद्र ग्रहण",
    tithi: "Phalguna Purnima",
    tithiHi: "फाल्गुन पूर्णिमा",
    rashi: "Simha (Leo)",
    rashiHi: "सिंह",
    nakshatra: "Uttara Phalguni",
    nakshatraHi: "उत्तराफाल्गुनी",
    sparshaUtc: "10:39 IST",
    madhyaUtc: "12:28 IST",
    mokshaUtc: "14:18 IST",
    durationHours: "3 hrs 39 mins",
    sutakHoursPrior: 9,
    sutakStartIst: "01:39 IST (Mar 14)",
    sutakEndIst: "14:18 IST (Mar 14)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "North America, South America, Europe, Australia, Pacific.",
    visibilityRegionsHi: "उत्तरी व दक्षिणी अमेरिका, यूरोप, ऑस्ट्रेलिया एवं प्रशांत महासागर।",
    spiritualSignificance: "Occurs during daytime in India; hence not physically visible. Sutak rules do not apply for religious activities in India, though meditative sadhana remains spiritually fruitful.",
    spiritualSignificanceHi: "भारत में दिन के समय होने के कारण यह दृश्यमान नहीं है। शास्त्रानुसार जहाँ ग्रहण न दिखे वहाँ सूतक के नियम मान्य नहीं होते।",
    guidelines: {
      pregnantWomen: "Stay indoors during peak hours if in visibility zones; maintain relaxed prayer.",
      pregnantWomenHi: "दृश्यमान क्षेत्रों में रहने वाली गर्भवती महिलाएं शांत मन से जप करें।",
      mantra: "ॐ सों सोमाय नमः॥ (अथवा: ॐ नमः शिवाय)",
      daan: "Donate white articles: rice, sugar, white clothes after eclipse.",
      daanHi: "चावल, चीनी, दूध अथवा श्वेत वस्त्रों का दान करें।",
    },
  },
  {
    id: "solar-2025-03-29",
    year: 2025,
    dateString: "2025-03-29",
    kind: "solar",
    type: "solar_partial",
    title: "Partial Solar Eclipse (खंडग्रास सूर्य ग्रहण)",
    titleHi: "आंशिक सूर्य ग्रहण",
    tithi: "Chaitra Amavasya",
    tithiHi: "चैत्र अमावस्या",
    rashi: "Meena (Pisces)",
    rashiHi: "मीन",
    nakshatra: "Uttara Bhadrapada",
    nakshatraHi: "उत्तराभाद्रपद",
    sparshaUtc: "14:20 IST",
    madhyaUtc: "16:17 IST",
    mokshaUtc: "18:14 IST",
    durationHours: "3 hrs 54 mins",
    sutakHoursPrior: 12,
    sutakStartIst: "02:20 IST (Mar 29)",
    sutakEndIst: "18:14 IST (Mar 29)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "Northern Europe, North Russia, Greenland, Atlantic Ocean.",
    visibilityRegionsHi: "उत्तरी यूरोप, रूस, ग्रीनलैंड व अटलांटिक महासागर।",
    spiritualSignificance: "Not visible in India. Daily puja and temple rituals continue uninterrupted.",
    spiritualSignificanceHi: "भारत में अदृश्य होने से दैनिक पूजा-अर्चना व मंदिर दर्शन यथावत रहेंगे।",
    guidelines: {
      pregnantWomen: "Routine guidelines apply.",
      pregnantWomenHi: "सामान्य दिनचर्या रखें।",
      mantra: "ॐ सूर्याय नमः॥ ॐ घृणि सूर्याय नमः॥",
      daan: "Wheat, copper utensils, jaggery.",
      daanHi: "गेहूं, तांबे का पात्र व गुड़ का दान।",
    },
  },
  {
    id: "lunar-2025-09-07",
    year: 2025,
    dateString: "2025-09-07",
    kind: "lunar",
    type: "lunar_total",
    title: "Total Lunar Eclipse (खग्रास चंद्र ग्रहण) — Fully Visible in India",
    titleHi: "खग्रास चंद्र ग्रहण (भारत में पूर्णतः दृश्य)",
    tithi: "Bhadrapada Purnima",
    tithiHi: "भाद्रपद पूर्णिमा",
    rashi: "Kumbha (Aquarius)",
    rashiHi: "कुंभ",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    sparshaUtc: "21:57 IST",
    madhyaUtc: "23:42 IST",
    mokshaUtc: "01:27 IST (Sep 8)",
    durationHours: "3 hrs 30 mins",
    sutakHoursPrior: 9,
    sutakStartIst: "12:57 IST (Sep 7)",
    sutakEndIst: "01:27 IST (Sep 8)",
    visibleInIndia: true,
    sutakApplicableInIndia: true,
    visibilityRegions: "India (complete), Asia, Europe, Africa, Australia, Indian Ocean.",
    visibilityRegionsHi: "सम्पूर्ण भारत, एशिया, यूरोप, अफ्रीका, ऑस्ट्रेलिया व हिन्द महासागर।",
    spiritualSignificance: "MAJOR ECLIPSE IN INDIA. Sutak Kaal begins 9 hours prior at 12:57 PM. Temple doors close during Sutak and eclipse. Chanting mantras during this time multiplies merits manifold.",
    spiritualSignificanceHi: "भारत में पूर्णतः दृश्य होने से सूतक के सभी नियम अनिवार्य हैं। दोपहर १२:५७ से सूतक लगेगा। मंदिरों के कपाट बंद रहेंगे। ग्रहण कालीन जप अत्यंत फलदायी है।",
    guidelines: {
      pregnantWomen: "Avoid cutting, sewing, using knives/scissors during eclipse hours. Rest comfortably and chant Hanuman Chalisa or Vishnu Sahasranama.",
      pregnantWomenHi: "ग्रहण काल में नुकीली वस्तुओं का प्रयोग न करें, शयन से बचें तथा भगवान विष्णु अथवा हनुमान जी का स्मरण करें।",
      mantra: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय मामृतात्॥",
      daan: "White sesame, rice, silver coins, and fresh food after taking bath post-Moksha.",
      daanHi: "मोक्ष के बाद स्नान कर चावल, दूध, चांदी अथवा जरूरतमंदों को भोजन का दान करें।",
    },
  },
  {
    id: "solar-2025-09-21",
    year: 2025,
    dateString: "2025-09-21",
    kind: "solar",
    type: "solar_partial",
    title: "Partial Solar Eclipse (खंडग्रास सूर्य ग्रहण)",
    titleHi: "खंडग्रास सूर्य ग्रहण",
    tithi: "Ashwina Amavasya (Sarva Pitru Amavasya)",
    tithiHi: "अश्विन अमावस्या (सर्वपितृ अमावस्या)",
    rashi: "Kanya (Virgo)",
    rashiHi: "कन्या",
    nakshatra: "Uttara Phalguni",
    nakshatraHi: "उत्तराफाल्गुनी",
    sparshaUtc: "22:59 IST",
    madhyaUtc: "01:12 IST (Sep 22)",
    mokshaUtc: "03:24 IST (Sep 22)",
    durationHours: "4 hrs 25 mins",
    sutakHoursPrior: 12,
    sutakStartIst: "10:59 IST (Sep 21)",
    sutakEndIst: "03:24 IST (Sep 22)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "South Pacific, New Zealand, Antarctica.",
    visibilityRegionsHi: "दक्षिणी प्रशांत, न्यूजीलैंड व अंटार्कटिका।",
    spiritualSignificance: "Occurs during Indian nighttime. Does not disrupt Sarva Pitru Amavasya Tarpan rituals in India.",
    spiritualSignificanceHi: "भारत में रात्रि होने के कारण श्राद्ध व सर्वपितृ तर्पण कार्य निर्विघ्न संपन्न होंगे।",
    guidelines: {
      pregnantWomen: "No special restrictions in India.",
      pregnantWomenHi: "भारत में कोई प्रतिबंध लागू नहीं।",
      mantra: "ॐ पितृभ्यो नमः॥ ॐ नमो भगवते वासुदेवाय॥",
      daan: "Charity for ancestors (Anna Daan / Vastra Daan).",
      daanHi: "पितरों के निमित्त अन्न व वस्त्र दान।",
    },
  },

  // 2026
  {
    id: "solar-2026-02-17",
    year: 2026,
    dateString: "2026-02-17",
    kind: "solar",
    type: "solar_annular",
    title: "Annular Solar Eclipse (कंकणाकृति सूर्य ग्रहण)",
    titleHi: "कंकणाकृति सूर्य ग्रहण (Ring of Fire)",
    tithi: "Phalguna Amavasya",
    tithiHi: "फाल्गुन अमावस्या",
    rashi: "Kumbha (Aquarius)",
    rashiHi: "कुंभ",
    nakshatra: "Dhanishta",
    nakshatraHi: "धनिष्ठा",
    sparshaUtc: "15:26 IST",
    madhyaUtc: "17:42 IST",
    mokshaUtc: "19:57 IST",
    durationHours: "4 hrs 31 mins",
    sutakHoursPrior: 12,
    sutakStartIst: "03:26 IST (Feb 17)",
    sutakEndIst: "19:57 IST (Feb 17)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "Antarctica, Southern tip of South America, Indian Ocean.",
    visibilityRegionsHi: "अंटार्कटिका, दक्षिणी अमेरिका का दक्षिणी भाग व दक्षिणी हिन्द महासागर।",
    spiritualSignificance: "Spectacular 'Ring of Fire' visible in polar regions; not visible in India.",
    spiritualSignificanceHi: "कंकणाकार वलय ध्रुवीय क्षेत्रों में दिखेगा; भारत में अदृश्य होने से सूतक नहीं लगेगा।",
    guidelines: {
      pregnantWomen: "Routine daily life in India.",
      pregnantWomenHi: "सामान्य जीवन शैली।",
      mantra: "ॐ आदित्याय नमः॥",
      daan: "Copper items or jaggery.",
      daanHi: "तांबे का पात्र अथवा गुड़ का दान।",
    },
  },
  {
    id: "lunar-2026-03-03",
    year: 2026,
    dateString: "2026-03-03",
    kind: "lunar",
    type: "lunar_total",
    title: "Total Lunar Eclipse (खग्रास चंद्र ग्रहण) — Visible in India",
    titleHi: "खग्रास चंद्र ग्रहण (भारत में दृश्य)",
    tithi: "Phalguna Purnima (Holi)",
    tithiHi: "फाल्गुन पूर्णिमा (होलिका)",
    rashi: "Simha (Leo)",
    rashiHi: "सिंह",
    nakshatra: "Purva Phalguni",
    nakshatraHi: "पूर्वाफाल्गुनी",
    sparshaUtc: "16:20 IST",
    madhyaUtc: "17:04 IST",
    mokshaUtc: "20:44 IST",
    durationHours: "4 hrs 24 mins",
    sutakHoursPrior: 9,
    sutakStartIst: "07:20 IST (Mar 3)",
    sutakEndIst: "20:44 IST (Mar 3)",
    visibleInIndia: true,
    sutakApplicableInIndia: true,
    visibilityRegions: "India (visible during moonrise), Asia, Australia, Pacific, Americas.",
    visibilityRegionsHi: "सम्पूर्ण भारत (चंद्रोदय के समय दृश्य), एशिया, ऑस्ट्रेलिया व अमेरिका।",
    spiritualSignificance: "Occurs on Phalguna Purnima. In India, Moon rises while eclipsed (Grasthodaya). Sutak is fully applicable across India from 07:20 AM. Extraordinary spiritual energy for Shiva and Vishnu japa.",
    spiritualSignificanceHi: "फाल्गुन पूर्णिमा पर ग्रस्तोदित चंद्र ग्रहण। भारत में चंद्रोदय के साथ ग्रहण दिखेगा। प्रातः ०७:२० से सूतक प्रारंभ होगा। होलिका दहन मुहूर्त पर इसका विशेष प्रभाव रहता है।",
    guidelines: {
      pregnantWomen: "Remain indoors during moonrise to moksha (5:45 PM to 8:44 PM). Chant Om Namah Shivaya.",
      pregnantWomenHi: "शाम को चंद्रोदय से मोक्ष तक घर के भीतर रहें तथा भगवान शिव का जप करें।",
      mantra: "ॐ नमः शिवाय॥ ॐ सोमाय नमः॥",
      daan: "Donate milk, rice, white clothes, and silver after 8:45 PM.",
      daanHi: "रात्रि ८:४५ के बाद स्नान कर दूध, चावल एवं वस्त्र का दान करें।",
    },
  },
  {
    id: "solar-2026-08-12",
    year: 2026,
    dateString: "2026-08-12",
    kind: "solar",
    type: "solar_total",
    title: "Total Solar Eclipse (पूर्ण सूर्य ग्रहण)",
    titleHi: "पूर्ण सूर्य ग्रहण",
    tithi: "Shravana Amavasya",
    tithiHi: "श्रावण अमावस्या",
    rashi: "Karka (Cancer)",
    rashiHi: "कर्क",
    nakshatra: "Ashlesha",
    nakshatraHi: "आश्लेषा",
    sparshaUtc: "20:35 IST",
    madhyaUtc: "23:17 IST",
    mokshaUtc: "01:58 IST (Aug 13)",
    durationHours: "5 hrs 23 mins",
    sutakHoursPrior: 12,
    sutakStartIst: "08:35 IST (Aug 12)",
    sutakEndIst: "01:58 IST (Aug 13)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "Greenland, Iceland, Spain, Northern Portugal, Arctic.",
    visibilityRegionsHi: "ग्रीनलैंड, आइसलैंड, स्पेन, पुर्तगाल व उत्तरी अटलांटिक।",
    spiritualSignificance: "Major European total eclipse; occurs during nighttime in India and is not visible. No Sutak in India.",
    spiritualSignificanceHi: "यूरोप में पूर्ण सूर्य ग्रहण; भारत में रात्रि होने से अदृश्य। सूतक लागू नहीं होगा।",
    guidelines: {
      pregnantWomen: "No restrictions in India.",
      pregnantWomenHi: "भारत में कोई नियम लागू नहीं।",
      mantra: "ॐ घृणिः सूर्य आदित्यः॥",
      daan: "Red lentils (Masoor), wheat.",
      daanHi: "लाल मसूर व गेहूं का दान।",
    },
  },
  {
    id: "lunar-2026-08-28",
    year: 2026,
    dateString: "2026-08-28",
    kind: "lunar",
    type: "lunar_partial",
    title: "Partial Lunar Eclipse (खंडग्रास चंद्र ग्रहण)",
    titleHi: "खंडग्रास चंद्र ग्रहण",
    tithi: "Bhadrapada Purnima",
    tithiHi: "भाद्रपद पूर्णिमा",
    rashi: "Kumbha (Aquarius)",
    rashiHi: "कुंभ",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    sparshaUtc: "07:53 IST",
    madhyaUtc: "09:44 IST",
    mokshaUtc: "11:35 IST",
    durationHours: "3 hrs 42 mins",
    sutakHoursPrior: 9,
    sutakStartIst: "22:53 IST (Aug 27)",
    sutakEndIst: "11:35 IST (Aug 28)",
    visibleInIndia: false,
    sutakApplicableInIndia: false,
    visibilityRegions: "North & South America, Europe, Africa, Pacific Ocean.",
    visibilityRegionsHi: "उत्तर व दक्षिण अमेरिका, यूरोप, अफ्रीका व अटलांटिक महासागर।",
    spiritualSignificance: "Occurs in daytime in India; not visible. Normal Bhadrapada Purnima rituals continue.",
    spiritualSignificanceHi: "भारत में दिन में होने से दृश्य नहीं है। पूर्णिमा पूजा यथावत संपन्न होगी।",
    guidelines: {
      pregnantWomen: "Routine daily life.",
      pregnantWomenHi: "सामान्य दिनचर्या।",
      mantra: "ॐ चन्द्राय नमः॥",
      daan: "White flowers, camphor (Karpur), rice.",
      daanHi: "कपूर, चावल व श्वेत पुष्प।",
    },
  },

  // 2027
  {
    id: "solar-2027-08-02",
    year: 2027,
    dateString: "2027-08-02",
    kind: "solar",
    type: "solar_total",
    title: "Total Solar Eclipse of the Century (सदी का महान सूर्य ग्रहण)",
    titleHi: "सदी का महान सूर्य ग्रहण (६ मिनट २२ सेकंड)",
    tithi: "Shravana/Bhadrapada Amavasya",
    tithiHi: "श्रावण/भाद्रपद अमावस्या",
    rashi: "Karka (Cancer)",
    rashiHi: "कर्क",
    nakshatra: "Pushya",
    nakshatraHi: "पुष्य",
    sparshaUtc: "13:30 IST",
    madhyaUtc: "15:37 IST",
    mokshaUtc: "18:45 IST",
    durationHours: "5 hrs 15 mins (Totality: 6m 22s)",
    sutakHoursPrior: 12,
    sutakStartIst: "01:30 IST (Aug 2)",
    sutakEndIst: "18:45 IST (Aug 2)",
    visibleInIndia: true,
    sutakApplicableInIndia: true,
    visibilityRegions: "North Africa (Luxor Egypt 6m 22s), Middle East, Southern Europe, Western India (Gujarat/Rajasthan visible as partial).",
    visibilityRegionsHi: "उत्तरी अफ्रीका (मिस्र), मध्य पूर्व, दक्षिणी यूरोप, पश्चिमी भारत (गुजरात, राजस्थान में आंशिक रूप से दृश्य)।",
    spiritualSignificance: "HISTORIC ECLIPSE. One of the longest total eclipses of the 21st century. Visible partially in Western India before sunset. Immense spiritual transformation.",
    spiritualSignificanceHi: "२१वीं सदी का सबसे लंबा सूर्य ग्रहण (६ मिनट से अधिक)। पश्चिमी भारत में आंशिक रूप से दृश्य होगा। आध्यात्मिक साधना हेतु अति दुर्लभ अवसर।",
    guidelines: {
      pregnantWomen: "Rest in calm, peaceful environment; recite Aditya Hridaya Stotram.",
      pregnantWomenHi: "शांत वातावरण में विश्राम करें तथा आदित्य हृदय स्तोत्र का पाठ करें।",
      mantra: "ॐ ह्रीं ह्रीं सूर्याय नमः॥",
      daan: "Gold, copper, wheat, red clothes, ruby or red items.",
      daanHi: "गेहूं, गुड़, लाल वस्त्र व तांबे के पात्र का दान।",
    },
  },
];

export function getEclipsesForYear(year: number): EclipseEvent[] {
  return ECLIPSE_DATABASE.filter((e) => e.year === year);
}
