export { DELHI } from "./cities";

export const TITHI_NAMES = [
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima / Amavasya",
] as const;

export const TITHI_NAMES_HI = [
  "प्रतिपदा",
  "द्वितीया",
  "तृतीया",
  "चतुर्थी",
  "पञ्चमी",
  "षष्ठी",
  "सप्तमी",
  "अष्टमी",
  "नवमी",
  "दशमी",
  "एकादशी",
  "द्वादशी",
  "त्रयोदशी",
  "चतुर्दशी",
  "पूर्णिमा / अमावस्या",
] as const;

export const MASA_NAMES = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashvina",
  "Kartika",
  "Margashirsha",
  "Pausha",
  "Magha",
  "Phalguna",
] as const;

export const MASA_NAMES_HI = [
  "चैत्र",
  "वैशाख",
  "ज्येष्ठ",
  "आषाढ़",
  "श्रावण",
  "भाद्रपद",
  "आश्विन",
  "कार्तिक",
  "मार्गशीर्ष",
  "पौष",
  "माघ",
  "फाल्गुन",
] as const;

export const RASI_NAMES = [
  "Mesha (Aries)",
  "Vrishabha (Taurus)",
  "Mithuna (Gemini)",
  "Karka (Cancer)",
  "Simha (Leo)",
  "Kanya (Virgo)",
  "Tula (Libra)",
  "Vrischika (Scorpio)",
  "Dhanu (Sagittarius)",
  "Makara (Capricorn)",
  "Kumbha (Aquarius)",
  "Meena (Pisces)",
] as const;

export const RASI_NAMES_HI = [
  "मेष",
  "वृषभ",
  "मिथुन",
  "कर्क",
  "सिंह",
  "कन्या",
  "तुला",
  "वृश्चिक",
  "धनु",
  "मकर",
  "कुंभ",
  "मीन",
] as const;

export const NAKSHATRA_NAMES = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
] as const;

export const NAKSHATRA_NAMES_HI = [
  "अश्विनी",
  "भरणी",
  "कृत्तिका",
  "रोहिणी",
  "मृगशिरा",
  "आर्द्रा",
  "पुनर्वसु",
  "पुष्य",
  "आश्लेषा",
  "मघा",
  "पूर्वा फाल्गुनी",
  "उत्तरा फाल्गुनी",
  "हस्त",
  "चित्रा",
  "स्वाती",
  "विशाखा",
  "अनुराधा",
  "ज्येष्ठा",
  "मूल",
  "पूर्वाषाढ़ा",
  "उत्तराषाढ़ा",
  "श्रवण",
  "धनिष्ठा",
  "शतभिषा",
  "पूर्वा भाद्रपद",
  "उत्तरा भाद्रपद",
  "रेवती",
] as const;

export const NAKSHATRA_DEITIES = [
  "Ashwini Kumaras",
  "Yama",
  "Agni",
  "Brahma / Prajapati",
  "Soma (Chandra)",
  "Rudra (Shiva)",
  "Aditi",
  "Brihaspati",
  "Sarpa (Nagas)",
  "Pitris (Ancestors)",
  "Bhaga",
  "Aryaman",
  "Savitr (Surya)",
  "Vishwakarma",
  "Vayu",
  "Indragni",
  "Mitra",
  "Indra",
  "Nirriti",
  "Apas (Water)",
  "Vishwadevas",
  "Vishnu",
  "Vasus",
  "Varuna",
  "Aja Ekapada",
  "Ahirbudhnya",
  "Pushan",
] as const;

export const YOGA_NAMES = [
  "Vishkambha",
  "Priti",
  "Ayushman",
  "Saubhagya",
  "Shobhana",
  "Atiganda",
  "Sukarma",
  "Dhriti",
  "Shula",
  "Ganda",
  "Vriddhi",
  "Dhruva",
  "Vyaghata",
  "Harshana",
  "Vajra",
  "Siddhi",
  "Vyatipata",
  "Variyan",
  "Parigha",
  "Shiva",
  "Siddha",
  "Sadhya",
  "Shubha",
  "Shukla",
  "Brahma",
  "Indra",
  "Vaidhriti",
] as const;

export const YOGA_NAMES_HI = [
  "विष्कुम्भ",
  "प्रीति",
  "आयुष्मान",
  "सौभाग्य",
  "शोभन",
  "अतिगण्ड",
  "सुकर्मा",
  "धृति",
  "शूल",
  "गण्ड",
  "वृद्धि",
  "ध्रुव",
  "व्याघात",
  "हर्षण",
  "वज्र",
  "सिद्धि",
  "व्यतीपात",
  "वरीयान्",
  "परिघ",
  "शिव",
  "सिद्ध",
  "साध्य",
  "शुभ",
  "शुक्ल",
  "ब्रह्म",
  "इन्द्र",
  "वैधृति",
] as const;

export const KARANA_NAMES = [
  "Bava",
  "Balava",
  "Kaulava",
  "Taitila",
  "Gara",
  "Vanija",
  "Vishti (Bhadra)",
  "Shakuni",
  "Chatushpada",
  "Naga",
  "Kimstughna",
] as const;

export const KARANA_NAMES_HI = [
  "बव",
  "बालव",
  "कौलव",
  "तैतिल",
  "गर",
  "वणिज",
  "विष्टि (भद्रा)",
  "शकुनि",
  "चतुष्पद",
  "नाग",
  "किंस्तुघ्न",
] as const;

export const RITU_NAMES = [
  "Vasanta (Spring)",
  "Grishma (Summer)",
  "Varsha (Monsoon)",
  "Sharad (Autumn)",
  "Hemanta (Pre-winter)",
  "Shishira (Winter)",
] as const;

export const RITU_NAMES_HI = [
  "वसन्त (Spring)",
  "ग्रीष्म (Summer)",
  "वर्षा (Monsoon)",
  "शरद् (Autumn)",
  "हेमन्त (Pre-winter)",
  "शिशिर (Winter)",
] as const;

export const VARA_NAMES = [
  "Sunday (Ravivara)",
  "Monday (Somavara)",
  "Tuesday (Mangalavara)",
  "Wednesday (Budhavara)",
  "Thursday (Guruvara)",
  "Friday (Shukravara)",
  "Saturday (Shanivara)",
] as const;

export const VARA_NAMES_HI = [
  "रविवार",
  "सोमवार",
  "मंगलवार",
  "बुधवार",
  "गुरुवार",
  "शुक्रवार",
  "शनिवार",
] as const;

/** 1-indexed eighth of the day (sunrise→sunset) that is Rahu Kaal. Sunday=0. */
export const RAHU_KAAL_PERIOD = [8, 2, 7, 5, 6, 4, 3] as const;
/** 1-indexed eighth of the day that is Yamaganda. Sunday=0. */
export const YAMAGANDA_PERIOD = [5, 4, 3, 2, 1, 7, 6] as const;
/** 1-indexed eighth of the day that is Gulika Kaal. Sunday=0. */
export const GULIKA_PERIOD = [7, 6, 5, 4, 3, 2, 1] as const;

export const MONTH_NAMES_EN = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const MONTH_NAMES_HI = [
  "जनवरी",
  "फरवरी",
  "मार्च",
  "अप्रैल",
  "मई",
  "जून",
  "जुलाई",
  "अगस्त",
  "सितंबर",
  "अक्टूबर",
  "नवंबर",
  "दिसंबर",
];
