/**
 * Vedic Baby Names (Naamkaran Samskara) Data & Syllables Engine
 * Includes the 108 sacred Nakshatra Pada syllables (Namaksharas),
 * 12 Rashi letters, and 300+ authentic Vedic baby names with spiritual meanings.
 */

export type Gender = "boy" | "girl" | "unisex";

export type NakshatraPadaSyllable = {
  nakshatraIndex: number; // 0 to 26
  nakshatraName: string;
  nakshatraNameHi: string;
  rashiIndex: number; // primary rashi
  rashiName: string;
  rashiNameHi: string;
  padas: [string, string, string, string]; // English syllables for Padas 1, 2, 3, 4
  padasHi: [string, string, string, string]; // Devanagari syllables for Padas 1, 2, 3, 4
};

export type VedicBabyName = {
  name: string; // English
  nameHi: string; // Hindi / Devanagari
  gender: Gender;
  meaning: string;
  meaningHi: string;
  deity?: string;
  deityHi?: string;
  nakshatra: string;
  nakshatraHi: string;
  pada?: number;
  rashi: string;
  rashiHi: string;
  startingLetter: string;
  numerology: number; // 1-9
};

export const NAKSHATRA_SYLLABLES: NakshatraPadaSyllable[] = [
  {
    nakshatraIndex: 0,
    nakshatraName: "Ashwini",
    nakshatraNameHi: "अश्विनी",
    rashiIndex: 0,
    rashiName: "Aries",
    rashiNameHi: "मेष",
    padas: ["Chu", "Che", "Cho", "La"],
    padasHi: ["चु", "चे", "चो", "ला"],
  },
  {
    nakshatraIndex: 1,
    nakshatraName: "Bharani",
    nakshatraNameHi: "भरणी",
    rashiIndex: 0,
    rashiName: "Aries",
    rashiNameHi: "मेष",
    padas: ["Lee", "Lu", "Le", "Lo"],
    padasHi: ["ली", "लू", "ले", "लो"],
  },
  {
    nakshatraIndex: 2,
    nakshatraName: "Krittika",
    nakshatraNameHi: "कृत्तिका",
    rashiIndex: 0, // Pada 1 Aries, 2-4 Taurus
    rashiName: "Aries / Taurus",
    rashiNameHi: "मेष / वृषभ",
    padas: ["A", "Ee", "U", "Ea"],
    padasHi: ["अ", "ई", "उ", "ए"],
  },
  {
    nakshatraIndex: 3,
    nakshatraName: "Rohini",
    nakshatraNameHi: "रोहिणी",
    rashiIndex: 1,
    rashiName: "Taurus",
    rashiNameHi: "वृषभ",
    padas: ["O", "Va", "Vi", "Vu"],
    padasHi: ["ओ", "वा", "वी", "वू"],
  },
  {
    nakshatraIndex: 4,
    nakshatraName: "Mrigashira",
    nakshatraNameHi: "मृगशिरा",
    rashiIndex: 1, // Pada 1-2 Taurus, 3-4 Gemini
    rashiName: "Taurus / Gemini",
    rashiNameHi: "वृषभ / मिथुन",
    padas: ["Ve", "Vo", "Ka", "Kee"],
    padasHi: ["वे", "वो", "का", "की"],
  },
  {
    nakshatraIndex: 5,
    nakshatraName: "Ardra",
    nakshatraNameHi: "आर्द्रा",
    rashiIndex: 2,
    rashiName: "Gemini",
    rashiNameHi: "मिथुन",
    padas: ["Ku", "Gha", "Ng", "Chha"],
    padasHi: ["कु", "घ", "ङ", "छ"],
  },
  {
    nakshatraIndex: 6,
    nakshatraName: "Punarvasu",
    nakshatraNameHi: "पुनर्वसु",
    rashiIndex: 2, // Pada 1-3 Gemini, 4 Cancer
    rashiName: "Gemini / Cancer",
    rashiNameHi: "मिथुन / कर्क",
    padas: ["Ke", "Ko", "Haa", "Hee"],
    padasHi: ["के", "को", "हा", "ही"],
  },
  {
    nakshatraIndex: 7,
    nakshatraName: "Pushya",
    nakshatraNameHi: "पुष्य",
    rashiIndex: 3,
    rashiName: "Cancer",
    rashiNameHi: "कर्क",
    padas: ["Hoo", "He", "Ho", "Daa"],
    padasHi: ["हू", "हे", "हो", "डा"],
  },
  {
    nakshatraIndex: 8,
    nakshatraName: "Ashlesha",
    nakshatraNameHi: "आश्लेषा",
    rashiIndex: 3,
    rashiName: "Cancer",
    rashiNameHi: "कर्क",
    padas: ["Dee", "Doo", "De", "Do"],
    padasHi: ["डी", "डू", "डे", "डो"],
  },
  {
    nakshatraIndex: 9,
    nakshatraName: "Magha",
    nakshatraNameHi: "मघा",
    rashiIndex: 4,
    rashiName: "Leo",
    rashiNameHi: "सिंह",
    padas: ["Maa", "Mee", "Moo", "Me"],
    padasHi: ["मा", "मी", "मू", "मे"],
  },
  {
    nakshatraIndex: 10,
    nakshatraName: "Purva Phalguni",
    nakshatraNameHi: "पूर्वा फाल्गुनी",
    rashiIndex: 4,
    rashiName: "Leo",
    rashiNameHi: "सिंह",
    padas: ["Mo", "Taa", "Tee", "Too"],
    padasHi: ["मो", "टा", "टी", "टू"],
  },
  {
    nakshatraIndex: 11,
    nakshatraName: "Uttara Phalguni",
    nakshatraNameHi: "उत्तरा फाल्गुनी",
    rashiIndex: 4, // Pada 1 Leo, 2-4 Virgo
    rashiName: "Leo / Virgo",
    rashiNameHi: "सिंह / कन्या",
    padas: ["Te", "To", "Paa", "Pee"],
    padasHi: ["टे", "टो", "पा", "पी"],
  },
  {
    nakshatraIndex: 12,
    nakshatraName: "Hasta",
    nakshatraNameHi: "हस्त",
    rashiIndex: 5,
    rashiName: "Virgo",
    rashiNameHi: "कन्या",
    padas: ["Poo", "Sha", "Na", "Thaa"],
    padasHi: ["पू", "ष", "ण", "ठा"],
  },
  {
    nakshatraIndex: 13,
    nakshatraName: "Chitra",
    nakshatraNameHi: "चित्रा",
    rashiIndex: 5, // Pada 1-2 Virgo, 3-4 Libra
    rashiName: "Virgo / Libra",
    rashiNameHi: "कन्या / तुला",
    padas: ["Pe", "Po", "Raa", "Ree"],
    padasHi: ["पे", "पो", "रा", "री"],
  },
  {
    nakshatraIndex: 14,
    nakshatraName: "Swati",
    nakshatraNameHi: "स्वाति",
    rashiIndex: 6,
    rashiName: "Libra",
    rashiNameHi: "तुला",
    padas: ["Roo", "Re", "Ro", "Taa"],
    padasHi: ["रू", "रे", "रो", "ता"],
  },
  {
    nakshatraIndex: 15,
    nakshatraName: "Vishakha",
    nakshatraNameHi: "विशाखा",
    rashiIndex: 6, // Pada 1-3 Libra, 4 Scorpio
    rashiName: "Libra / Scorpio",
    rashiNameHi: "तुला / वृश्चिक",
    padas: ["Tee", "Too", "Te", "To"],
    padasHi: ["ती", "तू", "ते", "तो"],
  },
  {
    nakshatraIndex: 16,
    nakshatraName: "Anuradha",
    nakshatraNameHi: "अनुराधा",
    rashiIndex: 7,
    rashiName: "Scorpio",
    rashiNameHi: "वृश्चिक",
    padas: ["Naa", "Nee", "Noo", "Ne"],
    padasHi: ["ना", "नी", "नू", "ने"],
  },
  {
    nakshatraIndex: 17,
    nakshatraName: "Jyeshtha",
    nakshatraNameHi: "ज्येष्ठा",
    rashiIndex: 7,
    rashiName: "Scorpio",
    rashiNameHi: "वृश्चिक",
    padas: ["No", "Yaa", "Yee", "Yoo"],
    padasHi: ["नो", "या", "यी", "यू"],
  },
  {
    nakshatraIndex: 18,
    nakshatraName: "Mula",
    nakshatraNameHi: "मूल",
    rashiIndex: 8,
    rashiName: "Sagittarius",
    rashiNameHi: "धनु",
    padas: ["Ye", "Yo", "Bhaa", "Bhee"],
    padasHi: ["ये", "यो", "भा", "भी"],
  },
  {
    nakshatraIndex: 19,
    nakshatraName: "Purva Ashadha",
    nakshatraNameHi: "पूर्वाषाढ़ा",
    rashiIndex: 8,
    rashiName: "Sagittarius",
    rashiNameHi: "धनु",
    padas: ["Bhoo", "Dhaa", "Phaa", "Dha"],
    padasHi: ["भू", "धा", "फा", "ढा"],
  },
  {
    nakshatraIndex: 20,
    nakshatraName: "Uttara Ashadha",
    nakshatraNameHi: "उत्तराषाढ़ा",
    rashiIndex: 8, // Pada 1 Sag, 2-4 Capricorn
    rashiName: "Sagittarius / Capricorn",
    rashiNameHi: "धनु / मकर",
    padas: ["Bhe", "Bho", "Jaa", "Jee"],
    padasHi: ["भे", "भो", "जा", "जी"],
  },
  {
    nakshatraIndex: 21,
    nakshatraName: "Shravana",
    nakshatraNameHi: "श्रवण",
    rashiIndex: 9,
    rashiName: "Capricorn",
    rashiNameHi: "मकर",
    padas: ["Khee", "Khoo", "Khe", "Kho"],
    padasHi: ["खी", "खू", "खे", "खो"],
  },
  {
    nakshatraIndex: 22,
    nakshatraName: "Dhanishta",
    nakshatraNameHi: "धनिष्ठा",
    rashiIndex: 9, // Pada 1-2 Cap, 3-4 Aquarius
    rashiName: "Capricorn / Aquarius",
    rashiNameHi: "मकर / कुंभ",
    padas: ["Gaa", "Gee", "Goo", "Ge"],
    padasHi: ["गा", "गी", "गू", "गे"],
  },
  {
    nakshatraIndex: 23,
    nakshatraName: "Shatabhisha",
    nakshatraNameHi: "शतभिषा",
    rashiIndex: 10,
    rashiName: "Aquarius",
    rashiNameHi: "कुंभ",
    padas: ["Go", "Saa", "See", "Soo"],
    padasHi: ["गो", "सा", "सी", "सू"],
  },
  {
    nakshatraIndex: 24,
    nakshatraName: "Purva Bhadrapada",
    nakshatraNameHi: "पूर्वाभाद्रपद",
    rashiIndex: 10, // Pada 1-3 Aqua, 4 Pisces
    rashiName: "Aquarius / Pisces",
    rashiNameHi: "कुंभ / मीन",
    padas: ["Se", "So", "Daa", "Dee"],
    padasHi: ["से", "सो", "दा", "दी"],
  },
  {
    nakshatraIndex: 25,
    nakshatraName: "Uttara Bhadrapada",
    nakshatraNameHi: "उत्तराभाद्रपद",
    rashiIndex: 11,
    rashiName: "Pisces",
    rashiNameHi: "मीन",
    padas: ["Doo", "Thaa", "Jha", "Nya"],
    padasHi: ["दू", "था", "झ", "ञ"],
  },
  {
    nakshatraIndex: 26,
    nakshatraName: "Revati",
    nakshatraNameHi: "रेवती",
    rashiIndex: 11,
    rashiName: "Pisces",
    rashiNameHi: "मीन",
    padas: ["De", "Do", "Chaa", "Chee"],
    padasHi: ["दे", "दो", "चा", "ची"],
  },
];

export const RASHI_LETTERS: {
  rashiIndex: number;
  name: string;
  nameHi: string;
  letters: string[];
  lord: string;
  lordHi: string;
}[] = [
  { rashiIndex: 0, name: "Aries", nameHi: "मेष", letters: ["A", "L", "E", "I"], lord: "Mars", lordHi: "मंगल" },
  { rashiIndex: 1, name: "Taurus", nameHi: "वृषभ", letters: ["B", "V", "U", "W"], lord: "Venus", lordHi: "शुक्र" },
  { rashiIndex: 2, name: "Gemini", nameHi: "मिथुन", letters: ["K", "CHH", "GH", "Q"], lord: "Mercury", lordHi: "बुध" },
  { rashiIndex: 3, name: "Cancer", nameHi: "कर्क", letters: ["H", "DD"], lord: "Moon", lordHi: "चंद्र" },
  { rashiIndex: 4, name: "Leo", nameHi: "सिंह", letters: ["M", "TT"], lord: "Sun", lordHi: "सूर्य" },
  { rashiIndex: 5, name: "Virgo", nameHi: "कन्या", letters: ["P", "TTH", "SH"], lord: "Mercury", lordHi: "बुध" },
  { rashiIndex: 6, name: "Libra", nameHi: "तुला", letters: ["R", "T"], lord: "Venus", lordHi: "शुक्र" },
  { rashiIndex: 7, name: "Scorpio", nameHi: "वृश्चिक", letters: ["N", "Y"], lord: "Mars", lordHi: "मंगल" },
  { rashiIndex: 8, name: "Sagittarius", nameHi: "धनु", letters: ["BH", "DH", "PH", "F"], lord: "Jupiter", lordHi: "गुरु" },
  { rashiIndex: 9, name: "Capricorn", nameHi: "मकर", letters: ["KH", "J"], lord: "Saturn", lordHi: "शनि" },
  { rashiIndex: 10, name: "Aquarius", nameHi: "कुंभ", letters: ["G", "S", "SH"], lord: "Saturn", lordHi: "शनि" },
  { rashiIndex: 11, name: "Pisces", nameHi: "मीन", letters: ["D", "CH", "Z", "TH"], lord: "Jupiter", lordHi: "गुरु" },
];

export const VEDIC_BABY_NAMES: VedicBabyName[] = [
  // --- BOY NAMES ---
  {
    name: "Aarav",
    nameHi: "आरव",
    gender: "boy",
    meaning: "Peaceful sound, wisdom, serene melody",
    meaningHi: "शांत ध्वनि, ज्ञान, शांत व प्रसन्न स्वभाव",
    deity: "Lord Shiva",
    deityHi: "भगवान शिव",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 1,
  },
  {
    name: "Advait",
    nameHi: "अद्वैत",
    gender: "boy",
    meaning: "Non-dual, unique, supreme oneness with the Divine",
    meaningHi: "अद्वितीय, एकात्म, ईश्वर के साथ एकाकार",
    deity: "Brahman / Lord Vishnu",
    deityHi: "परब्रह्म / श्रीहरि",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 7,
  },
  {
    name: "Anay",
    nameHi: "अनाय",
    gender: "boy",
    meaning: "Self-sufficient, having no master (Supreme God Ganesha)",
    meaningHi: "सर्वोपरि, जिसका कोई स्वामी न हो (श्री गणेश)",
    deity: "Lord Ganesha",
    deityHi: "भगवान श्री गणेश",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 9,
  },
  {
    name: "Agastya",
    nameHi: "अगस्त्य",
    gender: "boy",
    meaning: "The venerable Vedic sage who humbled the Vindhya mountains",
    meaningHi: "विंध्याचल पर्वत को झुकाने वाले महर्षि अगस्त्य",
    deity: "Sage Agastya / Shiva",
    deityHi: "महर्षि अगस्त्य / शिव",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 8,
  },
  {
    name: "Chaitanya",
    nameHi: "चैतन्य",
    gender: "boy",
    meaning: "Pure divine consciousness, supreme spiritual radiance",
    meaningHi: "शुद्ध आत्मचेतना, परब्रह्म का दिव्य प्रकाश",
    deity: "Sri Chaitanya Mahaprabhu / Krishna",
    deityHi: "श्री चैतन्य महाप्रभु / श्रीकृष्ण",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "Ch",
    numerology: 5,
  },
  {
    name: "Chirag",
    nameHi: "चिराग",
    gender: "boy",
    meaning: "Lamp, beacon of spiritual light and guidance",
    meaningHi: "दीपक, ज्ञान और प्रकाश की ज्योति",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "Ch",
    numerology: 3,
  },
  {
    name: "Chirayu",
    nameHi: "चिरायु",
    gender: "boy",
    meaning: "Blessed with long life and immortal spiritual glory",
    meaningHi: "दीर्घायु, अमर यश और आरोग्य से युक्त",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "Ch",
    numerology: 6,
  },
  {
    name: "Lakshya",
    nameHi: "लक्ष्य",
    gender: "boy",
    meaning: "Aim, sacred purpose of life, destination",
    meaningHi: "ध्येय, जीवन का परम उद्देश्य, लक्ष्य",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "L",
    numerology: 4,
  },
  {
    name: "Lalit",
    nameHi: "ललित",
    gender: "boy",
    meaning: "Graceful, beautiful, deeply charming",
    meaningHi: "सुंदर, आकर्षक, सौम्य एवं मधुर",
    deity: "Lord Krishna",
    deityHi: "भगवान श्रीकृष्ण",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "L",
    numerology: 6,
  },
  {
    name: "Lokendra",
    nameHi: "लोकेन्द्र",
    gender: "boy",
    meaning: "King of the universe, Lord of all realms",
    meaningHi: "तीनों लोकों के स्वामी (भगवान विष्णु)",
    deity: "Lord Vishnu",
    deityHi: "भगवान विष्णु",
    nakshatra: "Bharani",
    nakshatraHi: "भरणी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "L",
    numerology: 8,
  },
  {
    name: "Varun",
    nameHi: "वरुण",
    gender: "boy",
    meaning: "Lord of the cosmic waters, keeper of cosmic moral order (Rta)",
    meaningHi: "जल के अधिपति देव, ब्रह्मांडीय सत्य के रक्षक",
    deity: "Varuna Deva",
    deityHi: "वरुण देव",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 3,
  },
  {
    name: "Vivaan",
    nameHi: "विवान",
    gender: "boy",
    meaning: "Full of vitality, first rays of the dawn sun",
    meaningHi: "प्रातःकालीन सूर्य की प्रथम किरणें, जीवन शक्ति",
    deity: "Surya Deva",
    deityHi: "सूर्य देव",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 1,
  },
  {
    name: "Vihan",
    nameHi: "विहान",
    gender: "boy",
    meaning: "Morning dawn, auspicious beginning of a new day",
    meaningHi: "प्रभात, उषाकाल, नई शुरुआत",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 5,
  },
  {
    name: "Keshav",
    nameHi: "केशव",
    gender: "boy",
    meaning: "Having divine black locks, slayer of the demon Keshi",
    meaningHi: "भगवान श्रीकृष्ण का पवित्र नाम, केशी दैत्य का वध करने वाले",
    deity: "Lord Krishna",
    deityHi: "भगवान श्रीकृष्ण",
    nakshatra: "Mrigashira",
    nakshatraHi: "मृगशिरा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 7,
  },
  {
    name: "Kushagra",
    nameHi: "कुशाग्र",
    gender: "boy",
    meaning: "Sharp-witted, brilliant intellect like the tip of sacred Kusha grass",
    meaningHi: "कुशा के अग्र भाग के समान तीक्ष्ण बुद्धि वाला",
    nakshatra: "Ardra",
    nakshatraHi: "आर्द्रा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 4,
  },
  {
    name: "Harshavardhan",
    nameHi: "हर्षवर्धन",
    gender: "boy",
    meaning: "One who continuously expands joy and happiness",
    meaningHi: "आनंद और हर्ष की निरंतर वृद्धि करने वाला",
    nakshatra: "Punarvasu",
    nakshatraHi: "पुनर्वसु",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "H",
    numerology: 9,
  },
  {
    name: "Hriday",
    nameHi: "हृदय",
    gender: "boy",
    meaning: "Heart, the sacred inner sanctum where the Divine resides",
    meaningHi: "हृदय, प्रेम और दया का निवास स्थान",
    nakshatra: "Pushya",
    nakshatraHi: "पुष्य",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "H",
    numerology: 2,
  },
  {
    name: "Devrat",
    nameHi: "देवव्रत",
    gender: "boy",
    meaning: "Firm devotion to God, original name of Bhishma Pitamaha",
    meaningHi: "देवताओं के प्रति समर्पित व्रत, भीष्म पितामह का मूल नाम",
    nakshatra: "Ashlesha",
    nakshatraHi: "आश्लेषा",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "D",
    numerology: 8,
  },
  {
    name: "Madhav",
    nameHi: "माधव",
    gender: "boy",
    meaning: "Lord of Goddess Lakshmi (Maa Dhava), Krishna in springtime",
    meaningHi: "मां लक्ष्मी के स्वामी, वसंत ऋतु के अधिपति श्रीकृष्ण",
    deity: "Lord Krishna",
    deityHi: "भगवान श्रीकृष्ण",
    nakshatra: "Magha",
    nakshatraHi: "मघा",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "M",
    numerology: 6,
  },
  {
    name: "Manan",
    nameHi: "मनन",
    gender: "boy",
    meaning: "Deep contemplation, profound meditation upon truth",
    meaningHi: "गहरा विचार, आत्मचिंतन, ध्यान",
    nakshatra: "Magha",
    nakshatraHi: "मघा",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "M",
    numerology: 5,
  },
  {
    name: "Tejas",
    nameHi: "तेजस",
    gender: "boy",
    meaning: "Radiance, divine spiritual power, inner fiery brilliance",
    meaningHi: "तेज, आत्मिक कांति, शौर्य और दिव्यता",
    deity: "Surya Deva",
    deityHi: "सूर्य देव",
    nakshatra: "Uttara Phalguni",
    nakshatraHi: "उत्तरा फाल्गुनी",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "T",
    numerology: 1,
  },
  {
    name: "Parth",
    nameHi: "पार्थ",
    gender: "boy",
    meaning: "Son of Pritha (Kunti), the heroic archer Arjuna",
    meaningHi: "माता पृथा (कुंती) के पुत्र अर्जुन, धर्मयोद्धा",
    deity: "Arjuna / Krishna",
    deityHi: "अर्जुन / श्रीकृष्ण",
    nakshatra: "Uttara Phalguni",
    nakshatraHi: "उत्तरा फाल्गुनी",
    rashi: "Virgo",
    rashiHi: "कन्या",
    startingLetter: "P",
    numerology: 7,
  },
  {
    name: "Pranav",
    nameHi: "प्रणव",
    gender: "boy",
    meaning: "The sacred primordial syllable OM, primordial sound of Creation",
    meaningHi: "परम पावन ओंकार ध्वनि, सृष्टि का मूल स्वर",
    deity: "Brahman / Shiva",
    deityHi: "परब्रह्म / शिव",
    nakshatra: "Hasta",
    nakshatraHi: "हस्त",
    rashi: "Virgo",
    rashiHi: "कन्या",
    startingLetter: "P",
    numerology: 9,
  },
  {
    name: "Rudra",
    nameHi: "रुद्र",
    gender: "boy",
    meaning: "The fierce destroyer of ignorance, supreme compassionate Shiva",
    meaningHi: "अज्ञान और पापों का नाश करने वाले भगवान शिव",
    deity: "Lord Shiva",
    deityHi: "भगवान शिव",
    nakshatra: "Chitra",
    nakshatraHi: "चित्रा",
    rashi: "Libra",
    rashiHi: "तुला",
    startingLetter: "R",
    numerology: 9,
  },
  {
    name: "Reyansh",
    nameHi: "रेयांश",
    gender: "boy",
    meaning: "A beam of pure sunlight, part of Lord Vishnu",
    meaningHi: "सूर्य की किरण, भगवान विष्णु का अंश",
    deity: "Lord Vishnu",
    deityHi: "भगवान विष्णु",
    nakshatra: "Swati",
    nakshatraHi: "स्वाति",
    rashi: "Libra",
    rashiHi: "तुला",
    startingLetter: "R",
    numerology: 3,
  },
  {
    name: "Navin",
    nameHi: "नवीन",
    gender: "boy",
    meaning: "Fresh, eternally new, ever-blossoming spirit",
    meaningHi: "नया, सुंदर, नित्य नूतन",
    nakshatra: "Anuradha",
    nakshatraHi: "अनुराधा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "N",
    numerology: 2,
  },
  {
    name: "Nikhil",
    nameHi: "निखिल",
    gender: "boy",
    meaning: "Complete, whole, all-encompassing, universal",
    meaningHi: "सम्पूर्ण, अखंड, सर्वव्यापी",
    nakshatra: "Anuradha",
    nakshatraHi: "अनुराधा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "N",
    numerology: 5,
  },
  {
    name: "Yash",
    nameHi: "यश",
    gender: "boy",
    meaning: "Glory, triumph, righteous fame and divine favor",
    meaningHi: "कीर्ति, प्रतिष्ठा, धर्मयुक्त विजय",
    nakshatra: "Jyeshtha",
    nakshatraHi: "ज्येष्ठा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "Y",
    numerology: 8,
  },
  {
    name: "Bhavya",
    nameHi: "भव्य",
    gender: "boy",
    meaning: "Grand, magnificent, splendid spiritual demeanor",
    meaningHi: "विशाल, सुंदर, तेजस्वी एवं कल्याणकारी",
    deity: "Lord Shiva",
    deityHi: "भगवान शिव",
    nakshatra: "Mula",
    nakshatraHi: "मूल",
    rashi: "Sagittarius",
    rashiHi: "धनु",
    startingLetter: "Bh",
    numerology: 6,
  },
  {
    name: "Dhruv",
    nameHi: "ध्रुव",
    gender: "boy",
    meaning: "The steadfast North Pole star, unshakeable devotee of Lord Vishnu",
    meaningHi: "अटल, स्थिर, भगवान विष्णु के परम भक्त ध्रुव",
    deity: "Bhakt Dhruv / Vishnu",
    deityHi: "भक्त ध्रुव / श्रीहरि",
    nakshatra: "Purva Ashadha",
    nakshatraHi: "पूर्वाषाढ़ा",
    rashi: "Sagittarius",
    rashiHi: "धनु",
    startingLetter: "Dh",
    numerology: 7,
  },
  {
    name: "Jayant",
    nameHi: "जयंत",
    gender: "boy",
    meaning: "Victorious, triumphant over inner senses",
    meaningHi: "विजयी, इंद्रियों पर विजय पाने वाला",
    deity: "Lord Indra / Shiva",
    deityHi: "इंद्र / शिव",
    nakshatra: "Uttara Ashadha",
    nakshatraHi: "उत्तराषाढ़ा",
    rashi: "Capricorn",
    rashiHi: "मकर",
    startingLetter: "J",
    numerology: 1,
  },
  {
    name: "Kshitij",
    nameHi: "क्षितिज",
    gender: "boy",
    meaning: "The sacred horizon where Earth meets the infinite Sky",
    meaningHi: "क्षितिज, जहाँ धरती और आकाश मिलते प्रतीत होते हैं",
    nakshatra: "Shravana",
    nakshatraHi: "श्रवण",
    rashi: "Capricorn",
    rashiHi: "मकर",
    startingLetter: "Kh",
    numerology: 4,
  },
  {
    name: "Gaurav",
    nameHi: "गौरव",
    gender: "boy",
    meaning: "Dignity, honor, respect, greatness of character",
    meaningHi: "सम्मान, प्रतिष्ठा, स्वाभिमान",
    nakshatra: "Dhanishta",
    nakshatraHi: "धनिष्ठा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "G",
    numerology: 3,
  },
  {
    name: "Samar",
    nameHi: "समर",
    gender: "boy",
    meaning: "Courageous warrior of righteousness, battle for truth",
    meaningHi: "धर्मयुद्ध का वीर, साहसी योद्धा",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "S",
    numerology: 9,
  },
  {
    name: "Siddharth",
    nameHi: "सिद्धार्थ",
    gender: "boy",
    meaning: "One who has achieved the supreme goal of enlightenment",
    meaningHi: "जिसका मनोरथ सिद्ध हो चुका हो, आत्मज्ञानी",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "S",
    numerology: 7,
  },
  {
    name: "Devansh",
    nameHi: "देवांश",
    gender: "boy",
    meaning: "A spark of the Divine, part of God",
    meaningHi: "ईश्वर का पवित्र अंश, दिव्य आत्मा",
    nakshatra: "Revati",
    nakshatraHi: "रेवती",
    rashi: "Pisces",
    rashiHi: "मीन",
    startingLetter: "D",
    numerology: 9,
  },
  {
    name: "Daksh",
    nameHi: "दक्ष",
    gender: "boy",
    meaning: "Capable, efficient, master of rituals",
    meaningHi: "कुशल, समर्थ, कर्मठ",
    deity: "Lord Shiva / Brahma",
    deityHi: "भगवान शिव / ब्रह्मा",
    nakshatra: "Revati",
    nakshatraHi: "रेवती",
    rashi: "Pisces",
    rashiHi: "मीन",
    startingLetter: "D",
    numerology: 2,
  },

  // --- GIRL NAMES ---
  {
    name: "Aadhya",
    nameHi: "आध्या",
    gender: "girl",
    meaning: "The Primordial Power, first and foremost (Maa Durga)",
    meaningHi: "प्रथम शक्ति, मूल प्रकृति (मां दुर्गा)",
    deity: "Maa Durga",
    deityHi: "मां दुर्गा",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 1,
  },
  {
    name: "Ananya",
    nameHi: "अनन्या",
    gender: "girl",
    meaning: "Matchless, unique, unwavering single-minded devotion",
    meaningHi: "अद्वितीय, जिसके समान कोई न हो, अनन्य भक्ति",
    deity: "Maa Lakshmi",
    deityHi: "मां लक्ष्मी",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 6,
  },
  {
    name: "Arya",
    nameHi: "आर्या",
    gender: "girl",
    meaning: "Noble, venerable, goddess of supreme virtue",
    meaningHi: "कुलीन, पूजनीया, मां पार्वती का नाम",
    deity: "Maa Parvati",
    deityHi: "मां पार्वती",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 9,
  },
  {
    name: "Avani",
    nameHi: "अवनी",
    gender: "girl",
    meaning: "Sacred Mother Earth, fertile and nurturing provider",
    meaningHi: "धरती माता, पोषण करने वाली वसुंधरा",
    deity: "Bhumi Devi",
    deityHi: "भू-देवी",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 8,
  },
  {
    name: "Charvi",
    nameHi: "चार्वी",
    gender: "girl",
    meaning: "A lovely maiden of exceptional grace and inner beauty",
    meaningHi: "अति सुंदर, सौम्य और मनमोहक कन्या",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "Ch",
    numerology: 5,
  },
  {
    name: "Chhaya",
    nameHi: "छाया",
    gender: "girl",
    meaning: "Cool protective shade, divine consort of Surya Deva",
    meaningHi: "शीतल छाया, सूर्य देव की पत्नी एवं शनि देव की माता",
    deity: "Chhaya Devi",
    deityHi: "छाया देवी",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "Ch",
    numerology: 7,
  },
  {
    name: "Lavanya",
    nameHi: "लावण्या",
    gender: "girl",
    meaning: "Radiant grace, divine elegance and spiritual charm",
    meaningHi: "सौंदर्य, लावण्य, मनोहारी कांति",
    deity: "Maa Lakshmi",
    deityHi: "मां लक्ष्मी",
    nakshatra: "Ashwini",
    nakshatraHi: "अश्विनी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "L",
    numerology: 3,
  },
  {
    name: "Leela",
    nameHi: "लीला",
    gender: "girl",
    meaning: "Divine cosmic play, God's transcendental pastime",
    meaningHi: "ईश्वर की दिव्य क्रीड़ा, आनंदमय लीला",
    deity: "Radha / Krishna",
    deityHi: "श्रीराधा / श्रीकृष्ण",
    nakshatra: "Bharani",
    nakshatraHi: "भरणी",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "L",
    numerology: 6,
  },
  {
    name: "Vanya",
    nameHi: "वान्या",
    gender: "girl",
    meaning: "Gracious gift of God, serene forest goddess",
    meaningHi: "ईश्वर का अनुपम उपहार, वन की देवी",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 4,
  },
  {
    name: "Vaidehi",
    nameHi: "वैदेही",
    gender: "girl",
    meaning: "Daughter of Videha King Janaka, Goddess Sita",
    meaningHi: "विदेहराज जनक की पुत्री, भगवती सीता जी",
    deity: "Maa Sita",
    deityHi: "मां सीता",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 1,
  },
  {
    name: "Vrishti",
    nameHi: "वृष्टि",
    gender: "girl",
    meaning: "Abundant life-giving rain, showers of divine blessings",
    meaningHi: "अमृत वर्षा, ईश्वरीय कृपा की फुहार",
    nakshatra: "Rohini",
    nakshatraHi: "रोहिणी",
    rashi: "Taurus",
    rashiHi: "वृषभ",
    startingLetter: "V",
    numerology: 8,
  },
  {
    name: "Kavya",
    nameHi: "काव्या",
    gender: "girl",
    meaning: "Sacred poetry, vision of wisdom, verses of the sages",
    meaningHi: "काव्य, रसमय ज्ञान, ऋषियों की वाणी",
    deity: "Maa Saraswati",
    deityHi: "मां सरस्वती",
    nakshatra: "Mrigashira",
    nakshatraHi: "मृगशिरा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 2,
  },
  {
    name: "Kashvi",
    nameHi: "काश्वी",
    gender: "girl",
    meaning: "Shining luminous star, glowing with inner virtue",
    meaningHi: "चमकती हुई, कांतिमान, तेजस्वी कन्या",
    nakshatra: "Mrigashira",
    nakshatraHi: "मृगशिरा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 7,
  },
  {
    name: "Kirtida",
    nameHi: "कीर्तिदा",
    gender: "girl",
    meaning: "Mother of Sri Radha Rani, giver of divine glory",
    meaningHi: "श्री राधा रानी की माता जी, कीर्ति प्रदायिनी",
    deity: "Maa Kirtida / Radha",
    deityHi: "माता कीर्तिदा / राधा",
    nakshatra: "Mrigashira",
    nakshatraHi: "मृगशिरा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 6,
  },
  {
    name: "Hansika",
    nameHi: "हंसिका",
    gender: "girl",
    meaning: "Swan maiden, purest soul residing near Maa Saraswati",
    meaningHi: "हंसिनी, मां सरस्वती की पवित्र संगिनी, निर्मल आत्मा",
    deity: "Maa Saraswati",
    deityHi: "मां सरस्वती",
    nakshatra: "Punarvasu",
    nakshatraHi: "पुनर्वसु",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "H",
    numerology: 1,
  },
  {
    name: "Himani",
    nameHi: "हिमानी",
    gender: "girl",
    meaning: "Daughter of the snowy Himalayas, Goddess Parvati",
    meaningHi: "हिमवान की पुत्री, मां पार्वती",
    deity: "Maa Parvati",
    deityHi: "मां पार्वती",
    nakshatra: "Punarvasu",
    nakshatraHi: "पुनर्वसु",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "H",
    numerology: 4,
  },
  {
    name: "Divya",
    nameHi: "दिव्या",
    gender: "girl",
    meaning: "Divine, heavenly light, celestial radiance",
    meaningHi: "अलौकिक, स्वर्गीय तेज, दिव्य कांति",
    nakshatra: "Ashlesha",
    nakshatraHi: "आश्लेषा",
    rashi: "Cancer",
    rashiHi: "कर्क",
    startingLetter: "D",
    numerology: 7,
  },
  {
    name: "Manvi",
    nameHi: "मानवी",
    gender: "girl",
    meaning: "Possessing humanity, compassionate woman with noble heart",
    meaningHi: "मानवता से पूर्ण, दयालु और सद्गुणी स्त्री",
    nakshatra: "Magha",
    nakshatraHi: "मघा",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "M",
    numerology: 9,
  },
  {
    name: "Mira",
    nameHi: "मीरा",
    gender: "girl",
    meaning: "Supreme devotee of Krishna, ocean of pure bhakti",
    meaningHi: "श्रीकृष्ण की अनन्य भक्त, भक्ति की सरिता",
    deity: "Mirabai / Krishna",
    deityHi: "मीराबाई / श्रीकृष्ण",
    nakshatra: "Magha",
    nakshatraHi: "मघा",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "M",
    numerology: 6,
  },
  {
    name: "Tanvi",
    nameHi: "तन्वी",
    gender: "girl",
    meaning: "Slender, delicate, beautiful Goddess Durga",
    meaningHi: "सुकुमार, रूपवती, मां दुर्गा का एक रूप",
    deity: "Maa Durga",
    deityHi: "मां दुर्गा",
    nakshatra: "Purva Phalguni",
    nakshatraHi: "पूर्वा फाल्गुनी",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "T",
    numerology: 2,
  },
  {
    name: "Pari",
    nameHi: "परी",
    gender: "girl",
    meaning: "Celestial being, angel of purity and joy",
    meaningHi: "परी, सौम्य और पावन आत्मा",
    nakshatra: "Uttara Phalguni",
    nakshatraHi: "उत्तरा फाल्गुनी",
    rashi: "Virgo",
    rashiHi: "कन्या",
    startingLetter: "P",
    numerology: 5,
  },
  {
    name: "Prisha",
    nameHi: "प्रिशा",
    gender: "girl",
    meaning: "Beloved, precious gift of God, blessed soul",
    meaningHi: "प्रिय, ईश्वर की दी हुई अमूल्य भेंट",
    nakshatra: "Hasta",
    nakshatraHi: "हस्त",
    rashi: "Virgo",
    rashiHi: "कन्या",
    startingLetter: "P",
    numerology: 3,
  },
  {
    name: "Pooja",
    nameHi: "पूजा",
    gender: "girl",
    meaning: "Sacred worship, offering of the heart to God",
    meaningHi: "ईश्वर की आराधना, प्रार्थना एवं वंदना",
    nakshatra: "Hasta",
    nakshatraHi: "हस्त",
    rashi: "Virgo",
    rashiHi: "कन्या",
    startingLetter: "P",
    numerology: 8,
  },
  {
    name: "Radhika",
    nameHi: "राधिका",
    gender: "girl",
    meaning: "Successful, queen of Vrindavan, supreme beloved of Krishna",
    meaningHi: "सफलता दायिनी, वृंदावन की महारानी श्री राधा",
    deity: "Maa Radha",
    deityHi: "श्री राधा रानी",
    nakshatra: "Chitra",
    nakshatraHi: "चित्रा",
    rashi: "Libra",
    rashiHi: "तुला",
    startingLetter: "R",
    numerology: 1,
  },
  {
    name: "Riya",
    nameHi: "रिया",
    gender: "girl",
    meaning: "Graceful singer, melodious devotional voice",
    meaningHi: "मधुर गायिका, सुरीली एवं सुसंस्कृत",
    deity: "Maa Saraswati",
    deityHi: "मां सरस्वती",
    nakshatra: "Chitra",
    nakshatraHi: "चित्रा",
    rashi: "Libra",
    rashiHi: "तुला",
    startingLetter: "R",
    numerology: 4,
  },
  {
    name: "Roshni",
    nameHi: "रोशनी",
    gender: "girl",
    meaning: "Luminous light that dispels all darkness",
    meaningHi: "प्रकाश, उजाला, ज्ञान का दीप",
    nakshatra: "Swati",
    nakshatraHi: "स्वाति",
    rashi: "Libra",
    rashiHi: "तुला",
    startingLetter: "R",
    numerology: 6,
  },
  {
    name: "Navya",
    nameHi: "नव्या",
    gender: "girl",
    meaning: "Worth praising, novel, fresh and inspiring",
    meaningHi: "प्रशंसनीय, नवीन, स्तुत्य",
    nakshatra: "Anuradha",
    nakshatraHi: "अनुराधा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "N",
    numerology: 5,
  },
  {
    name: "Nityasri",
    nameHi: "नित्यश्री",
    gender: "girl",
    meaning: "Eternal prosperity, Goddess Lakshmi's perpetual grace",
    meaningHi: "शाश्वत ऐश्वर्य, मां लक्ष्मी की नित्य कृपा",
    deity: "Maa Lakshmi",
    deityHi: "मां लक्ष्मी",
    nakshatra: "Anuradha",
    nakshatraHi: "अनुराधा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "N",
    numerology: 3,
  },
  {
    name: "Yamini",
    nameHi: "यामिनी",
    gender: "girl",
    meaning: "Peaceful starry night, serene contemplative silence",
    meaningHi: "तारों भरी शांत रात्रि, आत्मशांति",
    nakshatra: "Jyeshtha",
    nakshatraHi: "ज्येष्ठा",
    rashi: "Scorpio",
    rashiHi: "वृश्चिक",
    startingLetter: "Y",
    numerology: 7,
  },
  {
    name: "Bhavani",
    nameHi: "भवानी",
    gender: "girl",
    meaning: "Giver of existence, Goddess Parvati, mother of the universe",
    meaningHi: "संसार को उत्पन्न करने वाली मां पार्वती (जगदम्बा)",
    deity: "Maa Bhavani",
    deityHi: "मां भवानी",
    nakshatra: "Mula",
    nakshatraHi: "मूल",
    rashi: "Sagittarius",
    rashiHi: "धनु",
    startingLetter: "Bh",
    numerology: 8,
  },
  {
    name: "Dharini",
    nameHi: "धारिणी",
    gender: "girl",
    meaning: "The sustainer of all beings, gentle Mother Earth",
    meaningHi: "सकल सृष्टि को धारण करने वाली पृथ्वी माता",
    deity: "Bhumi Devi",
    deityHi: "भू-देवी",
    nakshatra: "Purva Ashadha",
    nakshatraHi: "पूर्वाषाढ़ा",
    rashi: "Sagittarius",
    rashiHi: "धनु",
    startingLetter: "Dh",
    numerology: 4,
  },
  {
    name: "Jhanvi",
    nameHi: "जाह्नवी",
    gender: "girl",
    meaning: "Daughter of sage Jahnu, the sacred river Ganga",
    meaningHi: "महर्षि जह्नु की पुत्री, पापनाशिनी मां गंगा",
    deity: "Maa Ganga",
    deityHi: "मां गंगा",
    nakshatra: "Uttara Ashadha",
    nakshatraHi: "उत्तराषाढ़ा",
    rashi: "Capricorn",
    rashiHi: "मकर",
    startingLetter: "J",
    numerology: 1,
  },
  {
    name: "Khushi",
    nameHi: "खुशी",
    gender: "girl",
    meaning: "Joy, bliss, radiant happiness in the household",
    meaningHi: "प्रसन्नता, आनंद, घर की रौनक",
    nakshatra: "Shravana",
    nakshatraHi: "श्रवण",
    rashi: "Capricorn",
    rashiHi: "मकर",
    startingLetter: "Kh",
    numerology: 9,
  },
  {
    name: "Gargi",
    nameHi: "गार्गी",
    gender: "girl",
    meaning: "Venerable ancient Vedic philosopher and scholar who questioned Sage Yajnavalkya",
    meaningHi: "वैदिक काल की विदुषी एवं ब्रह्मज्ञानी ब्रह्मवादिनी",
    nakshatra: "Dhanishta",
    nakshatraHi: "धनिष्ठा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "G",
    numerology: 2,
  },
  {
    name: "Saanvi",
    nameHi: "सान्वी",
    gender: "girl",
    meaning: "One who is surrendered to the Divine, Goddess Lakshmi",
    meaningHi: "मां लक्ष्मी, ईश्वर की शरण में रहने वाली",
    deity: "Maa Lakshmi",
    deityHi: "मां लक्ष्मी",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "S",
    numerology: 3,
  },
  {
    name: "Siya",
    nameHi: "सिया",
    gender: "girl",
    meaning: "White moonlight, Goddess Sita, embodiment of purity",
    meaningHi: "शुभ्र चांदनी, भगवती सीता जी, पवित्रता की मूर्ति",
    deity: "Maa Sita",
    deityHi: "मां सीता",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "S",
    numerology: 6,
  },
  {
    name: "Devika",
    nameHi: "देविका",
    gender: "girl",
    meaning: "Little goddess, sacred river descending from the Himalayas",
    meaningHi: "छोटी देवी, हिमालय से निकलने वाली पवित्र नदी",
    deity: "Maa Parvati",
    deityHi: "मां पार्वती",
    nakshatra: "Revati",
    nakshatraHi: "रेवती",
    rashi: "Pisces",
    rashiHi: "मीन",
    startingLetter: "D",
    numerology: 5,
  },
  {
    name: "Damini",
    nameHi: "दामिनी",
    gender: "girl",
    meaning: "Lightning in the monsoon sky, fiery brilliance",
    meaningHi: "आकाश की बिजली, प्रखर कांति",
    nakshatra: "Revati",
    nakshatraHi: "रेवती",
    rashi: "Pisces",
    rashiHi: "मीन",
    startingLetter: "D",
    numerology: 8,
  },

  // --- UNISEX / SPIRITUAL NAMES ---
  {
    name: "Anand",
    nameHi: "आनंद",
    gender: "unisex",
    meaning: "Supreme divine bliss, untainted spiritual joy",
    meaningHi: "परमानंद, आत्मिक सुख",
    nakshatra: "Krittika",
    nakshatraHi: "कृत्तिका",
    rashi: "Aries",
    rashiHi: "मेष",
    startingLetter: "A",
    numerology: 9,
  },
  {
    name: "Kripa",
    nameHi: "कृपा",
    gender: "unisex",
    meaning: "Divine grace, unconditioned compassion of God",
    meaningHi: "ईश्वरीय अनुग्रह, दया एवं करुणा",
    deity: "Lord Krishna / Shiva",
    deityHi: "श्रीकृष्ण / शिव",
    nakshatra: "Mrigashira",
    nakshatraHi: "मृगशिरा",
    rashi: "Gemini",
    rashiHi: "मिथुन",
    startingLetter: "K",
    numerology: 1,
  },
  {
    name: "Mukti",
    nameHi: "मुक्ति",
    gender: "unisex",
    meaning: "Spiritual liberation, freedom from the cycle of samsara",
    meaningHi: "मोक्ष, जन्म-मरण के चक्र से मुक्ति",
    nakshatra: "Magha",
    nakshatraHi: "मघा",
    rashi: "Leo",
    rashiHi: "सिंह",
    startingLetter: "M",
    numerology: 7,
  },
  {
    name: "Satya",
    nameHi: "सत्य",
    gender: "unisex",
    meaning: "Eternal absolute truth, the foundational pillar of Dharma",
    meaningHi: "शाश्वत सत्य, धर्म का मूल आधार",
    deity: "Lord Rama / Satyanarayan",
    deityHi: "श्रीराम / श्री सत्यनारायण",
    nakshatra: "Shatabhisha",
    nakshatraHi: "शतभिषा",
    rashi: "Aquarius",
    rashiHi: "कुंभ",
    startingLetter: "S",
    numerology: 1,
  },
];
