export type SuvicharCategory =
  | "all"
  | "jain"
  | "krishna"
  | "mahadev"
  | "hanuman"
  | "ram"
  | "devi"
  | "ganesh"
  | "sant"
  | "festivals"
  | "suprabhat";

export interface SuvicharItem {
  id: string;
  category: SuvicharCategory;
  tradition: "jain" | "hindu" | "universal";
  titleHi: string;
  titleEn: string;
  quoteHi: string;
  quoteEn?: string;
  shlokaOrSutra?: string;
  sourceHi: string;
  sourceEn: string;
  symbol: "ahimsa" | "om" | "trishul" | "lotus" | "flute" | "bow" | "gada" | "swastik" | "diya" | "sun";
  tag: string;
}

export interface CardTheme {
  id: string;
  nameHi: string;
  nameEn: string;
  bgType: "gradient" | "radial";
  bgColors: [string, string, string?];
  textColor: string;
  accentColor: string;
  shlokaColor: string;
  quoteBoxBg: string;
  badgeBg: string;
  badgeText: string;
  borderColor: string;
  glowColor: string;
  motif: string;
  categoryFit?: SuvicharCategory[];
}

export interface CardAspectRatio {
  id: "story" | "square" | "landscape";
  nameHi: string;
  nameEn: string;
  ratio: string;
  width: number;
  height: number;
  iconText: string;
}

export const ASPECT_RATIOS: CardAspectRatio[] = [
  {
    id: "story",
    nameHi: "व्हाट्सएप स्टेटस (9:16)",
    nameEn: "WhatsApp Status (9:16)",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    iconText: "📱",
  },
  {
    id: "square",
    nameHi: "इंस्टाग्राम पोस्ट (1:1)",
    nameEn: "Square Post (1:1)",
    ratio: "1:1",
    width: 1080,
    height: 1080,
    iconText: "⏹️",
  },
  {
    id: "landscape",
    nameHi: "बैनर / फेसबुक (16:9)",
    nameEn: "Banner / FB (16:9)",
    ratio: "16:9",
    width: 1920,
    height: 1080,
    iconText: "🖼️",
  },
];

export const SALUTATION_PRESETS = [
  { id: "jai-jinendra", textHi: "सप्रेम जय जिनेन्द्र", tradition: "jain" },
  { id: "michhami-dukkadam", textHi: "मिच्छामि दुक्कडं (क्षमा भाव)", tradition: "jain" },
  { id: "jai-shree-krishna", textHi: "जय श्री कृष्णा", tradition: "hindu" },
  { id: "radhe-radhe", textHi: "राधे राधे", tradition: "hindu" },
  { id: "har-har-mahadev", textHi: "हर हर महादेव ॐ", tradition: "hindu" },
  { id: "jai-shree-ram", textHi: "जय श्री राम 🚩", tradition: "hindu" },
  { id: "jai-bajrangbali", textHi: "जय बजरंगबली संकटमोचन", tradition: "hindu" },
  { id: "jai-mata-di", textHi: "जय माता दी 🌸", tradition: "hindu" },
  { id: "ganpati-bappa-morya", textHi: "गणपति बाप्पा मोरया 🪔", tradition: "hindu" },
  { id: "jai-shree-shyam", textHi: "हारे का सहारा बाबा श्याम", tradition: "hindu" },
  { id: "shubh-prabhat", textHi: "शुभ प्रभात — आपका दिन मंगलमय हो", tradition: "universal" },
  { id: "shubh-sandhya", textHi: "शुभ संध्या एवं शुभ रात्रि", tradition: "universal" },
  { id: "subhkamnaye", textHi: "हार्दिक शुभकामनाएं सहित", tradition: "universal" },
];

export const CARD_THEMES: CardTheme[] = [
  {
    id: "jain-swarna",
    nameHi: "जैन श्वेत-स्वर्ण (अहिंसा शांति)",
    nameEn: "Jain Pure Gold & White",
    bgType: "gradient",
    bgColors: ["#141E28", "#1E293B", "#0F172A"],
    textColor: "#F8FAFC",
    accentColor: "#F59E0B",
    shlokaColor: "#FDE68A",
    quoteBoxBg: "rgba(255, 255, 255, 0.07)",
    badgeBg: "rgba(245, 158, 11, 0.2)",
    badgeText: "#FCD34D",
    borderColor: "rgba(245, 158, 11, 0.45)",
    glowColor: "rgba(245, 158, 11, 0.25)",
    motif: "✋ 卐",
    categoryFit: ["jain", "suprabhat"],
  },
  {
    id: "vrindavan-sunset",
    nameHi: "वृंदावन संध्या (कृष्ण कृपा)",
    nameEn: "Vrindavan Sunset Glow",
    bgType: "gradient",
    bgColors: ["#2E1065", "#4C1D95", "#831843"],
    textColor: "#FFFBEB",
    accentColor: "#FBBF24",
    shlokaColor: "#FEF08A",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(251, 191, 36, 0.22)",
    badgeText: "#FDE68A",
    borderColor: "rgba(251, 191, 36, 0.5)",
    glowColor: "rgba(217, 119, 6, 0.35)",
    motif: "🦚 🪈",
    categoryFit: ["krishna", "suprabhat"],
  },
  {
    id: "kailash-mahadev",
    nameHi: "कैलाश नीलकंठ (शिव महिमा)",
    nameEn: "Kailash Cosmic Neelkanth",
    bgType: "gradient",
    bgColors: ["#082F49", "#0F172A", "#1E1B4B"],
    textColor: "#F0F9FF",
    accentColor: "#38BDF8",
    shlokaColor: "#BAE6FD",
    quoteBoxBg: "rgba(56, 189, 248, 0.08)",
    badgeBg: "rgba(56, 189, 248, 0.2)",
    badgeText: "#E0F2FE",
    borderColor: "rgba(56, 189, 248, 0.45)",
    glowColor: "rgba(14, 165, 233, 0.3)",
    motif: "🔱 🕉️",
    categoryFit: ["mahadev"],
  },
  {
    id: "ayodhya-saffron",
    nameHi: "अयोध्या भगवा (राम-हनुमान तेज)",
    nameEn: "Ayodhya Divine Saffron",
    bgType: "gradient",
    bgColors: ["#451A03", "#7C2D12", "#9A3412"],
    textColor: "#FFF7ED",
    accentColor: "#F97316",
    shlokaColor: "#FED7AA",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(249, 115, 22, 0.25)",
    badgeText: "#FFEDD5",
    borderColor: "rgba(251, 146, 60, 0.55)",
    glowColor: "rgba(234, 88, 12, 0.35)",
    motif: "🚩 🏹",
    categoryFit: ["ram", "hanuman", "festivals"],
  },
  {
    id: "devi-sindoor",
    nameHi: "माँ शक्ति सिंदूर (दुर्गा-लक्ष्मी)",
    nameEn: "Devi Crimson Radiance",
    bgType: "gradient",
    bgColors: ["#500724", "#831843", "#9F1239"],
    textColor: "#FFF1F2",
    accentColor: "#F43F5E",
    shlokaColor: "#FECDD3",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(244, 63, 94, 0.22)",
    badgeText: "#FFE4E6",
    borderColor: "rgba(251, 113, 133, 0.5)",
    glowColor: "rgba(225, 29, 72, 0.35)",
    motif: "🌺 🪔",
    categoryFit: ["devi", "festivals"],
  },
  {
    id: "royal-swarna-temple",
    nameHi: "स्वर्ण मंदिर प्रभात (दिव्य आभा)",
    nameEn: "Golden Temple Radiance",
    bgType: "gradient",
    bgColors: ["#292524", "#44403C", "#1C1917"],
    textColor: "#FAFAF9",
    accentColor: "#EAB308",
    shlokaColor: "#FEF08A",
    quoteBoxBg: "rgba(234, 179, 8, 0.09)",
    badgeBg: "rgba(234, 179, 8, 0.22)",
    badgeText: "#FEF9C3",
    borderColor: "rgba(234, 179, 8, 0.55)",
    glowColor: "rgba(202, 138, 4, 0.35)",
    motif: "🪔 🌟",
    categoryFit: ["suprabhat", "sant", "ganesh"],
  },
  {
    id: "vedic-marigold",
    nameHi: "वैदिक गेंदा एवं पीताम्बर",
    nameEn: "Vedic Marigold & Pitamber",
    bgType: "gradient",
    bgColors: ["#3F2E05", "#713F12", "#854D0E"],
    textColor: "#FEFCE8",
    accentColor: "#FACC15",
    shlokaColor: "#FEF9C3",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(250, 204, 21, 0.22)",
    badgeText: "#FEF08A",
    borderColor: "rgba(250, 204, 21, 0.5)",
    glowColor: "rgba(234, 179, 8, 0.35)",
    motif: "🌼 🪔",
    categoryFit: ["ganesh", "festivals", "suprabhat"],
  },
  {
    id: "brahma-muhurat",
    nameHi: "शांत ब्रह्म मुहूर्त (गहन ध्यान)",
    nameEn: "Brahma Muhurat Starlight",
    bgType: "gradient",
    bgColors: ["#090A0F", "#111827", "#1E1B4B"],
    textColor: "#F9FAFB",
    accentColor: "#A78BFA",
    shlokaColor: "#DDD6FE",
    quoteBoxBg: "rgba(167, 139, 250, 0.08)",
    badgeBg: "rgba(167, 139, 250, 0.2)",
    badgeText: "#EDE9FE",
    borderColor: "rgba(167, 139, 250, 0.45)",
    glowColor: "rgba(139, 92, 246, 0.3)",
    motif: "✨ 🌌",
    categoryFit: ["sant", "suprabhat"],
  },
];

export const SUVICHAR_DATABASE: SuvicharItem[] = [
  // ================= JAIN DHARMA & BHAGWAN MAHAVIRA =================
  {
    id: "jain-1",
    category: "jain",
    tradition: "jain",
    titleHi: "अहिंसा परमो धर्मः",
    titleEn: "Non-Violence is Supreme Virtue",
    shlokaOrSutra: "अहिंसा परमो धर्मः, धर्म हिंसा तथैव च।",
    quoteHi: "संसार के सभी जीवों के प्रति करुणा और मैत्री भाव रखो। किसी भी जीव को दुःख मत पहुंचाओ, क्योंकि सभी को अपना जीवन प्रिय है।",
    quoteEn: "Have compassion and friendship towards all living beings. Injure no one, for all life is sacred.",
    sourceHi: "भगवान महावीर (आचारांग सूत्र)",
    sourceEn: "Bhagwan Mahavira (Acharanga Sutra)",
    symbol: "ahimsa",
    tag: "जैन धर्म",
  },
  {
    id: "jain-2",
    category: "jain",
    tradition: "jain",
    titleHi: "जियो और जीने दो",
    titleEn: "Live and Let Live",
    shlokaOrSutra: "परस्परोपग्रहो जीवानाम्।",
    quoteHi: "स्वयं शांति से जियो और दूसरों को भी शांति व स्वतंत्रता से जीने दो। प्राणी मात्र के प्रति मन में प्रेम ही सच्चा धर्म है।",
    quoteEn: "Live peacefully and let all others live with peace and freedom. Love for all beings is true dharma.",
    sourceHi: "भगवान महावीर संदेश",
    sourceEn: "Bhagwan Mahavira Teaching",
    symbol: "ahimsa",
    tag: "महावीर वाणी",
  },
  {
    id: "jain-3",
    category: "jain",
    tradition: "jain",
    titleHi: "नवकार महामंत्र",
    titleEn: "Navkar Mahamantra",
    shlokaOrSutra: "णमो अरिहंताणं, णमो सिद्धाणं, णमो आयरियाणं। णमो उवज्झायाणं, णमो लोए सव्व साहूणं॥",
    quoteHi: "यह पंच परमेष्ठी को किया गया पावन नमन सभी पापों का नाश करने वाला और सम्पूर्ण जगत में परम कल्याणकारी है।",
    quoteEn: "Salutations to the Arihantas, Siddhas, Acharyas, Upadhyayas, and all Sadhus. May this mantra bless your soul with eternal peace.",
    sourceHi: "श्री नवकार महामंत्र",
    sourceEn: "Shri Navkar Mahamantra",
    symbol: "swastik",
    tag: "नवकार मंत्र",
  },
  {
    id: "jain-4",
    category: "jain",
    tradition: "jain",
    titleHi: "क्रोध पर विजय",
    titleEn: "Conquering Anger",
    shlokaOrSutra: "अक्कोधेन जिणे कोधं, असाधुं साहुणा जिणे।",
    quoteHi: "क्रोध को शांत भाव से जीतो, दुष्टता को सज्जनता से जीतो, लोभ को दान से जीतो और असत्य को सत्य से जीतो।",
    quoteEn: "Conquer anger with forgiveness, wickedness with goodness, greed with charity, and falsehood with truth.",
    sourceHi: "भगवान महावीर (उत्तराध्ययन सूत्र)",
    sourceEn: "Bhagwan Mahavira (Uttaradhyayana Sutra)",
    symbol: "lotus",
    tag: "सदाचार",
  },
  {
    id: "jain-5",
    category: "jain",
    tradition: "jain",
    titleHi: "क्षमावणी — मिच्छामि दुक्कडं",
    titleEn: "Universal Forgiveness (Michhami Dukkadam)",
    shlokaOrSutra: "खामेमि सव्व जीवे, सव्वे जीवा खमंतु मे। मित्ती मे सव्व भूएसु, वेरं मज्झं न केणइ॥",
    quoteHi: "मैं संसार के सभी जीवों से क्षमा याचना करता हूँ, सभी जीव मुझे क्षमा करें। मेरी सबके साथ मित्रता है, किसी से कोई वैर नहीं।",
    quoteEn: "I ask forgiveness from all living beings; may all beings forgive me. I have friendship with everyone, and enmity with none.",
    sourceHi: "जैन क्षमावणी सूत्र",
    sourceEn: "Jain Forgiveness Sutra",
    symbol: "ahimsa",
    tag: "पर्युषण व क्षमावाणी",
  },
  {
    id: "jain-6",
    category: "jain",
    tradition: "jain",
    titleHi: "कर्म और आत्म-कल्याण",
    titleEn: "Karma & The Soul",
    shlokaOrSutra: "अप्पा कत्ता विकत्ता य, दुहाण य सुहाण य।",
    quoteHi: "अपनी आत्मा ही अपने सुख और दुःख का कर्ता और भोक्ता है। शुभ विचारों और कर्मों से ही जीवन में मोक्ष व आनंद संभव है।",
    quoteEn: "The soul itself is the maker and unmaker of its happiness and sorrow. Pure thoughts and noble actions illuminate the soul.",
    sourceHi: "श्री उत्तराध्ययन सूत्र",
    sourceEn: "Uttaradhyayana Sutra",
    symbol: "diya",
    tag: "कर्म सिद्धांत",
  },
  {
    id: "jain-7",
    category: "jain",
    tradition: "jain",
    titleHi: "चत्तारि मंगलं",
    titleEn: "Fourfold Auspicious Refuge",
    shlokaOrSutra: "चत्तारि मंगलं: अरिहंता मंगलं, सिद्धा मंगलं, साहू मंगलं, केवलिपन्नत्तो धम्मो मंगलं।",
    quoteHi: "अरिहंत मंगल हैं, सिद्ध मंगल हैं, साधु मंगल हैं और केवलि भगवान द्वारा प्ररूपित दयामयी धर्म ही परम मंगलकारी है।",
    quoteEn: "Auspicious are the Arihants, Siddhas, Sadhus, and the compassionate Dharma taught by the Omniscient.",
    sourceHi: "जैन मंगल पाठ",
    sourceEn: "Jain Mangal Path",
    symbol: "swastik",
    tag: "मंगल पाठ",
  },

  // ================= SHRI KRISHNA & BHAGAVAD GITA =================
  {
    id: "krishna-1",
    category: "krishna",
    tradition: "hindu",
    titleHi: "कर्मयोग — फल की चिंता मत करो",
    titleEn: "Karmayoga — Focus on Action",
    shlokaOrSutra: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥",
    quoteHi: "तुम्हारा अधिकार केवल कर्म करने पर है, उसके फलों पर कभी नहीं। फल की इच्छा से कर्म मत करो और न ही कर्म त्यागने में आसक्त होओ।",
    quoteEn: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Act with devotion.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 2, श्लोक 47)",
    sourceEn: "Bhagavad Gita (2.47)",
    symbol: "flute",
    tag: "गीता ज्ञान",
  },
  {
    id: "krishna-2",
    category: "krishna",
    tradition: "hindu",
    titleHi: "धर्म की रक्षा और ईश्वर कृपा",
    titleEn: "Divine Protection",
    shlokaOrSutra: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥",
    quoteHi: "जब-जब धर्म की हानि और अधर्म की वृद्धि होती है, तब-तब मैं सज्जनों की रक्षा और धर्म की पुनर्स्थापना हेतु अवतरित होता हूँ।",
    quoteEn: "Whenever there is a decline in righteousness, I manifest Myself for the protection of the good and re-establishment of Dharma.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 4, श्लोक 7)",
    sourceEn: "Bhagavad Gita (4.7)",
    symbol: "flute",
    tag: "श्री कृष्ण वाणी",
  },
  {
    id: "krishna-3",
    category: "krishna",
    tradition: "hindu",
    titleHi: "मन पर नियंत्रण",
    titleEn: "Mastery of the Mind",
    shlokaOrSutra: "असंशयं महाबाहो मनो दुर्निग्रहं चलम्। अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते॥",
    quoteHi: "मन चंचल और कठिनता से वश में होने वाला अवश्य है, परन्तु निरंतर अभ्यास और वैराग्य से इसे पूर्णतः शांत किया जा सकता है।",
    quoteEn: "The mind is restless and hard to control, but by regular practice and detachment, it can certainly be mastered.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 6, श्लोक 35)",
    sourceEn: "Bhagavad Gita (6.35)",
    symbol: "flute",
    tag: "मन की शांति",
  },
  {
    id: "krishna-4",
    category: "krishna",
    tradition: "hindu",
    titleHi: "सर्वसमर्पण और निर्भयता",
    titleEn: "Total Surrender & Peace",
    shlokaOrSutra: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज। अहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥",
    quoteHi: "सब चिंताओं और संशयों को छोड़कर केवल मेरी शरण में आ जाओ। मैं तुम्हें समस्त दुःखों व भयों से मुक्त कर दूंगा, शोक मत करो।",
    quoteEn: "Surrender all your worries unto Me alone. I will liberate you from all fears and anxieties; do not grieve.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 18, श्लोक 66)",
    sourceEn: "Bhagavad Gita (18.66)",
    symbol: "flute",
    tag: "शरणागति",
  },
  {
    id: "krishna-5",
    category: "krishna",
    tradition: "hindu",
    titleHi: "राधे राधे की महिमा",
    titleEn: "Glory of Shri Radha Krishna",
    shlokaOrSutra: "श्री राधा मेरी स्वामिनी, मैं राधे को दास। जनम जनम मोहि दीजियो, श्री वृन्दावन वास॥",
    quoteHi: "जिसके हृदय में श्री राधा-कृष्ण का नाम बसता है, उसके जीवन की सभी चिंताएं और कष्ट स्वतः दूर हो जाते हैं।",
    quoteEn: "Whosoever holds the sacred name of Radha-Krishna in the heart finds eternal peace and divine grace.",
    sourceHi: "ब्रज भक्ति रस",
    sourceEn: "Braj Devotional Wisdom",
    symbol: "lotus",
    tag: "राधा कृष्ण",
  },

  // ================= MAHADEV & SHIV BHAKTI =================
  {
    id: "mahadev-1",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "महामृत्युंजय संजीवनी मंत्र",
    titleEn: "Mahamrityunjaya Mantra",
    shlokaOrSutra: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय मामृतात्॥",
    quoteHi: "हम त्रिनेत्रधारी भगवान शिव की आराधना करते हैं, जो समस्त संसार को जीवन शक्ति देते हैं। वे हमें मृत्यु के भय से मुक्त कर अमरता प्रदान करें।",
    quoteEn: "We worship the Three-Eyed Lord Shiva, the fragrant nourisher of life. May He liberate us from bondage and fear of death.",
    sourceHi: "ऋग्वेद एवं यजुर्वेद",
    sourceEn: "Rigveda & Yajurveda",
    symbol: "trishul",
    tag: "शिव महामंत्र",
  },
  {
    id: "mahadev-2",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "शिव पंचाक्षर स्त्रोत",
    titleEn: "Shiv Panchakshara Stotra",
    shlokaOrSutra: "नागेन्द्रहाराय त्रिलोचनाय भस्माङ्गरागाय महेश्वराय। नित्याय शुद्धाय दिगम्बराय तस्मै नकाराय नमः शिवाय॥",
    quoteHi: "जो नागराज को हार रूप में धारण करते हैं, तीनों लोकों के स्वामी हैं, उन परम पवित्र देवाधिदेव महादेव को सादर प्रणाम।",
    quoteEn: "Salutations to the pure, eternal Lord of lords Shiva, who wears the serpent garland and holds cosmic grace.",
    sourceHi: "आदि शंकराचार्य विरचित",
    sourceEn: "Adi Shankaracharya",
    symbol: "om",
    tag: "शिव स्तुति",
  },
  {
    id: "mahadev-3",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "महाकाल कृपा और निर्भयता",
    titleEn: "Fearlessness in Mahakaal's Grace",
    shlokaOrSutra: "अकाल मृत्यु वो मरे जो काम करे चांडाल का। काल भी उसका क्या बिगाड़े जो भक्त हो महाकाल का॥",
    quoteHi: "सच्चे मन से जो महादेव का ध्यान करता है, संकट और काल भी उसका कुछ नहीं बिगाड़ सकते। हर परिस्थिति में शांत रहें।",
    quoteEn: "Those sheltered under Mahakaal's grace fear nothing in the cosmos. True surrender brings boundless strength.",
    sourceHi: "शिव महिमा",
    sourceEn: "Shiva Mahima",
    symbol: "trishul",
    tag: "महाकाल",
  },
  {
    id: "mahadev-4",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "विषपान और सहनशीलता",
    titleEn: "Patience and Compassion",
    shlokaOrSutra: "कर्पूरगौरं करुणावतारं संसारसारम् भुजगेन्द्रहारम्। सदावसन्तं हृदयारविन्दे भवं भवानीसहितं नमामि॥",
    quoteHi: "जो विष पीकर भी शांत और कल्याणकारी रहे, वही महादेव हैं। जीवन की कड़वाहट को भी धैर्य और प्रेम से जीतना ही शिवत्व है।",
    quoteEn: "To absorb life's negativity calmly and radiate love and welfare for all is the true essence of Shiva consciousness.",
    sourceHi: "भवानी स्तुति",
    sourceEn: "Bhavani Stuti",
    symbol: "lotus",
    tag: "सहनशीलता",
  },

  // ================= HANUMAN JI & SANKATMOCHAN =================
  {
    id: "hanuman-1",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "संकट कटै मिटै सब पीरा",
    titleEn: "Removal of All Afflictions",
    shlokaOrSutra: "संकट कटै मिटै सब पीरा। जो सुमिरै हनुमत बलबीरा॥",
    quoteHi: "जो भी वीर हनुमान जी का निरंतर स्मरण व ध्यान करता है, उसके जीवन के सभी संकट, भय और पीड़ाएं तत्काल मिट जाती हैं।",
    quoteEn: "All troubles vanish and all sorrows are eradicated for one who meditates upon the mighty and compassionate Hanuman.",
    sourceHi: "श्री हनुमान चालीसा (गोस्वामी तुलसीदास)",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "हनुमान चालीसा",
  },
  {
    id: "hanuman-2",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "सब सुख लहै तुम्हारी सरना",
    titleEn: "All Happiness in Thy Refuge",
    shlokaOrSutra: "सब सुख लहै तुम्हारी सरना। तुम रक्षक काहू को डर ना॥",
    quoteHi: "पवनपुत्र हनुमान जी की शरण में आने पर संसार के सभी सुख और निर्भयता प्राप्त होती है। जब वे हमारे रक्षक हैं, तो किसका भय?",
    quoteEn: "In your shelter, all joy is attained. When you are our protector, whom shall we fear?",
    sourceHi: "श्री हनुमान चालीसा",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "निर्भयता",
  },
  {
    id: "hanuman-3",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "मनोजवं मारुततुल्यवेगम्",
    titleEn: "Hanuman Vandana",
    shlokaOrSutra: "मनोजवं मारुततुल्यवेगं जितेन्द्रियं बुद्धिमतां वरिष्ठम्। वातात्मजं वानरयूथमुख्यं श्रीरामदूतं शरणं प्रपद्ये॥",
    quoteHi: "मन और वायु के समान तीव्र गति वाले, जितेंद्रिय, बुद्धिमानों में श्रेष्ठ, श्री रामदूत हनुमान जी के चरणों में हम नमन करते हैं।",
    quoteEn: "Swift as the mind, faster than the wind, master of the senses and wisest of the wise — I bow to Shri Rama's messenger Hanuman.",
    sourceHi: "श्री हनुमान वंदना",
    sourceEn: "Hanuman Vandana",
    symbol: "lotus",
    tag: "हनुमान वंदना",
  },

  // ================= SHRI RAM & RAMAYANA =================
  {
    id: "ram-1",
    category: "ram",
    tradition: "hindu",
    titleHi: "रघुकुल रीति — मर्यादा और वचन",
    titleEn: "Righteousness & Integrity",
    shlokaOrSutra: "रघुकुल रीति सदा चलि आई। प्राण जाहुं बरु बचनु न जाई॥",
    quoteHi: "सत्य, मर्यादा और कर्तव्य पालन ही जीवन का सबसे बड़ा आदर्श है। अपने वचनों और मूल्यों पर अटल रहना ही सच्ची मर्यादा है।",
    quoteEn: "Righteousness, honor, and truthfulness stand above all else. Holding onto virtue brings eternal glory.",
    sourceHi: "श्रीरामचरितमानस (बालकाण्ड)",
    sourceEn: "Ramcharitmanas",
    symbol: "bow",
    tag: "मर्यादा पुरुषोत्तम",
  },
  {
    id: "ram-2",
    category: "ram",
    tradition: "hindu",
    titleHi: "निर्मल मन की भक्ति",
    titleEn: "Purity of Heart",
    shlokaOrSutra: "निर्मल मन जन सो मोहि पावा। मोहि कपट छल छिद्र न भावा॥",
    quoteHi: "भगवान श्री राम कहते हैं: जिसका मन निर्मल और पवित्र है, वही मुझे प्राप्त कर सकता है। मुझे छल-कपट और अहंकार तनिक भी प्रिय नहीं।",
    quoteEn: "Lord Rama says: Only one with a pure, honest heart attains Me. Guile, arrogance, and deceit find no favor with the Divine.",
    sourceHi: "श्रीरामचरितमानस (सुन्दरकाण्ड)",
    sourceEn: "Ramcharitmanas (Sundarkand)",
    symbol: "bow",
    tag: "निर्मल भक्ति",
  },
  {
    id: "ram-3",
    category: "ram",
    tradition: "hindu",
    titleHi: "मंगल भवन अमंगल हारी",
    titleEn: "Auspicious Benediction",
    shlokaOrSutra: "मंगल भवन अमंगल हारी। द्रवहु सुदसरथ अजिर बिहारी॥",
    quoteHi: "जो समस्त मंगलों के धाम हैं और सभी अमंगलों व कष्टों को हरने वाले हैं, वे प्रभु श्री राम हमारे जीवन को सुखमय बनाएं।",
    quoteEn: "May Lord Rama, the fountainhead of all auspiciousness and destroyer of misfortune, bless your home with peace and joy.",
    sourceHi: "श्रीरामचरितमानस",
    sourceEn: "Ramcharitmanas",
    symbol: "sun",
    tag: "मंगल कामना",
  },

  // ================= MAA DURGA, LAKSHMI & SHAKTI =================
  {
    id: "devi-1",
    category: "devi",
    tradition: "hindu",
    titleHi: "सर्वमंगल मांगल्ये",
    titleEn: "Supreme Auspicious Mother",
    shlokaOrSutra: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥",
    quoteHi: "जो सब मंगलों में परम मंगलमयी, कल्याणकारी और सभी मनोकामनाओं को सिद्ध करने वाली हैं, उन माँ जगदम्बा को कोटि-कोटि नमन।",
    quoteEn: "Salutations to the most auspicious Mother, the fulfiller of all pure desires and protector of all who seek Her shelter.",
    sourceHi: "श्री दुर्गा सप्तशती",
    sourceEn: "Durga Saptashati",
    symbol: "lotus",
    tag: "दुर्गा स्तुति",
  },
  {
    id: "devi-2",
    category: "devi",
    tradition: "hindu",
    titleHi: "या देवी सर्वभूतेषु",
    titleEn: "The Divine Energy in All",
    shlokaOrSutra: "या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता। नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥",
    quoteHi: "जो देवी सभी प्राणियों में शक्ति, शांति, चेतना और मातृरूप में विद्यमान हैं, उन सर्वव्यापी माँ भगवती को बारंबार प्रणाम।",
    quoteEn: "To the Divine Mother who abides in all living beings in the form of inner strength, peace, and love — we bow again and again.",
    sourceHi: "श्री चण्डी पाठ",
    sourceEn: "Chandi Path",
    symbol: "lotus",
    tag: "शक्ति उपासना",
  },
  {
    id: "devi-3",
    category: "devi",
    tradition: "hindu",
    titleHi: "माँ महालक्ष्मी कृपा",
    titleEn: "Goddess Lakshmi Blessings",
    shlokaOrSutra: "नमस्तेऽस्तु महामाये श्रीपीठे सुरपूजिते। शङ्खचक्रगदाहस्ते महालक्ष्मि नमोऽस्तु ते॥",
    quoteHi: "माँ लक्ष्मी आपके घर-आंगन में सुख, शांति, समृद्धि और सद्बुद्धि का वास करें। परिश्रम और ईमानदारी ही लक्ष्मी का सच्चा निवास है।",
    quoteEn: "May Goddess Lakshmi bless your life with boundless joy, prosperity, purity, and virtuous wisdom.",
    sourceHi: "महालक्ष्मी अष्टकम",
    sourceEn: "Mahalakshmi Ashtakam",
    symbol: "lotus",
    tag: "महालक्ष्मी",
  },

  // ================= GANPATI BAPPA =================
  {
    id: "ganesh-1",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "वक्रतुण्ड महाकाय — विघ्नहर्ता",
    titleEn: "Remover of All Obstacles",
    shlokaOrSutra: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
    quoteHi: "करोड़ों सूर्यों के समान दिव्य तेज वाले विघ्नहर्ता श्री गणेश आपके जीवन के सभी विघ्नों को दूर कर हर कार्य में सफलता प्रदान करें।",
    quoteEn: "May Lord Ganesha, radiating with the brilliance of a million suns, remove all hurdles and bless your endeavors with grand success.",
    sourceHi: "श्री गणेश स्तुति",
    sourceEn: "Ganesh Stuti",
    symbol: "swastik",
    tag: "प्रथम पूज्य गणेश",
  },
  {
    id: "ganesh-2",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "शुभ लाभ और रिद्धि-सिद्धि",
    titleEn: "Auspicious Prosperity & Wisdom",
    shlokaOrSutra: "गजाननं भूतगणादिसेवितं कपित्थजम्बूफलचारुभक्षणम्। उमासुतं शोकविनाशकारकं नमामि विघ्नेश्वरपादपङ्कजम्॥",
    quoteHi: "भगवान गजानन आपके परिवार में सद्बुद्धि, आरोग्यता और सकारात्मक ऊर्जा का संचार करें। हर दिन शुभ और फलदायी हो।",
    quoteEn: "May Lord Ganesha bestow good health, intellect, harmony, and joy upon you and your loved ones.",
    sourceHi: "गणेश वंदना",
    sourceEn: "Ganesh Vandana",
    symbol: "diya",
    tag: "शुभ लाभ",
  },

  // ================= SANT VANI, KABIR & GURU NANAK =================
  {
    id: "sant-1",
    category: "sant",
    tradition: "universal",
    titleHi: "संत कबीर — आत्म-निरीक्षण",
    titleEn: "Sant Kabir — Self Reflection",
    shlokaOrSutra: "बुरा जो देखन मैं चला, बुरा न मिलिया कोय। जो दिल खोजा आपना, मुझसे बुरा न कोय॥",
    quoteHi: "दूसरों में दोष ढूंढने के बजाय जब हम अपने अंतर्मन में झांकते हैं, तब समझ आता है कि वास्तविक सुधार स्वयं से ही शुरू होता है।",
    quoteEn: "When I searched for faults in others, I found none. When I looked inside my own heart, I realized true change starts within.",
    sourceHi: "संत कबीर साखी",
    sourceEn: "Sant Kabir Sakhi",
    symbol: "diya",
    tag: "कबीर वाणी",
  },
  {
    id: "sant-2",
    category: "sant",
    tradition: "universal",
    titleHi: "मधुर वाणी का प्रभाव",
    titleEn: "Power of Gentle Speech",
    shlokaOrSutra: "ऐसी बानी बोलिए, मन का आपा खोय। औरन को सीतल करै, आपहु सीतल होय॥",
    quoteHi: "हमेशा ऐसी विनम्र और प्रेमपूर्ण वाणी बोलें जो दूसरों के मन को भी शांति दे और हमारे स्वयं के हृदय को भी आनंदित करे।",
    quoteEn: "Speak gentle and kind words without ego. It cools and comforts the listener, and brings peace to your own soul.",
    sourceHi: "संत कबीर दोहा",
    sourceEn: "Sant Kabir",
    symbol: "lotus",
    tag: "मधुर वाणी",
  },
  {
    id: "sant-3",
    category: "sant",
    tradition: "universal",
    titleHi: "तुलसी मीठे बचन",
    titleEn: "Goswami Tulsidas",
    shlokaOrSutra: "तुलसी मीठे बचन ते सुख उपजत चहुं ओर। बसीकरन इक मंत्र है परिहरू बचन कठोर॥",
    quoteHi: "मीठे और आदरयुक्त वचनों से चारों तरफ सुख और सौहार्द फैलता है। यही लोगों के दिलों को जीतने का सबसे शक्तिशाली साधन है।",
    quoteEn: "Sweet and polite words generate happiness everywhere. They are the greatest key to win hearts and dispel bitterness.",
    sourceHi: "गोस्वामी तुलसीदास",
    sourceEn: "Goswami Tulsidas",
    symbol: "sun",
    tag: "तुलसी वाणी",
  },
  {
    id: "sant-4",
    category: "sant",
    tradition: "universal",
    titleHi: "गुरु नानक देव — एक ओंकार",
    titleEn: "Guru Nanak — Truth & Compassion",
    shlokaOrSutra: "ੴ सतिनामु करता पुरखु निरभउ निरवैरु अकाल मूरति अजूनी सैभं गुर प्रसादि॥",
    quoteHi: "ईश्वर एक है, सत्य ही उसका नाम है। जो बिना किसी भय और वैर के सभी से प्रेम करता है, वही प्रभु की कृपा का पात्र बनता है।",
    quoteEn: "God is One, Truth is His Name. Live without fear and without malice, and radiate goodwill to all creation.",
    sourceHi: "श्री गुरु नानक देव जी (जपजी साहिब)",
    sourceEn: "Guru Nanak Dev (Japji Sahib)",
    symbol: "om",
    tag: "गुरु संदेश",
  },

  // ================= DAILY SUPRABHAT & POSITIVE MORNING =================
  {
    id: "suprabhat-1",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "शुभ प्रभात — नया सवेरा, नई आशा",
    titleEn: "Auspicious Morning & Fresh Hope",
    shlokaOrSutra: "कराग्रे वसते लक्ष्मीः करमध्ये सरस्वती। करमूले तु गोविन्दः प्रभाते करदर्शनम्॥",
    quoteHi: "सुबह उठकर अपनी हथेलियों का दर्शन कर ईश्वर को नमन करें। हर नया दिन परमात्मा का अनमोल उपहार है, इसे सकारात्मकता से जिएं।",
    quoteEn: "Every sunrise brings new opportunities to do good, spread kindness, and walk on the path of truth. Have a blessed morning!",
    sourceHi: "वैदिक प्रभात श्लोक",
    sourceEn: "Vedic Morning Verse",
    symbol: "sun",
    tag: "शुभ प्रभात",
  },
  {
    id: "suprabhat-2",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "सूर्य देव वंदना — ऊर्जा और आरोग्य",
    titleEn: "Surya Vandana — Vital Energy",
    shlokaOrSutra: "ॐ सूर्याय नमः। ॐ आदित्याय नमः। ॐ भास्कराय नमः॥",
    quoteHi: "भगवान सूर्य देव आपके जीवन में तेज, स्वास्थ्य, ज्ञान और अपार सकारात्मक ऊर्जा का प्रकाश फैलाएं। आपका दिन मंगलमय हो।",
    quoteEn: "May Lord Surya illuminate your life with radiant health, spiritual wisdom, and joyful positivity.",
    sourceHi: "सूर्य नमस्कार मंत्र",
    sourceEn: "Surya Mantra",
    symbol: "sun",
    tag: "सूर्य वंदना",
  },
  {
    id: "suprabhat-3",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "कर्म और कृतज्ञता",
    titleEn: "Gratitude & Good Karma",
    shlokaOrSutra: "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः। सर्वे भद्राणि पश्यन्तु मा कश्चिद्दुःखभाग्भवेत्॥",
    quoteHi: "संसार के सभी प्राणी सुखी हों, निरोगी हों और सभी का कल्याण हो। हर सुबह कृतज्ञ मन से सबको शुभकामनाएं भेजें।",
    quoteEn: "May all beings be happy, may all be free from illness. May all behold what is good, may no one suffer.",
    sourceHi: "उपनिषद् शांति मंत्र",
    sourceEn: "Upanishad Shanti Mantra",
    symbol: "lotus",
    tag: "विश्व शांति",
  },

  // ================= FESTIVAL SPECIALS =================
  {
    id: "festival-1",
    category: "festivals",
    tradition: "jain",
    titleHi: "महावीर जन्म कल्याणक",
    titleEn: "Mahavir Jayanti Wishes",
    shlokaOrSutra: "जय महावीर, जय जिनेन्द्र। अहिंसा परमो धर्मः॥",
    quoteHi: "भगवान महावीर के सत्य, अहिंसा, अपरिग्रह और अनेकांत के पावन संदेश को अपने जीवन में अपनाएं। महावीर जयंती की हार्दिक मंगलकामनाएं!",
    quoteEn: "May the divine teachings of Lord Mahavira guide you on the path of truth, non-violence, and inner peace. Happy Mahavir Jayanti!",
    sourceHi: "महावीर जन्म कल्याणक",
    sourceEn: "Mahavir Janma Kalyanak",
    symbol: "ahimsa",
    tag: "महावीर जयंती",
  },
  {
    id: "festival-2",
    category: "festivals",
    tradition: "hindu",
    titleHi: "दीपावली — प्रकाश और समृद्धि",
    titleEn: "Deepavali Wishes",
    shlokaOrSutra: "तमसो मा ज्योतिर्गमय। मृत्योर्मा अमृतं गमय॥",
    quoteHi: "दीयों का यह पावन पर्व आपके जीवन से अंधकार, क्लेश और निराशा को मिटाकर सुख, समृद्धि व आरोग्यता का दीप जलाए।",
    quoteEn: "May the divine lights of Deepavali illuminate your path towards endless happiness, peace, and auspicious prosperity.",
    sourceHi: "दीपावली मंगलकामना",
    sourceEn: "Diwali Blessings",
    symbol: "diya",
    tag: "दीपावली",
  },
  {
    id: "festival-3",
    category: "festivals",
    tradition: "hindu",
    titleHi: "श्री कृष्ण जन्माष्टमी",
    titleEn: "Krishna Janmashtami",
    shlokaOrSutra: "वसुदेवसुतं देवं कंसचाणूरमर्दनम्। देवकीपरमानन्दं कृष्णं वन्दे जगद्गुरुम्॥",
    quoteHi: "माखनचोर, बंशीधर, जगद्गुरु भगवान श्री कृष्ण का जन्मोत्सव आपके जीवन में प्रेम, आनंद और धर्म का प्रकाश लाए। जय कन्हैया लाल की!",
    quoteEn: "May the divine blessings of Lord Krishna fill your life with love, happiness, and righteous strength. Happy Janmashtami!",
    sourceHi: "श्री कृष्णाष्टमी स्तुति",
    sourceEn: "Krishna Ashtami",
    symbol: "flute",
    tag: "जन्माष्टमी",
  },
  {
    id: "festival-4",
    category: "festivals",
    tradition: "hindu",
    titleHi: "महाशिवरात्रि",
    titleEn: "Maha Shivratri",
    shlokaOrSutra: "ॐ नमः शिवाय। हर हर महादेव॥",
    quoteHi: "देवाधिदेव महादेव और माता पार्वती की कृपा से आपके जीवन के सभी कष्ट दूर हों और मनोकामनाएं पूर्ण हों। महाशिवरात्रि की शुभकामनाएं!",
    quoteEn: "May the infinite grace of Lord Shiva and Maa Parvati bring health, inner peace, and divine bliss to your family.",
    sourceHi: "शिवरात्रि पर्व",
    sourceEn: "Shivratri Blessings",
    symbol: "trishul",
    tag: "महाशिवरात्रि",
  },
];
