export type SuvicharCategory =
  | "all"
  | "jain"
  | "krishna"
  | "mahadev"
  | "hanuman"
  | "ram"
  | "devi"
  | "ganesh"
  | "sant"
  | "festivals"
  | "suprabhat";

export interface SuvicharItem {
  id: string;
  category: SuvicharCategory;
  tradition: "jain" | "hindu" | "universal";
  titleHi: string;
  titleEn: string;
  quoteHi: string;
  quoteHinglish: string;
  quoteEn: string;
  shlokaOrSutra?: string;
  shlokaHinglish?: string;
  sourceHi: string;
  sourceEn: string;
  symbol: "ahimsa" | "om" | "trishul" | "lotus" | "flute" | "bow" | "gada" | "swastik" | "diya" | "sun";
  tag: string;
  tagEn: string;
}

export interface CardTheme {
  id: string;
  nameHi: string;
  nameEn: string;
  bgType: "gradient" | "radial";
  bgColors: [string, string, string?];
  textColor: string;
  accentColor: string;
  shlokaColor: string;
  quoteBoxBg: string;
  badgeBg: string;
  badgeText: string;
  borderColor: string;
  glowColor: string;
  motif: string;
  categoryFit?: SuvicharCategory[];
}

export interface CardAspectRatio {
  id: "story" | "square" | "landscape";
  nameHi: string;
  nameEn: string;
  ratio: string;
  width: number;
  height: number;
  iconText: string;
}

export const ASPECT_RATIOS: CardAspectRatio[] = [
  {
    id: "story",
    nameHi: "व्हाट्सएप स्टेटस (9:16)",
    nameEn: "WhatsApp Status (9:16)",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    iconText: "📱",
  },
  {
    id: "square",
    nameHi: "इंस्टाग्राम पोस्ट (1:1)",
    nameEn: "Square Post (1:1)",
    ratio: "1:1",
    width: 1080,
    height: 1080,
    iconText: "⏹️",
  },
  {
    id: "landscape",
    nameHi: "बैनर / फेसबुक (16:9)",
    nameEn: "Banner / FB (16:9)",
    ratio: "16:9",
    width: 1920,
    height: 1080,
    iconText: "🖼️",
  },
];

export const SALUTATION_PRESETS = [
  { id: "jai-jinendra", textHi: "सप्रेम जय जिनेन्द्र", textEn: "Saprem Jai Jinendra 🙏", tradition: "jain" },
  { id: "michhami-dukkadam", textHi: "मिच्छामि दुक्कडं (क्षमा भाव)", textEn: "Michhami Dukkadam (Kshama Bhaav)", tradition: "jain" },
  { id: "jai-shree-krishna", textHi: "जय श्री कृष्णा", textEn: "Jai Shree Krishna 🪈", tradition: "hindu" },
  { id: "radhe-radhe", textHi: "राधे राधे", textEn: "Radhe Radhe 🌸", tradition: "hindu" },
  { id: "har-har-mahadev", textHi: "हर हर महादेव ॐ", textEn: "Har Har Mahadev ॐ", tradition: "hindu" },
  { id: "jai-shree-ram", textHi: "जय श्री राम 🚩", textEn: "Jai Shree Ram 🚩", tradition: "hindu" },
  { id: "jai-bajrangbali", textHi: "जय बजरंगबली संकटमोचन", textEn: "Jai Bajrangbali Sankatmochan", tradition: "hindu" },
  { id: "jai-mata-di", textHi: "जय माता दी 🌸", textEn: "Jai Mata Di 🌸", tradition: "hindu" },
  { id: "ganpati-bappa-morya", textHi: "गणपति बाप्पा मोरया 🪔", textEn: "Ganpati Bappa Morya 🪔", tradition: "hindu" },
  { id: "jai-shree-shyam", textHi: "हारे का सहारा बाबा श्याम", textEn: "Hare Ka Sahara Baba Shyam", tradition: "hindu" },
  { id: "shubh-prabhat", textHi: "शुभ प्रभात — आपका दिन मंगलमय हो", textEn: "Shubh Prabhat — Have a Blessed Day", tradition: "universal" },
  { id: "shubh-sandhya", textHi: "शुभ संध्या एवं शुभ रात्रि", textEn: "Shubh Sandhya & Good Night", tradition: "universal" },
  { id: "subhkamnaye", textHi: "हार्दिक शुभकामनाएं सहित", textEn: "With Warmest Devotional Wishes", tradition: "universal" },
];

export const CARD_THEMES: CardTheme[] = [
  {
    id: "jain-swarna",
    nameHi: "जैन श्वेत-स्वर्ण (अहिंसा शांति)",
    nameEn: "Jain Pure Gold & White",
    bgType: "gradient",
    bgColors: ["#141E28", "#1E293B", "#0F172A"],
    textColor: "#F8FAFC",
    accentColor: "#F59E0B",
    shlokaColor: "#FDE68A",
    quoteBoxBg: "rgba(255, 255, 255, 0.07)",
    badgeBg: "rgba(245, 158, 11, 0.2)",
    badgeText: "#FCD34D",
    borderColor: "rgba(245, 158, 11, 0.45)",
    glowColor: "rgba(245, 158, 11, 0.25)",
    motif: "✋ 卐",
    categoryFit: ["jain", "suprabhat"],
  },
  {
    id: "vrindavan-sunset",
    nameHi: "वृंदावन संध्या (कृष्ण कृपा)",
    nameEn: "Vrindavan Sunset Glow",
    bgType: "gradient",
    bgColors: ["#2E1065", "#4C1D95", "#831843"],
    textColor: "#FFFBEB",
    accentColor: "#FBBF24",
    shlokaColor: "#FEF08A",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(251, 191, 36, 0.22)",
    badgeText: "#FDE68A",
    borderColor: "rgba(251, 191, 36, 0.5)",
    glowColor: "rgba(217, 119, 6, 0.35)",
    motif: "🦚 🪈",
    categoryFit: ["krishna", "suprabhat"],
  },
  {
    id: "kailash-mahadev",
    nameHi: "कैलाश नीलकंठ (शिव महिमा)",
    nameEn: "Kailash Cosmic Neelkanth",
    bgType: "gradient",
    bgColors: ["#082F49", "#0F172A", "#1E1B4B"],
    textColor: "#F0F9FF",
    accentColor: "#38BDF8",
    shlokaColor: "#BAE6FD",
    quoteBoxBg: "rgba(56, 189, 248, 0.08)",
    badgeBg: "rgba(56, 189, 248, 0.2)",
    badgeText: "#E0F2FE",
    borderColor: "rgba(56, 189, 248, 0.45)",
    glowColor: "rgba(14, 165, 233, 0.3)",
    motif: "🔱 🕉️",
    categoryFit: ["mahadev"],
  },
  {
    id: "ayodhya-saffron",
    nameHi: "अयोध्या भगवा (राम-हनुमान तेज)",
    nameEn: "Ayodhya Divine Saffron",
    bgType: "gradient",
    bgColors: ["#451A03", "#7C2D12", "#9A3412"],
    textColor: "#FFF7ED",
    accentColor: "#F97316",
    shlokaColor: "#FED7AA",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(249, 115, 22, 0.25)",
    badgeText: "#FFEDD5",
    borderColor: "rgba(251, 146, 60, 0.55)",
    glowColor: "rgba(234, 88, 12, 0.35)",
    motif: "🚩 🏹",
    categoryFit: ["ram", "hanuman", "festivals"],
  },
  {
    id: "devi-sindoor",
    nameHi: "माँ शक्ति सिंदूर (दुर्गा-लक्ष्मी)",
    nameEn: "Devi Crimson Radiance",
    bgType: "gradient",
    bgColors: ["#500724", "#831843", "#9F1239"],
    textColor: "#FFF1F2",
    accentColor: "#F43F5E",
    shlokaColor: "#FECDD3",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(244, 63, 94, 0.22)",
    badgeText: "#FFE4E6",
    borderColor: "rgba(251, 113, 133, 0.5)",
    glowColor: "rgba(225, 29, 72, 0.35)",
    motif: "🌺 🪔",
    categoryFit: ["devi", "festivals"],
  },
  {
    id: "royal-swarna-temple",
    nameHi: "स्वर्ण मंदिर प्रभात (दिव्य आभा)",
    nameEn: "Golden Temple Radiance",
    bgType: "gradient",
    bgColors: ["#292524", "#44403C", "#1C1917"],
    textColor: "#FAFAF9",
    accentColor: "#EAB308",
    shlokaColor: "#FEF08A",
    quoteBoxBg: "rgba(234, 179, 8, 0.09)",
    badgeBg: "rgba(234, 179, 8, 0.22)",
    badgeText: "#FEF9C3",
    borderColor: "rgba(234, 179, 8, 0.55)",
    glowColor: "rgba(202, 138, 4, 0.35)",
    motif: "🪔 🌟",
    categoryFit: ["suprabhat", "sant", "ganesh"],
  },
  {
    id: "vedic-marigold",
    nameHi: "वैदिक गेंदा एवं पीताम्बर",
    nameEn: "Vedic Marigold & Pitamber",
    bgType: "gradient",
    bgColors: ["#3F2E05", "#713F12", "#854D0E"],
    textColor: "#FEFCE8",
    accentColor: "#FACC15",
    shlokaColor: "#FEF9C3",
    quoteBoxBg: "rgba(255, 255, 255, 0.08)",
    badgeBg: "rgba(250, 204, 21, 0.22)",
    badgeText: "#FEF08A",
    borderColor: "rgba(250, 204, 21, 0.5)",
    glowColor: "rgba(234, 179, 8, 0.35)",
    motif: "🌼 🪔",
    categoryFit: ["ganesh", "festivals", "suprabhat"],
  },
  {
    id: "brahma-muhurat",
    nameHi: "शांत ब्रह्म मुहूर्त (गहन ध्यान)",
    nameEn: "Brahma Muhurat Starlight",
    bgType: "gradient",
    bgColors: ["#090A0F", "#111827", "#1E1B4B"],
    textColor: "#F9FAFB",
    accentColor: "#A78BFA",
    shlokaColor: "#DDD6FE",
    quoteBoxBg: "rgba(167, 139, 250, 0.08)",
    badgeBg: "rgba(167, 139, 250, 0.2)",
    badgeText: "#EDE9FE",
    borderColor: "rgba(167, 139, 250, 0.45)",
    glowColor: "rgba(139, 92, 246, 0.3)",
    motif: "✨ 🌌",
    categoryFit: ["sant", "suprabhat"],
  },
];

export const SUVICHAR_DATABASE: SuvicharItem[] = [
  // ================= 1. JAIN DHARMA & BHAGWAN MAHAVIRA =================
  {
    id: "jain-1",
    category: "jain",
    tradition: "jain",
    titleHi: "अहिंसा परमो धर्मः",
    titleEn: "Ahimsa Paramo Dharma",
    shlokaOrSutra: "अहिंसा परमो धर्मः, धर्म हिंसा तथैव च।",
    shlokaHinglish: "Ahimsa Paramo Dharmah",
    quoteHi: "संसार के सभी जीवों के प्रति करुणा और मैत्री भाव रखो। किसी भी जीव को दुःख मत पहुंचाओ, क्योंकि सभी को अपना जीवन प्रिय है।",
    quoteHinglish: "Sansar ke sabhi jeevon ke prati karuna aur maitri bhaav rakhein. Kisi ko dukh na pahunchayein, sabhi ko apna jeevan priya hai.",
    quoteEn: "Have compassion and friendship towards all living beings. Injure no one, for all life is sacred and precious.",
    sourceHi: "भगवान महावीर (आचारांग सूत्र)",
    sourceEn: "Bhagwan Mahavira (Acharanga Sutra)",
    symbol: "ahimsa",
    tag: "जैन धर्म",
    tagEn: "Jain Dharma",
  },
  {
    id: "jain-2",
    category: "jain",
    tradition: "jain",
    titleHi: "जियो और जीने दो",
    titleEn: "Live and Let Live",
    shlokaOrSutra: "परस्परोपग्रहो जीवानाम्।",
    shlokaHinglish: "Parasparopagraho Jeevanam",
    quoteHi: "स्वयं शांति से जियो और दूसरों को भी शांति व स्वतंत्रता से जीने दो। प्राणी मात्र के प्रति मन में प्रेम ही सच्चा धर्म है।",
    quoteHinglish: "Swayam shanti se jiyein aur doosron ko bhi shanti se jeene dein. Prani matra ke prati prem hi sachha dharma hai.",
    quoteEn: "Live peacefully and let all others live with peace and freedom. Compassion for all beings is true dharma.",
    sourceHi: "भगवान महावीर संदेश",
    sourceEn: "Bhagwan Mahavira Teaching",
    symbol: "ahimsa",
    tag: "महावीर वाणी",
    tagEn: "Mahavira Vani",
  },
  {
    id: "jain-3",
    category: "jain",
    tradition: "jain",
    titleHi: "नवकार महामंत्र",
    titleEn: "Navkar Mahamantra",
    shlokaOrSutra: "णमो अरिहंताणं, णमो सिद्धाणं, णमो आयरियाणं। णमो उवज्झायाणं, णमो लोए सव्व साहूणं॥",
    shlokaHinglish: "Namo Arihantanam, Namo Siddhanam, Namo Aayariyanam. Namo Uvajjhayanam, Namo Loye Savva Sahunam.",
    quoteHi: "यह पंच परमेष्ठी को किया गया पावन नमन सभी पापों का नाश करने वाला और सम्पूर्ण जगत में परम कल्याणकारी है।",
    quoteHinglish: "Yeh Panch Parmeshthi ko kiya gaya pavan naman sabhi paapon ka nash karne wala aur param kalyankari hai.",
    quoteEn: "Salutations to Arihants, Siddhas, Acharyas, Upadhyayas, and all Sadhus. May this sacred mantra bestow eternal peace.",
    sourceHi: "श्री नवकार महामंत्र",
    sourceEn: "Shri Navkar Mahamantra",
    symbol: "swastik",
    tag: "नवकार मंत्र",
    tagEn: "Navkar Mantra",
  },
  {
    id: "jain-4",
    category: "jain",
    tradition: "jain",
    titleHi: "क्रोध पर विजय",
    titleEn: "Conquering Anger",
    shlokaOrSutra: "अक्कोधेन जिणे कोधं, असाधुं साहुणा जिणे।",
    shlokaHinglish: "Akkodhena Jine Kodham, Asadhum Sahuna Jine",
    quoteHi: "क्रोध को शांत भाव से जीतो, दुष्टता को सज्जनता से जीतो, लोभ को दान से जीतो और असत्य को सत्य से जीतो।",
    quoteHinglish: "Krodh ko shant bhaav se jeeto, dushtata ko sajjanta se jeeto, lobh ko daan se jeeto aur asatya ko satya se jeeto.",
    quoteEn: "Conquer anger with forgiveness, wickedness with goodness, greed with generosity, and falsehood with truth.",
    sourceHi: "भगवान महावीर (उत्तराध्ययन सूत्र)",
    sourceEn: "Bhagwan Mahavira (Uttaradhyayana Sutra)",
    symbol: "lotus",
    tag: "सदाचार",
    tagEn: "Virtue & Peace",
  },
  {
    id: "jain-5",
    category: "jain",
    tradition: "jain",
    titleHi: "क्षमावणी — मिच्छामि दुक्कडं",
    titleEn: "Michhami Dukkadam (Forgiveness)",
    shlokaOrSutra: "खामेमि सव्व जीवे, सव्वे जीवा खमंतु मे। मित्ती मे सव्व भूएसु, वेरं मज्झं न केणइ॥",
    shlokaHinglish: "Khamemi Savva Jeeve, Savve Jeeva Khamantu Me. Mitti Me Savva Bhuesu, Veram Majjham Na Kenai.",
    quoteHi: "मैं संसार के सभी जीवों से क्षमा याचना करता हूँ, सभी जीव मुझे क्षमा करें। मेरी सबके साथ मित्रता है, किसी से कोई वैर नहीं।",
    quoteHinglish: "Main sansar ke sabhi jeevon se kshama mangta hoon, sabhi mujhe kshama karein. Meri sabse mitrata hai, kisi se bair nahi.",
    quoteEn: "I ask forgiveness from all living beings; may all beings forgive me. I have friendship with all, and enmity with none.",
    sourceHi: "जैन क्षमावणी सूत्र",
    sourceEn: "Jain Forgiveness Sutra",
    symbol: "ahimsa",
    tag: "पर्युषण व क्षमावाणी",
    tagEn: "Paryushan & Kshamavani",
  },
  {
    id: "jain-6",
    category: "jain",
    tradition: "jain",
    titleHi: "कर्म और आत्म-कल्याण",
    titleEn: "Karma & The Pure Soul",
    shlokaOrSutra: "अप्पा कत्ता विकत्ता य, दुहाण य सुहाण य।",
    shlokaHinglish: "Appa Katta Vikatta Ya, Duhana Ya Suhana Ya",
    quoteHi: "अपनी आत्मा ही अपने सुख और दुःख का कर्ता और भोक्ता है। शुभ विचारों और शुद्ध कर्मों से ही आत्मा का कल्याण होता है।",
    quoteHinglish: "Apni aatma hi apne sukh aur dukh ki karta hai. Shubh vicharon aur shuddh karmon se hi aatma ka kalyan hota hai.",
    quoteEn: "The soul itself is the maker of its own joy and sorrow. Pure thoughts and righteous deeds illuminate the soul.",
    sourceHi: "श्री उत्तराध्ययन सूत्र",
    sourceEn: "Uttaradhyayana Sutra",
    symbol: "diya",
    tag: "कर्म सिद्धांत",
    tagEn: "Karma Principle",
  },
  {
    id: "jain-7",
    category: "jain",
    tradition: "jain",
    titleHi: "चत्तारि मंगलं",
    titleEn: "Chattari Mangalam",
    shlokaOrSutra: "चत्तारि मंगलं: अरिहंता मंगलं, सिद्धा मंगलं, साहू मंगलं, केवलिपन्नत्तो धम्मो मंगलं।",
    shlokaHinglish: "Chattari Mangalam: Arihanta Mangalam, Siddha Mangalam, Sahu Mangalam, Kevali-Pannatto Dhammo Mangalam.",
    quoteHi: "अरिहंत मंगल हैं, सिद्ध मंगल हैं, साधु मंगल हैं और केवलि भगवान द्वारा प्ररूपित दयामयी धर्म ही परम मंगलकारी है।",
    quoteHinglish: "Arihant mangal hain, Siddh mangal hain, Sadhu mangal hain aur Kevali bhagwan dwara bataya dayamayi dharma param mangal hai.",
    quoteEn: "Auspicious are the Arihants, the Siddhas, the Sadhus, and the compassionate Dharma revealed by the Enlightened.",
    sourceHi: "जैन मंगल पाठ",
    sourceEn: "Jain Mangal Path",
    symbol: "swastik",
    tag: "मंगल पाठ",
    tagEn: "Auspicious Refuge",
  },
  {
    id: "jain-8",
    category: "jain",
    tradition: "jain",
    titleHi: "अनेकांतवाद — सबका दृष्टिकोण समझो",
    titleEn: "Anekantavada — Many-Sided Truth",
    shlokaOrSutra: "सच्चं लोगम्मि सारभूयं।",
    shlokaHinglish: "Sachham Logammi Sarabhuyam",
    quoteHi: "सत्य के अनेक पहलू होते हैं। दूसरों के विचारों और आस्थाओं का सम्मान करना ही सच्चे ज्ञानी और अहिंसक का लक्षण है।",
    quoteHinglish: "Satya ke anek pehloo hote hain. Doosron ke vicharon aur aasthaon ka samman karna hi sachha gyan hai.",
    quoteEn: "Truth has multifaceted perspectives. Respecting the viewpoints and beliefs of others is the mark of true wisdom.",
    sourceHi: "भगवान महावीर दर्शन",
    sourceEn: "Mahavira Philosophy",
    symbol: "ahimsa",
    tag: "अनेकांतवाद",
    tagEn: "Anekantavada",
  },
  {
    id: "jain-9",
    category: "jain",
    tradition: "jain",
    titleHi: "अपरिग्रह — संतोष ही सबसे बड़ा धन",
    titleEn: "Aparigraha — True Contentment",
    shlokaOrSutra: "इच्छा हु आगास समा अणंतिया।",
    shlokaHinglish: "Ichha Hu Aagasa Sama Anantiya",
    quoteHi: "इच्छाएं आकाश की तरह अनंत हैं। जितना अधिक संतोष रखोगे, मन उतना ही शांत, भयमुक्त और आनंदित रहेगा।",
    quoteHinglish: "Ichhayein aakash ki tarah anant hain. Jitna santosh rakhoge, man utna hi shant aur anandit rahega.",
    quoteEn: "Desires are limitless like the sky. True wealth and freedom lie in contentment and detachment.",
    sourceHi: "उत्तराध्ययन सूत्र (9/48)",
    sourceEn: "Uttaradhyayana Sutra",
    symbol: "lotus",
    tag: "अपरिग्रह",
    tagEn: "Non-Possessiveness",
  },
  {
    id: "jain-10",
    category: "jain",
    tradition: "jain",
    titleHi: "रत्नत्रय — मोक्ष का मार्ग",
    titleEn: "Ratnatraya — The Three Jewels",
    shlokaOrSutra: "सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः।",
    shlokaHinglish: "Samyag-Darshana-Jnana-Charitrani Mokshamargah",
    quoteHi: "सम्यक दर्शन (सच्ची श्रद्धा), सम्यक ज्ञान (सच्चा बोध) और सम्यक चरित्र (सदाचार) ही आत्म-मुक्ति और परम शांति का मार्ग हैं।",
    quoteHinglish: "Samyak Darshan, Samyak Gyan aur Samyak Charitra hi aatma ki mukti aur anand ka shreshth marg hain.",
    quoteEn: "Right Faith, Right Knowledge, and Right Conduct together constitute the ultimate path to liberation and peace.",
    sourceHi: "तत्वार्थ सूत्र (आचार्य उमास्वामी)",
    sourceEn: "Tattvartha Sutra",
    symbol: "swastik",
    tag: "रत्नत्रय",
    tagEn: "Three Jewels",
  },
  {
    id: "jain-11",
    category: "jain",
    tradition: "jain",
    titleHi: "स्वयं पर विजय ही सबसे बड़ी जीत",
    titleEn: "Conquering Oneself",
    shlokaOrSutra: "जो सहस्सं सहस्साणं संगामे दुज्जए जिणे। एगं जिणेज्ज अप्पाणं एस से परमो जिओ॥",
    shlokaHinglish: "Jo Sahassam Sahassanam Sangame Dujjaye Jine. Egam Jinejja Appanam Esa Se Paramo Jio.",
    quoteHi: "हजारों युद्धों में लाखों शत्रुओं को जीतने वाले से कहीं श्रेष्ठ वह वीर है, जो अपनी ही इंद्रियों और मन को जीत लेता है।",
    quoteHinglish: "Hazaron yuddhon ko jeetne wale se kahin mahan woh hai, jo apne hi man aur indriyon ko jeet leta hai.",
    quoteEn: "Greater than conqueror of a million in battle is the spiritual hero who conquers his own mind and senses.",
    sourceHi: "भगवान महावीर (उत्तराध्ययन)",
    sourceEn: "Bhagwan Mahavira",
    symbol: "ahimsa",
    tag: "जितेन्द्रिय",
    tagEn: "Self-Mastery",
  },
  {
    id: "jain-12",
    category: "jain",
    tradition: "jain",
    titleHi: "वाणी की मधुरता और सत्य",
    titleEn: "Sweet & Truthful Speech",
    shlokaOrSutra: "सच्चं वए अणिस्सिओ।",
    shlokaHinglish: "Sachham Vaye Anissio",
    quoteHi: "सदा सत्य और प्रिय वाणी बोलो। जो शब्द किसी का दिल दुखाएं, वे मौन रहने से भी अधिक हानिकारक होते हैं।",
    quoteHinglish: "Sada satya aur priya vani bolein. Jo shabd kisi ka dil dukhayein, unse bachein aur prem se bolein.",
    quoteEn: "Speak words that are truthful, gentle, and beneficial. Words that wound others are worse than silence.",
    sourceHi: "दशवैकालिक सूत्र",
    sourceEn: "Dashavaikalika Sutra",
    symbol: "lotus",
    tag: "मधुर वाणी",
    tagEn: "Truthful Speech",
  },
  {
    id: "jain-13",
    category: "jain",
    tradition: "jain",
    titleHi: "आत्मा ही मंदिर है",
    titleEn: "The Soul is the Temple",
    shlokaOrSutra: "अप्पा सो परमप्पा।",
    shlokaHinglish: "Appa So Paramappa",
    quoteHi: "अपनी आत्मा को विकारों और दुर्भावों से मुक्त कर लो, वही परमात्मा का साक्षात स्वरूप बन जाती है।",
    quoteHinglish: "Apni aatma ko vikar aur buraaiyon se mukt kar lo, wahi Parmatma ka roop ban jaati hai.",
    quoteEn: "Free your inner self from passions and deceit, and the pure soul itself reveals the Divine.",
    sourceHi: "परमात्म प्रकाश (आचार्य योगिन्दु)",
    sourceEn: "Paramatma Prakasha",
    symbol: "diya",
    tag: "आत्म दर्शन",
    tagEn: "Soul Divinity",
  },

  // ================= 2. SHRI KRISHNA & BHAGAVAD GITA =================
  {
    id: "krishna-1",
    category: "krishna",
    tradition: "hindu",
    titleHi: "कर्मयोग — फल की चिंता मत करो",
    titleEn: "Karmayoga — Focus on Duty",
    shlokaOrSutra: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥",
    shlokaHinglish: "Karmanye Vadhikaraste Ma Phaleshu Kadachana. Ma Karma-Phala-Heturbhur Ma Te Sango'stv Akarmani.",
    quoteHi: "तुम्हारा अधिकार केवल कर्म करने पर है, उसके फलों पर कभी नहीं। फल की इच्छा से कर्म मत करो और न ही कर्म त्यागने में आसक्त होओ।",
    quoteHinglish: "Tumhara adhikar kewal karm karne par hai, fal par kabhi nahi. Nishkam bhaav se apna kartavya nibhate chalo.",
    quoteEn: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Act with devotion.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 2, श्लोक 47)",
    sourceEn: "Bhagavad Gita (2.47)",
    symbol: "flute",
    tag: "गीता ज्ञान",
    tagEn: "Gita Wisdom",
  },
  {
    id: "krishna-2",
    category: "krishna",
    tradition: "hindu",
    titleHi: "धर्म की रक्षा और ईश्वर कृपा",
    titleEn: "Divine Protection",
    shlokaOrSutra: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥",
    shlokaHinglish: "Yada Yada Hi Dharmasya Glanir Bhavati Bharata. Abhyutthanam Adharmasya Tadatmanam Srijamy Aham.",
    quoteHi: "जब-जब धर्म की हानि और अधर्म की वृद्धि होती है, तब-तब मैं सज्जनों की रक्षा और धर्म की पुनर्स्थापना हेतु अवतरित होता हूँ।",
    quoteHinglish: "Jab-jab dharma ki haani hoti hai aur adharma badhta hai, tab-tab main sajjanon ki raksha aur dharma sthapna ke liye prakat hota hoon.",
    quoteEn: "Whenever there is a decline in righteousness, I manifest Myself for the protection of the good and re-establishment of Dharma.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 4, श्लोक 7)",
    sourceEn: "Bhagavad Gita (4.7)",
    symbol: "flute",
    tag: "श्री कृष्ण वाणी",
    tagEn: "Krishna Vani",
  },
  {
    id: "krishna-3",
    category: "krishna",
    tradition: "hindu",
    titleHi: "मन पर नियंत्रण",
    titleEn: "Mastery of the Mind",
    shlokaOrSutra: "असंशयं महाबाहो मनो दुर्निग्रहं चलम्। अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते॥",
    shlokaHinglish: "Asamshayam Mahabaho Mano Durnigraham Chalam. Abhyasena Tu Kaunteya Vairagyena Cha Grihyate.",
    quoteHi: "मन चंचल और कठिनता से वश में होने वाला अवश्य है, परन्तु निरंतर अभ्यास और वैराग्य से इसे पूर्णतः शांत किया जा सकता है।",
    quoteHinglish: "Man chanchal zaroor hai, par nirantar abhyas aur vairagya se ise poori tarah shant kiya ja sakta hai.",
    quoteEn: "The mind is restless and hard to control, but by regular practice and detachment, it can certainly be mastered.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 6, श्लोक 35)",
    sourceEn: "Bhagavad Gita (6.35)",
    symbol: "flute",
    tag: "मन की शांति",
    tagEn: "Peace of Mind",
  },
  {
    id: "krishna-4",
    category: "krishna",
    tradition: "hindu",
    titleHi: "सर्वसमर्पण और निर्भयता",
    titleEn: "Total Surrender & Fearlessness",
    shlokaOrSutra: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज। अहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥",
    shlokaHinglish: "Sarva-Dharman Parityajya Mam Ekam Sharanam Vraja. Aham Tvam Sarva-Papebhyo Mokshayishyami Ma Shuchah.",
    quoteHi: "सब चिंताओं और संशयों को छोड़कर केवल मेरी शरण में आ जाओ। मैं तुम्हें समस्त दुःखों व भयों से मुक्त कर दूंगा, शोक मत करो।",
    quoteHinglish: "Sab chintayein chhod kar kewal meri sharan mein aa jao. Main tumhe sabhi dukhon aur bhay se mukt kar doonga.",
    quoteEn: "Surrender all your worries unto Me alone. I will liberate you from all fears and anxieties; do not grieve.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 18, श्लोक 66)",
    sourceEn: "Bhagavad Gita (18.66)",
    symbol: "flute",
    tag: "शरणागति",
    tagEn: "Surrender",
  },
  {
    id: "krishna-5",
    category: "krishna",
    tradition: "hindu",
    titleHi: "राधे राधे की महिमा",
    titleEn: "Radhe Radhe Bhakti",
    shlokaOrSutra: "श्री राधा मेरी स्वामिनी, मैं राधे को दास। जनम जनम मोहि दीजियो, श्री वृन्दावन वास॥",
    shlokaHinglish: "Shri Radha Meri Swamini, Main Radhe Ko Daas. Janam Janam Mohi Deejiyo, Shri Vrindavan Vaas.",
    quoteHi: "जिसके हृदय में श्री राधा-कृष्ण का नाम बसता है, उसके जीवन की सभी चिंताएं और कष्ट स्वतः दूर हो जाते हैं।",
    quoteHinglish: "Jinke hriday mein Shri Radha Krishna ka naam basta hai, unke jeevan ke sabhi sankat aur chintayein door ho jati hain.",
    quoteEn: "Whosoever holds the sacred name of Radha-Krishna in the heart finds eternal peace and divine grace.",
    sourceHi: "ब्रज भक्ति रस",
    sourceEn: "Braj Devotional Wisdom",
    symbol: "lotus",
    tag: "राधा कृष्ण",
    tagEn: "Radha Krishna",
  },
  {
    id: "krishna-6",
    category: "krishna",
    tradition: "hindu",
    titleHi: "स्थितप्रज्ञ — सुख और दुःख में समता",
    titleEn: "Sthitaprajna — Equanimity",
    shlokaOrSutra: "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः। वीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते॥",
    shlokaHinglish: "Dukheshv Anudvigna-Manah Sukheshu Vigata-Sprihah. Veeta-Raga-Bhaya-Krodhah Sthita-Dheer Munir Uchyate.",
    quoteHi: "दुःख में जो विचलित नहीं होता और सुख में जो आसक्त नहीं होता; जिसके राग, भय और क्रोध मिट चुके हैं, वही सच्चा स्थिरबुद्धि है।",
    quoteHinglish: "Dukh mein jo ghabrata nahi aur sukh mein ahankar nahi karta, wahi sthir buddhi wala sachha gyani hai.",
    quoteEn: "One undisturbed in sorrow, detached in joy, and free from fear and anger is truly poised in divine wisdom.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 2, श्लोक 56)",
    sourceEn: "Bhagavad Gita (2.56)",
    symbol: "flute",
    tag: "स्थितप्रज्ञ",
    tagEn: "Equanimity",
  },
  {
    id: "krishna-7",
    category: "krishna",
    tradition: "hindu",
    titleHi: "अनन्य भक्ति और योगक्षेम",
    titleEn: "Unwavering Devotion & Grace",
    shlokaOrSutra: "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते। तेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥",
    shlokaHinglish: "Ananyash Chintayanto Mam Ye Janah Paryupasate. Tesham Nityabhiyuktanam Yoga-Kshemam Vahamy Aham.",
    quoteHi: "जो अनन्य भाव से मेरा स्मरण करते हैं, उन नित्य युक्त भक्तों की सभी आवश्यकताओं और सुरक्षा की चिंता मैं स्वयं करता हूँ।",
    quoteHinglish: "Jo sache man se mera dhyan karte hain, unke jeevan ki har zaroorat aur suraksha ka dhyan main swayam rakhta hoon.",
    quoteEn: "To those who always remember Me with focused devotion, I personally provide what they lack and preserve what they have.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 9, श्लोक 22)",
    sourceEn: "Bhagavad Gita (9.22)",
    symbol: "flute",
    tag: "योगक्षेम",
    tagEn: "Divine Assurance",
  },
  {
    id: "krishna-8",
    category: "krishna",
    tradition: "hindu",
    titleHi: "पत्रं पुष्पं फलं तोयम् — भाव की प्रधानता",
    titleEn: "Love Over Rituals",
    shlokaOrSutra: "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति। तदहं भक्त्युपहृतमश्नामि प्रयतात्मनः॥",
    shlokaHinglish: "Patram Pushpam Phalam Toyam Yo Me Bhaktya Prayachhati. Tad Aham Bhakty-Upahritam Ashnami Prayatatmanah.",
    quoteHi: "यदि कोई मुझे प्रेम और निष्ठा से एक पत्ता, फूल, फल या केवल जल भी अर्पित करता है, तो मैं उसे सहर्ष स्वीकार करता हूँ।",
    quoteHinglish: "Prem aur shraddha se diya gaya ek patta ya jal bhi Prabhu ko param priya hai. Bhakti mein bhav hi mukhya hai.",
    quoteEn: "Whoever offers Me with love a leaf, a flower, a fruit, or even water, I accept with immense joy.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 9, श्लोक 26)",
    sourceEn: "Bhagavad Gita (9.26)",
    symbol: "lotus",
    tag: "प्रेम भक्ति",
    tagEn: "Pure Love",
  },
  {
    id: "krishna-9",
    category: "krishna",
    tradition: "hindu",
    titleHi: "आत्मा अमर है",
    titleEn: "The Immortal Soul",
    shlokaOrSutra: "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः। न चैनं क्लेदयन्त्यापो न शोषयति मारुतः॥",
    shlokaHinglish: "Nainam Chhindanti Shastrani Nainam Dahati Pavakah. Na Chainam Kledayanty Apo Na Shoshayati Marutah.",
    quoteHi: "आत्मा को न शस्त्र काट सकते हैं, न अग्नि जला सकती है, न जल भिगो सकता है और न वायु सुखा सकती है। आत्मा शाश्वत और अमर है।",
    quoteHinglish: "Aatma ko koi shastra nahi kaat sakta, aag nahi jala sakti. Aatma nitya, shashwat aur amar hai.",
    quoteEn: "Weapons cannot cut the soul, fire cannot burn it, water cannot wet it, nor can the wind dry it. The soul is eternal.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 2, श्लोक 23)",
    sourceEn: "Bhagavad Gita (2.23)",
    symbol: "flute",
    tag: "अमर आत्मा",
    tagEn: "Eternal Soul",
  },
  {
    id: "krishna-10",
    category: "krishna",
    tradition: "hindu",
    titleHi: "वासुदेवः सर्वमिति",
    titleEn: "All is Divine",
    shlokaOrSutra: "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते। वासुदेवः सर्वमिति स महात्मा सुदुर्लभः॥",
    shlokaHinglish: "Bahunam Janmanam Ante Jnanavan Mam Prapadyate. Vasudevah Sarvam Iti Sa Mahatma Sudurlabhah.",
    quoteHi: "अनेक जन्मों के बाद जो ज्ञानी यह अनुभव करता है कि सब कुछ परमात्मा ही है, ऐसा महात्मा अत्यंत दुर्लभ होता है।",
    quoteHinglish: "Jo har prani mein Ishwar ka roop dekhta hai aur sabhi se prem karta hai, wahi sachha gyani hai.",
    quoteEn: "After many lifetimes of spiritual quest, one who realizes that the Divine is all in all is indeed a rare soul.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 7, श्लोक 19)",
    sourceEn: "Bhagavad Gita (7.19)",
    symbol: "flute",
    tag: "सर्वव्यापी ईश्वर",
    tagEn: "Omnipresent God",
  },
  {
    id: "krishna-11",
    category: "krishna",
    tradition: "hindu",
    titleHi: "क्रोध से बुद्धि का नाश",
    titleEn: "Anger Destroys Reason",
    shlokaOrSutra: "क्रोधाद्भवति संमोहः संमोहात्स्मृतिविभ्रमः। स्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति॥",
    shlokaHinglish: "Krodhad Bhavati Sammohah Sammohat Smriti-Vibhramah. Smriti-Bhranshad Buddhi-Nasho Buddhi-Nashat Pranashyati.",
    quoteHi: "क्रोध से भ्रम उत्पन्न होता है, भ्रम से स्मृति नष्ट होती है और स्मृति नष्ट होने से बुद्धि का नाश होता है। शांत मन ही सबसे बड़ा बल है।",
    quoteHinglish: "Krodh se buddhi ka vinash hota hai. Har kathin samay mein man ko shant aur sthir rakhein.",
    quoteEn: "From anger arises delusion, from delusion loss of memory, and from loss of memory destruction of intellect. Peace is power.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 2, श्लोक 63)",
    sourceEn: "Bhagavad Gita (2.63)",
    symbol: "flute",
    tag: "आत्मसंयम",
    tagEn: "Self Control",
  },
  {
    id: "krishna-12",
    category: "krishna",
    tradition: "hindu",
    titleHi: "ईश्वर सबके हृदय में स्थित हैं",
    titleEn: "The Divine Within Every Heart",
    shlokaOrSutra: "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति। भ्रामयन्सर्वभूतानि यन्त्रारूढानि मायया॥",
    shlokaHinglish: "Ishwarah Sarva-Bhutanam Hrid-Deshe'rjuna Tishthati. Bhramayan Sarva-Bhutani Yantrarudhani Mayaya.",
    quoteHi: "भगवान सबके हृदय में विराजमान हैं। जब भीतर ही परमात्मा का वास है, तो किसी से द्वेष और ईर्ष्या कैसी?",
    quoteHinglish: "Ishwar har prani ke hriday mein baste hain. Sabke prati aadar aur prem ka bhaav rakhein.",
    quoteEn: "The Supreme Lord resides in the hearts of all living beings. Love all and harbor malice towards none.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 18, श्लोक 61)",
    sourceEn: "Bhagavad Gita (18.61)",
    symbol: "lotus",
    tag: "हृदयस्थ ईश्वर",
    tagEn: "Inner Divinity",
  },

  // ================= 3. MAHADEV & SHIVA BHAKTI =================
  {
    id: "mahadev-1",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "महामृत्युंजय संजीवनी मंत्र",
    titleEn: "Mahamrityunjaya Mantra",
    shlokaOrSutra: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय मामृतात्॥",
    shlokaHinglish: "Om Tryambakam Yajamahe Sugandhim Pushti-Vardhanam. Urvarukamiva Bandhanan Mrityor Mukshiya Mamritat.",
    quoteHi: "हम त्रिनेत्रधारी भगवान शिव की आराधना करते हैं, जो समस्त संसार को जीवन शक्ति देते हैं। वे हमें मृत्यु के भय से मुक्त कर अमरता प्रदान करें।",
    quoteHinglish: "Hum Trinetradhari Bhagwan Shiv ki aradhana karte hain jo samast sansar ko urja dete hain. Mahadev sabhi bhay door karein.",
    quoteEn: "We worship the Three-Eyed Lord Shiva, the fragrant nourisher of life. May He liberate us from bondage and fear of death.",
    sourceHi: "ऋग्वेद एवं यजुर्वेद",
    sourceEn: "Rigveda & Yajurveda",
    symbol: "trishul",
    tag: "शिव महामंत्र",
    tagEn: "Shiva Mahamantra",
  },
  {
    id: "mahadev-2",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "महाकाल कृपा और निर्भयता",
    titleEn: "Mahakaal's Divine Grace",
    shlokaOrSutra: "अकाल मृत्यु वो मरे जो काम करे चांडाल का। काल भी उसका क्या बिगाड़े जो भक्त हो महाकाल का॥",
    shlokaHinglish: "Akaal Mrityu Vo Mare Jo Kaam Kare Chandal Ka. Kaal Bhi Uska Kya Bigade Jo Bhakt Ho Mahakaal Ka.",
    quoteHi: "सच्चे मन से जो महादेव का ध्यान करता है, संकट और काल भी उसका कुछ नहीं बिगाड़ सकते। हर परिस्थिति में शांत रहें।",
    quoteHinglish: "Sachhe man se jo Mahadev ka dhyan karta hai, sankat aur kaal bhi uska kuch nahi bigad sakte. Har pal shant rahein.",
    quoteEn: "Those sheltered under Mahakaal's grace fear nothing in the cosmos. True surrender brings boundless strength.",
    sourceHi: "शिव महिमा",
    sourceEn: "Shiva Mahima",
    symbol: "trishul",
    tag: "महाकाल",
    tagEn: "Mahakaal",
  },
  {
    id: "mahadev-3",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "विषपान और सहनशीलता",
    titleEn: "Patience and Compassion",
    shlokaOrSutra: "कर्पूरगौरं करुणावतारं संसारसारम् भुजगेन्द्रहारम्। सदावसन्तं हृदयारविन्दे भवं भवानीसहितं नमामि॥",
    shlokaHinglish: "Karpura-Gauram Karunavataram Samsarasaram Bhujagendra-Haram. Sada Vasantam Hridayaravinde Bhavam Bhavani-Sahitam Namami.",
    quoteHi: "जो विष पीकर भी शांत और कल्याणकारी रहे, वही महादेव हैं। जीवन की कड़वाहट को भी धैर्य और प्रेम से जीतना ही शिवत्व है।",
    quoteHinglish: "Jo vish peekar bhi shant aur kalyankari rahe, wahi Mahadev hain. Jeevan ki kadwahat ko dhairya se jeetna hi Shivtva hai.",
    quoteEn: "To absorb life's negativity calmly and radiate love and welfare for all is the true essence of Shiva consciousness.",
    sourceHi: "भवानी स्तुति",
    sourceEn: "Bhavani Stuti",
    symbol: "lotus",
    tag: "सहनशीलता",
    tagEn: "Patience & Love",
  },
  {
    id: "mahadev-4",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "ॐ नमः शिवाय — पंचाक्षर स्तोत्र",
    titleEn: "Om Namah Shivaya",
    shlokaOrSutra: "नागेन्द्रहाराय त्रिलोचनाय भस्माङ्गरागाय महेश्वराय। नित्याय शुद्धाय दिगम्बराय तस्मै नकाराय नमः शिवाय॥",
    shlokaHinglish: "Nagendra-Haraya Trilochanaya Bhasmanga-Ragaya Maheshwaraya. Nityaya Shuddhaya Digambaraya Tasmai Nakaraya Namah Shivaya.",
    quoteHi: "भगवान शिव नित्य, शुद्ध और कल्याण के सागर हैं। 'ॐ नमः शिवाय' का निरंतर जप मन को पवित्र और एकाग्र बनाता है।",
    quoteHinglish: "Bhagwan Shiv nitya aur pavitra hain. Om Namah Shivaya ka jaap man ke sabhi dukhon ko shant karta hai.",
    quoteEn: "Salutations to Lord Shiva, the pure, eternal, and auspicious Supreme Lord. Chanting His name dispels all inner darkness.",
    sourceHi: "शिव पंचाक्षर स्तोत्र",
    sourceEn: "Shiva Panchakshara Stotra",
    symbol: "trishul",
    tag: "पंचाक्षर स्तोत्र",
    tagEn: "Panchakshara Stotra",
  },
  {
    id: "mahadev-5",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "भोलेनाथ का सरल स्वभाव",
    titleEn: "Bholenath's Simple Grace",
    shlokaOrSutra: "दयालुं भक्तवत्सलं शरणं प्रपद्ये।",
    shlokaHinglish: "Dayalum Bhakta-Vatsalam Sharanam Prapadye",
    quoteHi: "महादेव को न स्वर्ण चाहिए, न कोई दिखावा। केवल एक लोटा शुद्ध जल और सच्चे भाव का बेलपत्र ही शिव को प्रसन्न कर देता है।",
    quoteHinglish: "Mahadev ko koi dikhawa nahi chahiye. Ek lota jal aur saccha bhav hi Bholenath ko prasanna kar deta hai.",
    quoteEn: "Lord Shiva desires no opulent displays. A single pot of clean water and a leaf of pure devotion wins His endless grace.",
    sourceHi: "शिव पुराण",
    sourceEn: "Shiva Purana",
    symbol: "trishul",
    tag: "भोलेनाथ",
    tagEn: "Bholenath",
  },
  {
    id: "mahadev-6",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "शिव तांडव — ऊर्जा और आनंद",
    titleEn: "Shiva Tandava — Cosmic Energy",
    shlokaOrSutra: "जटाटवीगलज्जलप्रवाहपावितस्थले गलेऽवलम्ब्य लम्बितां भुजङ्गतुङ्गमालिकाम्। डमड्डमड्डमड्डमन्निनादवड्डमर्वयं चकार चण्डताण्डवं तनोतु नः शिवः शिवम्॥",
    shlokaHinglish: "Jatatavi-Galajjala-Pravaha-Pavitasthale Gale'valambya Lambitam Bhujanga-Tunga-Malikam.",
    quoteHi: "महादेव का तांडव सृष्टि के संहार और नए सृजन का प्रतीक है। जीवन के हर परिवर्तन को सहर्ष स्वीकार करना ही सच्चा वैराग्य है।",
    quoteHinglish: "Mahadev ka Tandava parivartan aur nayi urja ka prateek hai. Har sthiti mein aanandit rahein.",
    quoteEn: "Shiva's cosmic dance signifies eternal transformation and renewal. Embrace life's changes with courage and joy.",
    sourceHi: "शिव ताण्डव स्तोत्र (रावण विरचित)",
    sourceEn: "Shiva Tandava Stotram",
    symbol: "trishul",
    tag: "शिव तांडव",
    tagEn: "Cosmic Dance",
  },
  {
    id: "mahadev-7",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "सोमनाथ एवं 12 ज्योतिर्लिंग",
    titleEn: "Jyotirlinga Radiance",
    shlokaOrSutra: "सौराष्ट्रे सोमनाथं च श्रीशैले मल्लिकार्जुनम्। उज्जयिन्यां महाकालमोङ्कारममलेश्वरम्॥",
    shlokaHinglish: "Saurashtre Somanatham Cha Shrishayle Mallikarjunam. Ujjayinyam Mahakalam Omkaram Amaleshwaram.",
    quoteHi: "द्वादश ज्योतिर्लिंगों का स्मरण मात्र भक्तों के समस्त संकटों का निवारण करता है और जीवन में प्रकाश भर देता है।",
    quoteHinglish: "Jyotirlingon ka smaran man mein shanti aur urja bharta hai. Har Har Mahadev!",
    quoteEn: "Meditating upon the twelve sacred Jyotirlingas dispels sorrow and brings immense spiritual radiance into life.",
    sourceHi: "द्वादश ज्योतिर्लिंग स्तोत्र",
    sourceEn: "Dwadasha Jyotirlinga Stotram",
    symbol: "trishul",
    tag: "ज्योतिर्लिंग",
    tagEn: "Jyotirlinga",
  },

  // ================= 4. SANKATMOCHAN HANUMAN JI =================
  {
    id: "hanuman-1",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "संकट कटै मिटै सब पीरा",
    titleEn: "Sankat Kate Mite Sab Peera",
    shlokaOrSutra: "संकट कटै मिटै सब पीरा। जो सुमिरै हनुमत बलबीरा॥",
    shlokaHinglish: "Sankat Kate Mite Sab Peera. Jo Sumirai Hanumat Balbeera.",
    quoteHi: "जो भी वीर हनुमान जी का निरंतर स्मरण व ध्यान करता है, उसके जीवन के सभी संकट, भय और पीड़ाएं तत्काल मिट जाती हैं।",
    quoteHinglish: "Jo bhi Veer Hanuman Ji ka nitya smaran karta hai, uske sabhi sankat, bhay aur dukh door ho jaate hain.",
    quoteEn: "All troubles vanish and all sorrows are eradicated for one who meditates upon the mighty and compassionate Hanuman.",
    sourceHi: "श्री हनुमान चालीसा (गोस्वामी तुलसीदास)",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "हनुमान चालीसा",
    tagEn: "Hanuman Chalisa",
  },
  {
    id: "hanuman-2",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "सब सुख लहै तुम्हारी सरना",
    titleEn: "Fearless in Hanuman's Shelter",
    shlokaOrSutra: "सब सुख लहै तुम्हारी सरना। तुम रक्षक काहू को डर ना॥",
    shlokaHinglish: "Sab Sukh Lahai Tumhari Sarna. Tum Rakshak Kahu Ko Dar Na.",
    quoteHi: "पवनपुत्र हनुमान जी की शरण में आने पर संसार के सभी सुख और निर्भयता प्राप्त होती है। जब वे हमारे रक्षक हैं, तो किसका भय?",
    quoteHinglish: "Pawanputra Hanuman Ji ki sharan mein aane par sabhi sukh aur nidarata milti hai. Prabhu hamare rakshak hain.",
    quoteEn: "In your shelter, all joy is attained. When you are our protector, whom shall we fear?",
    sourceHi: "श्री हनुमान चालीसा",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "निर्भयता",
    tagEn: "Fearlessness",
  },
  {
    id: "hanuman-3",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "अतुलित बलधामं — ज्ञान और विनम्रता",
    titleEn: "Strength with Humility",
    shlokaOrSutra: "अतुलितबलधामं हेमशैलाभदेहं दनुजवनकृशानुं ज्ञानिनामग्रगण्यम्। सकलगुणनिधानं वानराणामधीशं रघुपतिप्रियभक्तं वातजातं नमामि॥",
    shlokaHinglish: "Atulita-Bala-Dhamam Hema-Shailabha-Deham Danuja-Vana-Krishanum Jnaninam Agra-Ganyam.",
    quoteHi: "अपरिमित बल के स्वामी होकर भी परम विनम्र और ज्ञानी बने रहना ही हनुमान जी का सबसे बड़ा गुण है। शक्ति के साथ विनम्रता ही सच्ची दिव्यता है।",
    quoteHinglish: "Aparimit bal ke sath vinamrata aur gyan ka hona hi Hanuman Ji ka sabse bada aadarsh hai.",
    quoteEn: "Possessing infinite strength yet radiating supreme humility and devotion is Hanuman's divine hallmark.",
    sourceHi: "रामचरितमानस (सुन्दरकाण्ड श्लोक)",
    sourceEn: "Ramcharitmanas",
    symbol: "gada",
    tag: "हनुमान वंदना",
    tagEn: "Hanuman Vandana",
  },
  {
    id: "hanuman-4",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "दुर्गम काज जगत के जेते",
    titleEn: "All Obstacles Dissolve",
    shlokaOrSutra: "दुर्गम काज जगत के जेते। सुगम अनुग्रह तुम्हरे तेते॥",
    shlokaHinglish: "Durgam Kaaj Jagat Ke Jete. Sugam Anugraha Tumhre Tete.",
    quoteHi: "संसार के जितने भी कठिन और असंभव कार्य हैं, वे हनुमान जी की कृपा मात्र से अत्यंत सुलभ और सरल हो जाते हैं।",
    quoteHinglish: "Sansar ke sabhi kathin karya Hanuman Ji ki kripa se asaan ho jaate hain. Jai Bajrangbali!",
    quoteEn: "Whatever difficult tasks exist in the world become effortlessly easy by the loving grace of Hanuman.",
    sourceHi: "श्री हनुमान चालीसा",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "संकटमोचन",
    tagEn: "Obstacle Remover",
  },
  {
    id: "hanuman-5",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "राम रसायन तुम्हरे पासा",
    titleEn: "The Elixir of Ram Naam",
    shlokaOrSutra: "राम रसायन तुम्हरे पासा। सदा रहो रघुपति के दासा॥",
    shlokaHinglish: "Ram Rasayan Tumhre Pasa. Sada Raho Raghupati Ke Dasa.",
    quoteHi: "हनुमान जी के पास राम नाम रूपी वह अमूल्य औषधि है, जो जीवन के समस्त रोगों, दुःखों और संतापों को क्षण भर में हर लेती है।",
    quoteHinglish: "Ram naam ki aushadhi sabhi chintaon aur rogon ko door karti hai. Nitya Ram naam ka smaran karein.",
    quoteEn: "Hanuman holds the divine elixir of Ram Naam, which instantly heals all worldly afflictions and anxieties.",
    sourceHi: "श्री हनुमान चालीसा",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "राम रसायन",
    tagEn: "Ram Rasayana",
  },
  {
    id: "hanuman-6",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "मनोजवं मारुततुल्यवेगम्",
    titleEn: "Master of Speed and Senses",
    shlokaOrSutra: "मनोजवं मारुततुल्यवेगं जितेन्द्रियं बुद्धिमतां वरिष्ठम्। वातात्मजं वानरयूथमुख्यं श्रीरामदूतं शरणं प्रपद्ये॥",
    shlokaHinglish: "Manojavam Maruta-Tulya-Vegam Jitendriyam Buddhimatam Varishtham. Vatatmajam Vanara-Yootha-Mukhyam Shri Rama Dutam Sharanam Prapadye.",
    quoteHi: "मन के समान तीव्र गति वाले, इंद्रियों को जीतने वाले और बुद्धिमानों में श्रेष्ठ श्री रामदूत हनुमान जी की हम शरण लेते हैं।",
    quoteHinglish: "Indriyon ko jeetne wale aur buddhiman Hanuman Ji ki sharan lene se sabhi karya safal hote hain.",
    quoteEn: "We take refuge in Shri Rama's messenger, Hanuman, swift as the mind, master of the senses, and foremost among the wise.",
    sourceHi: "हनुमान स्तुति",
    sourceEn: "Hanuman Stuti",
    symbol: "gada",
    tag: "रामदूत",
    tagEn: "Rama's Messenger",
  },

  // ================= 5. SHRI RAM & RAMAYANA =================
  {
    id: "ram-1",
    category: "ram",
    tradition: "hindu",
    titleHi: "रघुकुल रीति — मर्यादा और वचन",
    titleEn: "Raghukul Reeti — Righteous Duty",
    shlokaOrSutra: "रघुकुल रीति सदा चलि आई। प्राण जाहुं बरु बचनु न जाई॥",
    shlokaHinglish: "Raghukul Reeti Sada Chali Aai. Pran Jahun Baru Bachanu Na Jai.",
    quoteHi: "सत्य, मर्यादा और कर्तव्य पालन ही जीवन का सबसे बड़ा आदर्श है। अपने वचनों और मूल्यों पर अटल रहना ही सच्ची मर्यादा है।",
    quoteHinglish: "Satya, maryada aur kartavya palan hi jeevan ka sabse bada aadarsh hai. Apne vachanon par atal rahna hi Maryada hai.",
    quoteEn: "Righteousness, honor, and truthfulness stand above all else. Holding onto virtue brings eternal glory.",
    sourceHi: "श्रीरामचरितमानस (बालकाण्ड)",
    sourceEn: "Ramcharitmanas",
    symbol: "bow",
    tag: "मर्यादा पुरुषोत्तम",
    tagEn: "Maryada Purushottam",
  },
  {
    id: "ram-2",
    category: "ram",
    tradition: "hindu",
    titleHi: "निर्मल मन की भक्ति",
    titleEn: "Purity of Heart",
    shlokaOrSutra: "निर्मल मन जन सो मोहि पावा। मोहि कपट छल छिद्र न भावा॥",
    shlokaHinglish: "Nirmal Man Jan So Mohi Pawa. Mohi Kapat Chhal Chhidra Na Bhawa.",
    quoteHi: "भगवान श्री राम कहते हैं: जिसका मन निर्मल और पवित्र है, वही मुझे प्राप्त कर सकता है। मुझे छल-कपट और अहंकार तनिक भी प्रिय नहीं।",
    quoteHinglish: "Bhagwan Shri Ram kahte hain: Jiska man nirmal aur pavitra hai, wahi mujhe pata hai. Kapat aur ahankar se door rahein.",
    quoteEn: "Lord Rama says: Only one with a pure, honest heart attains Me. Guile, arrogance, and deceit find no favor with the Divine.",
    sourceHi: "श्रीरामचरितमानस (सुन्दरकाण्ड)",
    sourceEn: "Ramcharitmanas (Sundarkand)",
    symbol: "bow",
    tag: "निर्मल भक्ति",
    tagEn: "Pure Devotion",
  },
  {
    id: "ram-3",
    category: "ram",
    tradition: "hindu",
    titleHi: "राम नाम की असीम महिमा",
    titleEn: "Glory of Ram Naam",
    shlokaOrSutra: "कलयुग केवल नाम अधारा। सुमिरि सुमिरि नर उतरहिं पारा॥",
    shlokaHinglish: "Kalyug Kewal Naam Adhara. Sumiri Sumiri Nar Utarahin Para.",
    quoteHi: "इस कलिकाल में प्रभु का पावन नाम ही एकमात्र सहारा है। सच्चे मन से नाम जप करने वाला संसार के सभी भवों से पार हो जाता है।",
    quoteHinglish: "Kalyug mein Prabhu ka naam hi sabse bada sahara hai. Nitya prem se Ram naam ka smaran karein.",
    quoteEn: "In this age, the divine Name alone is the supreme anchor. Remembering it with devotion carries one across all oceans of sorrow.",
    sourceHi: "श्रीरामचरितमानस",
    sourceEn: "Ramcharitmanas",
    symbol: "bow",
    tag: "नाम जप",
    tagEn: "Naam Jaap",
  },
  {
    id: "ram-4",
    category: "ram",
    tradition: "hindu",
    titleHi: "शबरी की निष्कपट भक्ति",
    titleEn: "Shabari's Devotion",
    shlokaOrSutra: "कह रघुपति सुनु भामिनि बाता। मानउँ एक भगति कर नाता॥",
    shlokaHinglish: "Kaha Raghupati Sunu Bhamini Bata. Manau Ek Bhagati Kar Nata.",
    quoteHi: "श्री राम कहते हैं: मैं जाति, कुल, धन या पद को नहीं देखता; मैं केवल प्रेम और भक्ति के संबंध को ही पहचानता हूँ।",
    quoteHinglish: "Bhagwan Ram keval prem aur pavitra bhav ko dekhte hain. Nishkapat bhakti hi sabse badi pooja hai.",
    quoteEn: "Lord Rama says: I recognize only one bond—the bond of selfless love and unpretentious devotion.",
    sourceHi: "श्रीरामचरितमानस (अरण्यकाण्ड)",
    sourceEn: "Ramcharitmanas (Aranya Kand)",
    symbol: "bow",
    tag: "शबरी भक्ति",
    tagEn: "Shabari Bhakti",
  },
  {
    id: "ram-5",
    category: "ram",
    tradition: "hindu",
    titleHi: "धीरज, धर्म, मित्र अरु नारी",
    titleEn: "True Testing Times",
    shlokaOrSutra: "धीरज धर्म मित्र अरु नारी। आपद काल परिखिअहिं चारी॥",
    shlokaHinglish: "Dheeraj Dharma Mitra Aru Nari. Aapad Kaal Parikhiyahi Chari.",
    quoteHi: "धैर्य, धर्म, मित्र और जीवनसाथी — इन चारों की वास्तविक परीक्षा संकट और कठिन समय में ही होती है। कठिन समय में धैर्य कभी न छोड़ें।",
    quoteHinglish: "Kathin samay mein dhairya aur dharma par atal rahna hi sachhi shakti hai.",
    quoteEn: "Patience, righteousness, true friends, and spouse are truly tested in times of adversity. Never lose patience.",
    sourceHi: "श्रीरामचरितमानस",
    sourceEn: "Ramcharitmanas",
    symbol: "bow",
    tag: "धैर्य व धर्म",
    tagEn: "Patience & Virtue",
  },
  {
    id: "ram-6",
    category: "ram",
    tradition: "hindu",
    titleHi: "राम राज्य — समता और सुख",
    titleEn: "Ram Rajya — Peace & Prosperity",
    shlokaOrSutra: "दैहिक दैविक भौतिक तापा। राम राज नहिं काहुहि ब्यापा॥",
    shlokaHinglish: "Daihik Daivik Bhautik Tapa. Ram Raj Nahin Kahuhi Byapa.",
    quoteHi: "राम राज्य में न कोई दुखी था, न कोई पीड़ित। जब जीवन में धर्म और न्याय का वास होता है, तो घर-घर में राम राज्य का सुख उतर आता है।",
    quoteHinglish: "Jahan dharma aur nyay hota hai, wahan Ram Rajya ka anand hota hai. Sabhi ke hit mein sochein.",
    quoteEn: "In Ram Rajya, all sorrow and strife ceased to exist. Where truth and justice reign, divine peace flourishes.",
    sourceHi: "श्रीरामचरितमानस (उत्तरकाण्ड)",
    sourceEn: "Ramcharitmanas (Uttarkand)",
    symbol: "bow",
    tag: "राम राज्य",
    tagEn: "Ram Rajya",
  },

  // ================= 6. MAA DURGA, LAKSHMI & SHAKTI =================
  {
    id: "devi-1",
    category: "devi",
    tradition: "hindu",
    titleHi: "सर्वमंगल मांगल्ये",
    titleEn: "Sarva Mangala Mangalye",
    shlokaOrSutra: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥",
    shlokaHinglish: "Sarva-Mangala-Mangalye Shive Sarvartha-Sadhike. Sharanye Tryambake Gauri Narayani Namo'stu Te.",
    quoteHi: "जो सब मंगलों में परम मंगलमयी, कल्याणकारी और सभी मनोकामनाओं को सिद्ध करने वाली हैं, उन माँ जगदम्बा को कोटि-कोटि नमन।",
    quoteHinglish: "Jo sab mangalon mein param mangalmayi aur sabhi shubh manokamnayein poorn karne wali hain, Maa Jagdamba ko koti naman.",
    quoteEn: "Salutations to the most auspicious Mother, the fulfiller of all pure desires and protector of all who seek Her shelter.",
    sourceHi: "श्री दुर्गा सप्तशती",
    sourceEn: "Durga Saptashati",
    symbol: "lotus",
    tag: "दुर्गा स्तुति",
    tagEn: "Durga Stuti",
  },
  {
    id: "devi-2",
    category: "devi",
    tradition: "hindu",
    titleHi: "माँ महालक्ष्मी कृपा",
    titleEn: "Maa Mahalakshmi Blessings",
    shlokaOrSutra: "नमस्तेऽस्तु महामाये श्रीपीठे सुरपूजिते। शङ्खचक्रगदाहस्ते महालक्ष्मि नमोऽस्तु ते॥",
    shlokaHinglish: "Namaste'stu Mahamaye Shree-Peethe Sura-Poojite. Shankha-Chakra-Gada-Haste Mahalakshmi Namo'stu Te.",
    quoteHi: "माँ लक्ष्मी आपके घर-आंगन में सुख, शांति, समृद्धि और सद्बुद्धि का वास करें। परिश्रम और ईमानदारी ही लक्ष्मी का सच्चा निवास है।",
    quoteHinglish: "Maa Lakshmi aapke ghar mein sukh, shanti, samriddhi aur sadbuddhi ka vaas karein. Parishram hi Lakshmi ka sachha nivas hai.",
    quoteEn: "May Goddess Lakshmi bless your life with boundless joy, prosperity, purity, and virtuous wisdom.",
    sourceHi: "महालक्ष्मी अष्टकम",
    sourceEn: "Mahalakshmi Ashtakam",
    symbol: "lotus",
    tag: "महालक्ष्मी",
    tagEn: "Maha Lakshmi",
  },
  {
    id: "devi-3",
    category: "devi",
    tradition: "hindu",
    titleHi: "माँ सरस्वती — ज्ञान और विद्या",
    titleEn: "Maa Saraswati — Wisdom & Learning",
    shlokaOrSutra: "या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता या वीणावरदण्डमण्डितकरा या श्वेतपद्मासना। सा मां पातु सरस्वती भगवती निःशेषजाड्यापहा॥",
    shlokaHinglish: "Ya Kundendu-Tushara-Hara-Dhavala Ya Shubhra-Vastravrita Ya Veena-Vara-Danda-Mandita-Kara Ya Shweta-Padmasana.",
    quoteHi: "माँ सरस्वती अज्ञान के अंधकार को मिटाकर जीवन में ज्ञान, विद्या और विवेक का प्रकाश भरें। ज्ञान ही मनुष्य का सबसे बड़ा आभूषण है।",
    quoteHinglish: "Maa Saraswati jeevan se agyan ka andhkar door kar gyan aur vivek pradan karein.",
    quoteEn: "May Goddess Saraswati, embodiment of pure wisdom, eradicate all inner darkness and illuminate our intellect.",
    sourceHi: "सरस्वती वंदना",
    sourceEn: "Saraswati Vandana",
    symbol: "lotus",
    tag: "सरस्वती वंदना",
    tagEn: "Saraswati Vandana",
  },
  {
    id: "devi-4",
    category: "devi",
    tradition: "hindu",
    titleHi: "गायत्री महामंत्र — सद्बुद्धि का प्रकाश",
    titleEn: "Gayatri Mahamantra",
    shlokaOrSutra: "ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्॥",
    shlokaHinglish: "Om Bhur Bhuvah Swah Tat Savitur Varenyam Bhargo Devasya Dheemahi Dhiyo Yo Nah Prachodayat.",
    quoteHi: "हम उस सृष्टिकर्ता परम प्रकाशमान परमात्मा के दिव्य तेज का ध्यान करते हैं, जो हमारी बुद्धि को सत्कर्मों और सत्य के मार्ग पर प्रेरित करे।",
    quoteHinglish: "Hum Parmatma ke divya tej ka dhyan karte hain jo hamari buddhi ko satya aur gyan ki disha mein prerit kare.",
    quoteEn: "We meditate upon the glorious radiance of the Supreme Divine. May that Divine Light illuminate and guide our intellect.",
    sourceHi: "ऋग्वेद (गायत्री मंत्र)",
    sourceEn: "Rigveda (Gayatri Mantra)",
    symbol: "sun",
    tag: "गायत्री मंत्र",
    tagEn: "Gayatri Mantra",
  },
  {
    id: "devi-5",
    category: "devi",
    tradition: "hindu",
    titleHi: "या देवी सर्वभूतेषु — मातृ रूप",
    titleEn: "The Mother in All Beings",
    shlokaOrSutra: "या देवी सर्वभूतेषु मातृरूपेण संस्थिता। नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥",
    shlokaHinglish: "Ya Devi Sarva-Bhuteshu Matri-Rupena Samsthita. Namas Tasyai Namas Tasyai Namas Tasyai Namo Namah.",
    quoteHi: "जो देवी समस्त जीवों में माता, दया, शांति और चेतना के रूप में विराजमान हैं, उन करुणामयी जगदम्बा को बारंबार नमन।",
    quoteHinglish: "Jo Devi sabhi jeevon mein daya, shanti aur prem ke roop mein baste hain, unhein koti-koti naman.",
    quoteEn: "Salutations again and again to the Divine Mother who abides in all living beings as love, peace, and consciousness.",
    sourceHi: "श्री दुर्गा सप्तशती",
    sourceEn: "Durga Saptashati",
    symbol: "lotus",
    tag: "मातृ शक्ति",
    tagEn: "Divine Motherhood",
  },
  {
    id: "devi-6",
    category: "devi",
    tradition: "hindu",
    titleHi: "अन्नपूर्णा सदा पूर्णे — अन्न व शांति",
    titleEn: "Maa Annapurna — Abundance",
    shlokaOrSutra: "अन्नपूर्णे सदापूर्णे शङ्करप्राणवल्लभे। ज्ञानवैराग्यसिद्ध्यर्थं भिक्षां देहि च पार्वति॥",
    shlokaHinglish: "Annapurne Sada-Poorne Shankara-Prana-Vallabhe. Jnana-Vairagya-Siddhyartham Bhiksham Dehi Cha Parvati.",
    quoteHi: "माँ अन्नपूर्णा सभी के घरों में अन्न, धन, ज्ञान और वैराग्य की समृद्धि बनाए रखें। किसी भी घर में कोई भूखा न रहे।",
    quoteHinglish: "Maa Annapurna sabhi ke gharon mein sukh aur ann-dhan ki barakat banaye rakhein.",
    quoteEn: "O Mother Annapurna, fulfiller of all nourishment, bestow upon us the alms of knowledge, detachment, and joyful abundance.",
    sourceHi: "अन्नपूर्णा स्तोत्र (आदि शंकराचार्य)",
    sourceEn: "Annapurna Stotram",
    symbol: "diya",
    tag: "अन्नपूर्णा",
    tagEn: "Annapurna",
  },

  // ================= 7. GANPATI BAPPA =================
  {
    id: "ganesh-1",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "वक्रतुण्ड महाकाय — विघ्नहर्ता",
    titleEn: "Vakratunda Mahakaya",
    shlokaOrSutra: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
    shlokaHinglish: "Vakratunda Mahakaya Suryakoti Samaprabha. Nirvighnam Kuru Me Deva Sarva-Karyeshu Sarvada.",
    quoteHi: "करोड़ों सूर्यों के समान दिव्य तेज वाले विघ्नहर्ता श्री गणेश आपके जीवन के सभी विघ्नों को दूर कर हर कार्य में सफलता प्रदान करें।",
    quoteHinglish: "Vighnaharta Shri Ganesh aapke jeevan ke sabhi vighnon ko door kar har shubh karya mein safalta pradan karein.",
    quoteEn: "May Lord Ganesha, radiating with the brilliance of a million suns, remove all hurdles and bless your endeavors with grand success.",
    sourceHi: "श्री गणेश स्तुति",
    sourceEn: "Ganesh Stuti",
    symbol: "swastik",
    tag: "प्रथम पूज्य गणेश",
    tagEn: "Lord Ganesha",
  },
  {
    id: "ganesh-2",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "गजाननं भूतगणादि सेवितम्",
    titleEn: "Gajananam — Auspicious Beginnings",
    shlokaOrSutra: "गजाननं भूतगणादिसेवितं कपित्थजम्बूफलचारुभक्षणम्। उमासुतं शोकविनाशकारकं नमामि विघ्नेश्वरपादपङ्कजम्॥",
    shlokaHinglish: "Gajananam Bhuta-Ganadi-Sevitam Kapittha-Jambu-Phala-Charu-Bhakshanam.",
    quoteHi: "समस्त दुःखों और बाधाओं का नाश करने वाले उमापुत्र विघ्नेश्वर श्री गणेश के पावन चरणों में हमारा शत-शत नमन।",
    quoteHinglish: "Dukhon aur badhaon ko door karne wale Bappa ke charnon mein naman. Har shubh kaam mangalmay ho.",
    quoteEn: "We bow before the lotus feet of Lord Ganesha, the son of Uma and the destroyer of all grief and sorrow.",
    sourceHi: "गणेश ध्यान मंत्र",
    sourceEn: "Ganesh Dhyana Mantra",
    symbol: "swastik",
    tag: "विघ्नहर्ता",
    tagEn: "Remover of Obstacles",
  },
  {
    id: "ganesh-3",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "रिद्धि-सिद्धि और शुभ-लाभ",
    titleEn: "Riddhi-Siddhi & Auspicious Wealth",
    shlokaOrSutra: "एकदन्ताय विद्महे वक्रतुण्डाय धीमहि। तन्नो दन्तिः प्रचोदयात्॥",
    shlokaHinglish: "Ekadantaya Vidmahe Vakratundaya Dheemahi. Tanno Dantih Prachodayat.",
    quoteHi: "भगवान गणेश आपके घर-परिवार में रिद्धि, सिद्धि, सुख, समृद्धि और शुभता का वास करें। हर दिन मंगलमय हो।",
    quoteHinglish: "Ganpati Bappa aapke jeevan mein sukh, samriddhi aur safalta layein. Ganpati Bappa Morya!",
    quoteEn: "May Lord Ganesha bestow divine wisdom, prosperity, success, and auspicious blessings upon your home.",
    sourceHi: "गणेश गायत्री मंत्र",
    sourceEn: "Ganesh Gayatri Mantra",
    symbol: "swastik",
    tag: "शुभ लाभ",
    tagEn: "Auspicious Success",
  },
  {
    id: "ganesh-4",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "मोदक प्रिय — जीवन में मधुरता",
    titleEn: "Sweetness of Life",
    shlokaOrSutra: "प्रणम्य शिरसा देवं गौरीपुत्रं विनायकम्।",
    shlokaHinglish: "Pranamya Shirasa Devam Gauri-Putram Vinayakam",
    quoteHi: "जैसे बप्पा को मोदक प्रिय है, वैसे ही अपने स्वभाव में मधुरता, वाणी में प्रेम और व्यवहार में सरलता रखें।",
    quoteHinglish: "Apni vani aur vyavahar mein sada madhurta aur prem banaye rakhein.",
    quoteEn: "Cultivate sweetness in speech, kindness in conduct, and joy in every small deed, just as Ganesha loves sweetness.",
    sourceHi: "संकटनाशन गणेश स्तोत्र",
    sourceEn: "Sankatnashan Ganesh Stotra",
    symbol: "swastik",
    tag: "मधुरता",
    tagEn: "Sweetness",
  },

  // ================= 8. SANT VANI, KABIR & GURU NANAK =================
  {
    id: "sant-1",
    category: "sant",
    tradition: "universal",
    titleHi: "संत कबीर — आत्म-निरीक्षण",
    titleEn: "Sant Kabir — Self Reflection",
    shlokaOrSutra: "बुरा जो देखन मैं चला, बुरा न मिलिया कोय। जो दिल खोजा आपना, मुझसे बुरा न कोय॥",
    shlokaHinglish: "Bura Jo Dekhan Main Chala, Bura Na Miliya Koy. Jo Dil Khoja Aapna, Mujhse Bura Na Koy.",
    quoteHi: "दूसरों में दोष ढूंढने के बजाय जब हम अपने अंतर्मन में झांकते हैं, तब समझ आता है कि वास्तविक सुधार स्वयं से ही शुरू होता है।",
    quoteHinglish: "Doosron mein dosh dhoondhne ke bajay jab hum apne andar jhaankte hain, tab pata chalta hai ki sudhar swayam se shuru hota hai.",
    quoteEn: "When I searched for faults in others, I found none. When I looked inside my own heart, I realized true change starts within.",
    sourceHi: "संत कबीर साखी",
    sourceEn: "Sant Kabir Sakhi",
    symbol: "diya",
    tag: "कबीर वाणी",
    tagEn: "Kabir Vani",
  },
  {
    id: "sant-2",
    category: "sant",
    tradition: "universal",
    titleHi: "गुरु नानक देव — एक ओंकार",
    titleEn: "Guru Nanak — Ik Onkar",
    shlokaOrSutra: "ੴ सतिनामु करता पुरखु निरभउ निरवैरु अकाल मूरति अजूनी सैभं गुर प्रसादि॥",
    shlokaHinglish: "Ik Onkar Satnam Karta Purakh Nirbhau Nirvair Akal Moorat Ajoonee Saibhang Gur Parsad.",
    quoteHi: "ईश्वर एक है, सत्य ही उसका नाम है। जो बिना किसी भय और वैर के सभी से प्रेम करता है, वही प्रभु की कृपा का पात्र बनता है।",
    quoteHinglish: "Ishwar ek hai, Satya hi uska naam hai. Jo bina kisi bhay aur bair ke sabhi se prem karta hai, wahi prabhu kripa pata hai.",
    quoteEn: "God is One, Truth is His Name. Live without fear and without malice, and radiate goodwill to all creation.",
    sourceHi: "श्री गुरु नानक देव जी (जपजी साहिब)",
    sourceEn: "Guru Nanak Dev (Japji Sahib)",
    symbol: "om",
    tag: "गुरु संदेश",
    tagEn: "Guru Nanak",
  },
  {
    id: "sant-3",
    category: "sant",
    tradition: "universal",
    titleHi: "ऐसी बानी बोलिए — मन का आपा खोय",
    titleEn: "Gentle & Healing Speech",
    shlokaOrSutra: "ऐसी बानी बोलिए, मन का आपा खोय। औरन को सीतल करै, आपहु सीतल होय॥",
    shlokaHinglish: "Aisi Bani Boliye, Man Ka Aapa Khoy. Auran Ko Seetal Karai, Aapahu Seetal Hoy.",
    quoteHi: "अहंकार को त्यागकर ऐसी मधुर वाणी बोलो जो सुनने वाले के हृदय को शांति दे और स्वयं आपके मन को भी शीतलता प्रदान करे।",
    quoteHinglish: "Ahankar chhod kar aisi meethi vani bolein jo doosron ko shanti de aur swayam ko bhi anand de.",
    quoteEn: "Speak words devoid of ego that soothe the hearts of others while filling your own soul with cooling tranquility.",
    sourceHi: "संत कबीर दोहा",
    sourceEn: "Sant Kabir Doha",
    symbol: "lotus",
    tag: "मधुर वाणी",
    tagEn: "Sweet Speech",
  },
  {
    id: "sant-4",
    category: "sant",
    tradition: "universal",
    titleHi: "वृक्ष कबहुँ नहिं फल भखै — परोपकार",
    titleEn: "Selfless Service & Giving",
    shlokaOrSutra: "वृच्छ कबहूँ न फल भखै, नदी न संचै नीर। परमारथ के कारने, साधुन धरा सरीर॥",
    shlokaHinglish: "Vriksh Kabahu Nahin Phal Bhakhai, Nadi Na Sanchai Neer. Parmarath Ke Kaarne, Sadhun Dhara Sareer.",
    quoteHi: "पेड़ कभी अपना फल स्वयं नहीं खाते, नदियां कभी अपना जल स्वयं नहीं पीतीं। सज्जनों का जीवन सदैव दूसरों की भलाई के लिए होता है।",
    quoteHinglish: "Ped apna fal nahi khate, nadi apna paani nahi peeti. Doosron ki nishkam sahayata karna hi sachha manavta hai.",
    quoteEn: "Trees never eat their own fruit, rivers never drink their own water. Noble souls exist solely for the welfare of others.",
    sourceHi: "संत कबीर दोहा",
    sourceEn: "Sant Kabir",
    symbol: "lotus",
    tag: "परोपकार",
    tagEn: "Selfless Giving",
  },
  {
    id: "sant-5",
    category: "sant",
    tradition: "universal",
    titleHi: "चाणक्य नीति — विद्या ही सच्चा मित्र",
    titleEn: "Chanakya — True Wealth of Knowledge",
    shlokaOrSutra: "विद्या मित्रं प्रवासेषु भार्या मित्रं गृहेषु च। व्याधितस्यौषधं मित्रं धर्मो मित्रं मृतस्य च॥",
    shlokaHinglish: "Vidya Mitram Pravaseshu Bharya Mitram Griheshu Cha. Vyadhitasyaushadham Mitram Dharmo Mitram Mritasya Cha.",
    quoteHi: "विदेश में ज्ञान मित्र होता है, घर में गुणवान साथी मित्र होता है, रोगी के लिए औषधि मित्र होती है और परलोक में धर्म ही सच्चा मित्र है।",
    quoteHinglish: "Gyan aur dharma hi jeevan ke sabse sachhe aur sthir sathi hain.",
    quoteEn: "Knowledge is a friend on a journey, good character at home, medicine in sickness, and righteousness after life.",
    sourceHi: "चाणक्य नीति",
    sourceEn: "Chanakya Neeti",
    symbol: "diya",
    tag: "चाणक्य नीति",
    tagEn: "Chanakya Wisdom",
  },
  {
    id: "sant-6",
    category: "sant",
    tradition: "universal",
    titleHi: "मीराबाई — प्रभु प्रेम का रंग",
    titleEn: "Mirabai — Pure Unconditional Love",
    shlokaOrSutra: "पायो जी मैंने राम रतन धन पायो। वस्तु अमोलक दी मेरे सतगुरु, किरपा करि अपनायो॥",
    shlokaHinglish: "Payo Ji Maine Ram Ratan Dhan Payo. Vastu Amolak Dee Mere Satguru, Kirpa Kari Apnayo.",
    quoteHi: "संसार के सभी धन नश्वर हैं, केवल प्रभु भक्ति और नाम रूपी धन ही ऐसा है जो कभी समाप्त नहीं होता और हर जन्म में साथ रहता है।",
    quoteHinglish: "Prabhu prem aur naam jaap hi aatma ka sabse bada amoolya ratan hai.",
    quoteEn: "All worldly riches fade away. The treasure of the Divine Name alone is eternal and inexhaustible.",
    sourceHi: "भक्त शिरोमणि मीराबाई",
    sourceEn: "Sant Mirabai",
    symbol: "lotus",
    tag: "मीरा पद",
    tagEn: "Mirabai Bhakti",
  },

  // ================= 9. DAILY SUPRABHAT & MORNING MOTIVATION =================
  {
    id: "suprabhat-1",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "शुभ प्रभात — नया सवेरा, नई आशा",
    titleEn: "Shubh Prabhat — Morning Blessing",
    shlokaOrSutra: "कराग्रे वसते लक्ष्मीः करमध्ये सरस्वती। करमूले तु गोविन्दः प्रभाते करदर्शनम्॥",
    shlokaHinglish: "Karagre Vasate Lakshmih Kara-Madhye Saraswati. Kara-Moole Tu Govindah Prabhate Kara-Darshanam.",
    quoteHi: "सुबह उठकर अपनी हथेलियों का दर्शन कर ईश्वर को नमन करें। हर नया दिन परमात्मा का अनमोल उपहार है, इसे सकारात्मकता से जिएं।",
    quoteHinglish: "Subah uthkar Ishwar ko naman karein. Har naya din Parmatma ka anmol uphaar hai, ise sakaratmakta se jiyein. Shubh Prabhat!",
    quoteEn: "Every sunrise brings new opportunities to do good, spread kindness, and walk on the path of truth. Have a blessed morning!",
    sourceHi: "वैदिक प्रभात श्लोक",
    sourceEn: "Vedic Morning Verse",
    symbol: "sun",
    tag: "शुभ प्रभात",
    tagEn: "Good Morning",
  },
  {
    id: "suprabhat-2",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "विश्व शांति — सर्वे भवन्तु सुखिनः",
    titleEn: "Universal Peace & Wellness",
    shlokaOrSutra: "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः। सर्वे भद्राणि पश्यन्तु मा कश्चिद्दुःखभाग्भवेत्॥",
    shlokaHinglish: "Sarve Bhavantu Sukhinah Sarve Santu Niramayah. Sarve Bhadrani Pashyantu Ma Kashchid-Dukha-Bhag-Bhavet.",
    quoteHi: "संसार के सभी प्राणी सुखी हों, निरोगी हों और सभी का कल्याण हो। हर सुबह कृतज्ञ मन से सबको शुभकामनाएं भेजें।",
    quoteHinglish: "Sansar ke sabhi prani sukhi hon, nirogi hon aur sabhi ka kalyan ho. Aapka din shubh aur anandmayi ho.",
    quoteEn: "May all beings be happy, may all be free from illness. May all behold what is good, may no one suffer.",
    sourceHi: "उपनिषद् शांति मंत्र",
    sourceEn: "Upanishad Shanti Mantra",
    symbol: "lotus",
    tag: "विश्व शांति",
    tagEn: "Universal Peace",
  },
  {
    id: "suprabhat-3",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "सूर्य नमस्कार — नई ऊर्जा का संचार",
    titleEn: "Surya Vandana — Solar Radiance",
    shlokaOrSutra: "ॐ आदित्याय विद्महे मार्तण्डाय धीमहि तन्नः सूर्यः प्रचोदयात्॥",
    shlokaHinglish: "Om Adityaya Vidmahe Martandaya Dheemahi Tannah Suryah Prachodayat.",
    quoteHi: "भगवान भास्कर का दिव्य प्रकाश आपके जीवन से आलस्य, रोग और निराशा को दूर कर नई स्फूर्ति, तेज और उमंग का संचार करे।",
    quoteHinglish: "Surya Dev ka tej aapke jeevan mein nayi urja, arogya aur safalta laye. Shubh Prabhat!",
    quoteEn: "May the divine light of the Sun illuminate your mind, dispel darkness, and bestow health, vitality, and success.",
    sourceHi: "सूर्य गायत्री मंत्र",
    sourceEn: "Surya Gayatri",
    symbol: "sun",
    tag: "सूर्य वंदना",
    tagEn: "Surya Vandana",
  },
  {
    id: "suprabhat-4",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "कृतज्ञता और सकारात्मक सोच",
    titleEn: "Gratitude and Positivity",
    shlokaOrSutra: "सदा संतुष्टः सुखमेधते।",
    shlokaHinglish: "Sada Santushtah Sukham Edhate",
    quoteHi: "जो व्यक्ति जो कुछ उसके पास है उसके लिए ईश्वर को धन्यवाद देता है, उसका जीवन सदैव सुख, शांति और समृद्धि से भरा रहता है।",
    quoteHinglish: "Ishwar ka har saans ke liye dhanyavad karein. Sakaratmak soch se har din sundar banta hai.",
    quoteEn: "Gratitude turns what we have into enough. Begin each morning thanking the Divine for the gift of life.",
    sourceHi: "सनातन सुभाषित",
    sourceEn: "Sanatan Subhashita",
    symbol: "sun",
    tag: "सकारात्मक सोच",
    tagEn: "Gratitude",
  },
  {
    id: "suprabhat-5",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "कर्म ही पूजा है",
    titleEn: "Work is Worship",
    shlokaOrSutra: "उद्यमेन हि सिध्यन्ति कार्याणि न मनोरथैः।",
    shlokaHinglish: "Udyamena Hi Sidhyanti Karyani Na Manorathaih",
    quoteHi: "परिश्रम और ईमानदारी से किए गए कर्म ही सफलता की कुंजी हैं। आज के दिन अपने कर्तव्यों को पूरी निष्ठा से निभाएं।",
    quoteHinglish: "Parishram aur imandari se kiye gaye karya hi safalta dete hain. Aapka din pragatisheel ho.",
    quoteEn: "Achievements come through diligent effort, not mere wishing. Dedicate your day's work as an offering to God.",
    sourceHi: "हितोपदेश",
    sourceEn: "Hitopadesha",
    symbol: "sun",
    tag: "कर्म प्रेरणा",
    tagEn: "Daily Action",
  },

  // ================= 10. FESTIVALS & SPECIAL OCCASIONS =================
  {
    id: "festival-1",
    category: "festivals",
    tradition: "jain",
    titleHi: "महावीर जन्म कल्याणक",
    titleEn: "Mahavir Jayanti Wishes",
    shlokaOrSutra: "जय महावीर, जय जिनेन्द्र। अहिंसा परमो धर्मः॥",
    shlokaHinglish: "Jai Mahavira, Jai Jinendra. Ahimsa Paramo Dharmah.",
    quoteHi: "भगवान महावीर के सत्य, अहिंसा, अपरिग्रह और अनेकांत के पावन संदेश को अपने जीवन में अपनाएं। महावीर जयंती की हार्दिक मंगलकामनाएं!",
    quoteHinglish: "Bhagwan Mahavira ke Satya, Ahimsa aur Prem ke sandesh ko jeevan mein apnayein. Mahavir Jayanti ki mangal kamnayein!",
    quoteEn: "May the divine teachings of Lord Mahavira guide you on the path of truth, non-violence, and inner peace. Happy Mahavir Jayanti!",
    sourceHi: "महावीर जन्म कल्याणक",
    sourceEn: "Mahavir Janma Kalyanak",
    symbol: "ahimsa",
    tag: "महावीर जयंती",
    tagEn: "Mahavir Jayanti",
  },
  {
    id: "festival-2",
    category: "festivals",
    tradition: "hindu",
    titleHi: "दीपावली — प्रकाश और समृद्धि",
    titleEn: "Deepavali Blessings",
    shlokaOrSutra: "तमसो मा ज्योतिर्गमय। मृत्योर्मा अमृतं गमय॥",
    shlokaHinglish: "Tamaso Ma Jyotir Gamaya. Mrityor Ma Amritam Gamaya.",
    quoteHi: "दीयों का यह पावन पर्व आपके जीवन से अंधकार, क्लेश और निराशा को मिटाकर सुख, समृद्धि व आरोग्यता का दीप जलाए। शुभ दीपावली!",
    quoteHinglish: "Deepon ka yeh pavitra parv aapke jeevan mein sukh, samriddhi aur anand ka prakash laye. Shubh Deepavali!",
    quoteEn: "May the divine lights of Deepavali illuminate your path towards endless happiness, peace, and auspicious prosperity.",
    sourceHi: "दीपावली मंगलकामना",
    sourceEn: "Diwali Blessings",
    symbol: "diya",
    tag: "दीपावली",
    tagEn: "Diwali",
  },
  {
    id: "festival-3",
    category: "festivals",
    tradition: "hindu",
    titleHi: "श्री कृष्ण जन्माष्टमी",
    titleEn: "Janmashtami Celebrations",
    shlokaOrSutra: "नन्द के आनंद भयो, जय कन्हैया लाल की। हाथी घोड़ा पालकी, जय कन्हैया लाल की॥",
    shlokaHinglish: "Nand Ke Anand Bhayo, Jai Kanhaiya Lal Ki. Hathi Ghoda Palki, Jai Kanhaiya Lal Ki.",
    quoteHi: "माखनचोर, मुरलीधर भगवान श्री कृष्ण आपके घर-आंगन में प्रेम, उल्लास और मंगलता का वास करें। जन्माष्टमी की हार्दिक शुभकामनाएं!",
    quoteHinglish: "Bhagwan Shri Krishna aapke jeevan ko anand aur prem se bhar dein. Janmashtami ki dheron shubhkaamnayein!",
    quoteEn: "May Lord Krishna fill your life with blissful love, divine wisdom, and joyful serenity. Happy Janmashtami!",
    sourceHi: "जन्माष्टमी उत्सव",
    sourceEn: "Janmashtami Utsav",
    symbol: "flute",
    tag: "जन्माष्टमी",
    tagEn: "Janmashtami",
  },
  {
    id: "festival-4",
    category: "festivals",
    tradition: "hindu",
    titleHi: "महाशिवरात्रि — शिव-शक्ति मिलन",
    titleEn: "Maha Shivratri Blessings",
    shlokaOrSutra: "शिवं शांतं प्रपद्ये।",
    shlokaHinglish: "Shivam Shantam Prapadye",
    quoteHi: "महाशिवरात्रि के इस पावन पर्व पर देवाधिदेव महादेव और माता पार्वती की कृपा से आपके जीवन के सभी कष्ट दूर हों और मनोकामनाएं पूर्ण हों।",
    quoteHinglish: "Maha Shivratri par Bholenath aapke parivar ko sukh, shanti aur arogya pradan karein. Har Har Mahadev!",
    quoteEn: "On this sacred night of Maha Shivratri, may Lord Shiva and Mother Parvati bless your family with spiritual bliss and health.",
    sourceHi: "महाशिवरात्रि पर्व",
    sourceEn: "Maha Shivratri",
    symbol: "trishul",
    tag: "महाशिवरात्रि",
    tagEn: "Maha Shivratri",
  },
  {
    id: "festival-5",
    category: "festivals",
    tradition: "hindu",
    titleHi: "श्री राम नवमी",
    titleEn: "Ram Navami Wishes",
    shlokaOrSutra: "भए प्रगट कृपाला दीनदयाला कौसल्या हितकारी। हरषित महतारी मुनि मन हारी अद्भुत रूप बिचारी॥",
    shlokaHinglish: "Bhaye Pragata Kripala Deena-Dayala Kausalya Hitkari.",
    quoteHi: "मर्यादा पुरुषोत्तम भगवान श्री राम के जन्मोत्सव पर आपके घर में सुख, शांति, धर्म और समृद्धि का वास हो। राम नवमी की शुभकामनाएं!",
    quoteHinglish: "Prabhu Shri Ram ka aashirwad sada aapke sath rahe. Ram Navami ki mangal kamnayein!",
    quoteEn: "May the birth of Lord Rama inspire truth, courage, and righteousness in every step of your journey. Happy Ram Navami!",
    sourceHi: "राम जन्मोत्सव स्तुति",
    sourceEn: "Ram Janmotsav Stuti",
    symbol: "bow",
    tag: "राम नवमी",
    tagEn: "Ram Navami",
  },
  {
    id: "festival-6",
    category: "festivals",
    tradition: "jain",
    titleHi: "पर्युषण महापर्व — आत्म शुद्धि",
    titleEn: "Paryushan Mahaparva",
    shlokaOrSutra: "उत्तम क्षमा, मार्दव, आर्जव, सत्य, शौच, संयम, तप, त्याग, आकिंचन्य, ब्रह्मचर्य।",
    shlokaHinglish: "Uttama Kshama, Mardava, Aarjava, Satya, Shaucha, Sanyama, Tapa, Tyaga, Akinchanya, Brahmacharya.",
    quoteHi: "दशलक्षण पर्युषण पर्व पर अपनी आत्मा को दस धर्मों से अलंकृत करें। क्षमा भाव और संयम ही जीवन का सच्चा आभूषण है।",
    quoteHinglish: "Paryushan parva par aatma shuddhi aur kshama bhav ko apnayein. Jai Jinendra!",
    quoteEn: "During sacred Paryushan, adorn the soul with supreme forgiveness, humility, and truth. Seek forgiveness from all.",
    sourceHi: "दशलक्षण धर्म",
    sourceEn: "Dashalakshana Dharma",
    symbol: "ahimsa",
    tag: "पर्युषण पर्व",
    tagEn: "Paryushan",
  },
  {
    id: "festival-7",
    category: "festivals",
    tradition: "hindu",
    titleHi: "शारदीय / चैत्र नवरात्रि",
    titleEn: "Navratri Blessings",
    shlokaOrSutra: "जयन्ती मङ्गला काली भद्रकाली कपालिनी। दुर्गा क्षमा शिवा धात्री स्वाहा स्वधा नमोऽस्तु ते॥",
    shlokaHinglish: "Jayanti Mangala Kaali Bhadrakaali Kapalini. Durga Kshama Shiva Dhatri Swaha Swadha Namo'stu Te.",
    quoteHi: "माँ दुर्गा के नौ दिव्य स्वरूप आपके जीवन में शक्ति, साहस, सकारात्मक ऊर्जा और विजय का संचार करें। शुभ नवरात्रि!",
    quoteHinglish: "Maa Durga aapke jeevan ke sabhi sankaton ko door kar vijay pradan karein. Shubh Navratri!",
    quoteEn: "May the nine forms of Mother Durga bless you with strength, wisdom, and victory over all challenges. Happy Navratri!",
    sourceHi: "दुर्गा स्तुति",
    sourceEn: "Durga Stuti",
    symbol: "lotus",
    tag: "नवरात्रि",
    tagEn: "Navratri",
  },
  {
    id: "festival-8",
    category: "festivals",
    tradition: "hindu",
    titleHi: "गणेश चतुर्थी — बप्पा का आगमन",
    titleEn: "Ganesh Chaturthi Wishes",
    shlokaOrSutra: "गणपति बाप्पा मोरया, मंगल मूर्ति मोरया!",
    shlokaHinglish: "Ganpati Bappa Morya, Mangal Murti Morya!",
    quoteHi: "विघ्नहर्ता श्री गणेश आपके घर में सुख, शांति, समृद्धि और खुशियों का वास करें। गणेश चतुर्थी की हार्दिक शुभकामनाएं!",
    quoteHinglish: "Bappa aapke sabhi vighnon ko door kar khushiyan layein. Ganesh Chaturthi ki hardik shubhkamnayein!",
    quoteEn: "May Lord Ganesha shower your family with joy, peace, success, and prosperity. Happy Ganesh Chaturthi!",
    sourceHi: "गणेश उत्सव",
    sourceEn: "Ganesh Utsav",
    symbol: "swastik",
    tag: "गणेश चतुर्थी",
    tagEn: "Ganesh Chaturthi",
  },
  {
    id: "festival-9",
    category: "festivals",
    tradition: "universal",
    titleHi: "गुरु पूर्णिमा — कृतज्ञता और नमन",
    titleEn: "Guru Purnima — Gratitude to the Teacher",
    shlokaOrSutra: "गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः। गुरुः साक्षात् परं ब्रह्म तस्मै श्रीगुरवे नमः॥",
    shlokaHinglish: "Gurur Brahma Gurur Vishnuh Gurur Devo Maheshwarah. Guruh Sakshat Param Brahma Tasmai Shri Gurave Namah.",
    quoteHi: "जीवन में अज्ञान का अंधकार मिटाकर ज्ञान का प्रकाश देने वाले सभी गुरुजनों को कोटि-कोटि नमन। गुरु पूर्णिमा की शुभकामनाएं!",
    quoteHinglish: "Gyan aur satya ka marg dikhane wale sabhi Gurujanon ko koti naman. Shubh Guru Purnima!",
    quoteEn: "Salutations to the Guru who removes the darkness of ignorance and lights the lamp of wisdom. Happy Guru Purnima!",
    sourceHi: "गुरु गीता",
    sourceEn: "Guru Gita",
    symbol: "diya",
    tag: "गुरु पूर्णिमा",
    tagEn: "Guru Purnima",
  },
  {
    id: "festival-10",
    category: "festivals",
    tradition: "hindu",
    titleHi: "मकर संक्रांति — सूर्य का उत्तरायण",
    titleEn: "Makar Sankranti Blessings",
    shlokaOrSutra: "भास्करस्य प्रभा दिव्ये सर्वपापप्रणाशिनी।",
    shlokaHinglish: "Bhaskarasya Prabha Divye Sarva-Papa-Pranashini",
    quoteHi: "सूर्य देव का उत्तरायण आपके जीवन में नई ऊर्जा, मिठास, उमंग और खुशहाली का प्रकाश फैलाए। मकर संक्रांति की शुभकामनाएं!",
    quoteHinglish: "Makar Sankranti aapke jeevan mein nayi aasha aur anand laye. Shubh Makar Sankranti!",
    quoteEn: "May the auspicious transition of the Sun bring boundless happiness, health, and bright opportunities. Happy Makar Sankranti!",
    sourceHi: "संक्रांति पर्व",
    sourceEn: "Sankranti Festival",
    symbol: "sun",
    tag: "मकर संक्रांति",
    tagEn: "Makar Sankranti",
  },
  {
    id: "festival-11",
    category: "festivals",
    tradition: "hindu",
    titleHi: "हनुमान जयंती — असीम बल व भक्ति",
    titleEn: "Hanuman Jayanti Wishes",
    shlokaOrSutra: "अंजनी गर्भ सम्भूतो कपीन्द्रः पावनसुतः।",
    shlokaHinglish: "Anjani Garbha Sambhuto Kapindrah Pavanasutah",
    quoteHi: "पवनपुत्र वीर हनुमान जी के जन्मोत्सव पर आपके जीवन से सभी रोग, कष्ट, भय और संकट दूर हों। हनुमान जयंती की शुभकामनाएं!",
    quoteHinglish: "Hanuman Jayanti par Bajrangbali aapko bal, buddhi aur arogya pradan karein. Jai Shri Ram!",
    quoteEn: "May Lord Hanuman bless you with immense courage, radiant health, wisdom, and selfless devotion. Happy Hanuman Jayanti!",
    sourceHi: "हनुमान जन्मोत्सव",
    sourceEn: "Hanuman Jayanti",
    symbol: "gada",
    tag: "हनुमान जयंती",
    tagEn: "Hanuman Jayanti",
  },
  {
    id: "festival-12",
    category: "festivals",
    tradition: "hindu",
    titleHi: "रक्षाबंधन — स्नेह और विश्वास का बंधन",
    titleEn: "Raksha Bandhan Wishes",
    shlokaOrSutra: "येन बद्धो बली राजा दानवेन्द्रो महाबलः। तेन त्वामनुबध्नामि रक्षे मा चल मा चल॥",
    shlokaHinglish: "Yena Baddho Balee Raja Danavendro Mahabalah. Tena Tvam Anubadhnami Rakshe Ma Chala Ma Chala.",
    quoteHi: "भाई-बहन के अटूट प्रेम, विश्वास और रक्षा के पावन पर्व रक्षाबंधन की आप सभी को हार्दिक शुभकामनाएं!",
    quoteHinglish: "Bhai-behan ke pavitra prem aur sneh ke parv Raksha Bandhan ki hardik shubhkamnayein!",
    quoteEn: "May the sacred thread of Rakhi protect and strengthen the eternal bond of love, care, and family harmony.",
    sourceHi: "रक्षा सूत्र स्तुति",
    sourceEn: "Raksha Sutra",
    symbol: "lotus",
    tag: "रक्षाबंधन",
    tagEn: "Raksha Bandhan",
  },
  {
    id: "festival-13",
    category: "festivals",
    tradition: "hindu",
    titleHi: "होली — प्रेम, सद्भाव और भक्ति का रंग",
    titleEn: "Holi & Holika Dahan",
    shlokaOrSutra: "आनन्दो वर्धते नित्यं भक्तानां हृदये सदा।",
    shlokaHinglish: "Anando Vardhate Nityam Bhaktanam Hridaye Sada",
    quoteHi: "भक्त प्रह्लाद की अटूट आस्था का यह पर्व आपके जीवन से बुराई और क्लेश को मिटाकर प्रेम, सुख और सौहार्द के रंग घोले।",
    quoteHinglish: "Holi ka pavitra tyohar aapke jeevan ko anand, prem aur khushiyon ke rang se bhar de. Shubh Holi!",
    quoteEn: "May the joyous festival of colors wash away all negativity and fill your heart with vibrant love, peace, and spiritual bliss.",
    sourceHi: "होली उत्सव",
    sourceEn: "Holi Festival",
    symbol: "lotus",
    tag: "होली",
    tagEn: "Holi",
  },
  {
    id: "festival-14",
    category: "festivals",
    tradition: "hindu",
    titleHi: "अक्षय तृतीया — शाश्वत पुण्य और समृद्धि",
    titleEn: "Akshaya Tritiya Blessings",
    shlokaOrSutra: "अक्षयं सर्वदा पुण्यं दानेन च जपेन च।",
    shlokaHinglish: "Akshayam Sarvada Punyam Danena Cha Japena Cha",
    quoteHi: "इस पावन दिन किया गया दान, जप और सत्कर्म कभी क्षय नहीं होता। अक्षय तृतीया आपके घर में अनंत सुख-समृद्धि लाए।",
    quoteHinglish: "Akshaya Tritiya par kiya gaya daan aur naam jaap anant guna fal deta hai. Shubh Akshaya Tritiya!",
    quoteEn: "May this auspicious day of Akshaya Tritiya bless you with unending prosperity, good fortune, and spiritual merit.",
    sourceHi: "अक्षय तृतीया महिमा",
    sourceEn: "Akshaya Tritiya",
    symbol: "diya",
    tag: "अक्षय तृतीया",
    tagEn: "Akshaya Tritiya",
  },
  {
    id: "festival-15",
    category: "festivals",
    tradition: "hindu",
    titleHi: "धनतेरस — आरोग्य और समृद्धि",
    titleEn: "Dhanteras & Ayurveda Blessings",
    shlokaOrSutra: "नमामि धन्वन्तरिमादिदेवं सुरासुरैर्वन्दितपादपद्मम्।",
    shlokaHinglish: "Namami Dhanvantarim Aadi-Devam Sura-Surair Vandita-Pada-Padmam",
    quoteHi: "आरोग्य के देवता भगवान धन्वंतरि और माँ लक्ष्मी आपके परिवार को उत्तम स्वास्थ्य, दीर्घायु और सुख-समृद्धि प्रदान करें।",
    quoteHinglish: "Bhagwan Dhanvantari aur Maa Lakshmi aapko uttam swasthya aur samriddhi dein. Shubh Dhanteras!",
    quoteEn: "May Lord Dhanvantari and Goddess Lakshmi bless your home with vibrant health, longevity, and auspicious prosperity.",
    sourceHi: "धन्वंतरि वंदना",
    sourceEn: "Dhanvantari Vandana",
    symbol: "diya",
    tag: "धनतेरस",
    tagEn: "Dhanteras",
  },

  // --- ADDITIONAL JAIN DHARMA GEMS ---
  {
    id: "jain-14",
    category: "jain",
    tradition: "jain",
    titleHi: "सामायिक — समता भाव की साधना",
    titleEn: "Samayika — The Art of Equanimity",
    shlokaOrSutra: "करेमि भंते सामाइयं, सावज्जं जोगं पच्चक्खामि।",
    shlokaHinglish: "Karemi Bhante Samayikam, Savajjam Jogam Pachhakkhani",
    quoteHi: "सामायिक का अर्थ है राग और द्वेष को छोड़कर मन को समता में स्थित करना। समता में ही आत्मा का वास्तविक स्वरूप प्रकट होता है।",
    quoteHinglish: "Rag aur dwesh ko chhodkar man ko shanti aur samata mein sthir karna hi aatma ka sachha anand hai.",
    quoteEn: "Samayika means shedding attachment and aversion to dwell in pure equanimity. In calmness lies the soul's true nature.",
    sourceHi: "जैन सामायिक सूत्र",
    sourceEn: "Jain Samayika Sutra",
    symbol: "ahimsa",
    tag: "सामायिक",
    tagEn: "Equanimity",
  },
  {
    id: "jain-15",
    category: "jain",
    tradition: "jain",
    titleHi: "तपस्या — कर्मों की निर्जरा",
    titleEn: "Tapasya — Purifying Past Karma",
    shlokaOrSutra: "इच्छा निरोधस्तपः।",
    shlokaHinglish: "Ichha Nirodhas Tapah",
    quoteHi: "अनावश्यक इच्छाओं और वासनाओं पर नियंत्रण पाना ही सच्ची तपस्या है। तप से आत्मा के पुरातन कर्म कटते हैं और तेज बढ़ता है।",
    quoteHinglish: "Ichhaon par niyantran pana hi shreshth tapasya hai. Tap se aatma pavitra aur nirmal hoti hai.",
    quoteEn: "Restraining unworthy desires is true penance. Spiritual discipline burns past karmas and illuminates the soul.",
    sourceHi: "तत्वार्थ सूत्र",
    sourceEn: "Tattvartha Sutra",
    symbol: "diya",
    tag: "तपस्या",
    tagEn: "Spiritual Penance",
  },
  {
    id: "jain-16",
    category: "jain",
    tradition: "jain",
    titleHi: "भगवान पार्श्वनाथ — क्षमा की पराकाष्ठा",
    titleEn: "Bhagwan Parshvanath — Supreme Forgiveness",
    shlokaOrSutra: "कमठोपसर्गविजेता श्री पार्श्वनाथाय नमः।",
    shlokaHinglish: "Kamathopasarga-Vijeta Shri Parshwanathaya Namah",
    quoteHi: "कमठ द्वारा घोर उपसर्ग किए जाने पर भी भगवान पार्श्वनाथ के मन में किंचित भी क्रोध नहीं आया। शत्रु पर भी करुणा रखना ही प्रभु की शिक्षा है।",
    quoteHinglish: "Shatru ke prati bhi man mein dvesh na rakhna aur kshama bhaav banaye rakhna hi Bhagwan Parshvanath ka aadarsh hai.",
    quoteEn: "Even when tormented, Lord Parshvanath felt no anger, only pure compassion. Forgiving those who wrong us is supreme virtue.",
    sourceHi: "पार्श्वनाथ चरित्र",
    sourceEn: "Parshvanath Charitra",
    symbol: "ahimsa",
    tag: "पार्श्वनाथ भगवान",
    tagEn: "Lord Parshvanath",
  },
  {
    id: "jain-17",
    category: "jain",
    tradition: "jain",
    titleHi: "मैत्री भावना — सब जीवों से प्रेम",
    titleEn: "Maitri Bhavana — Universal Friendship",
    shlokaOrSutra: "मैत्री भाव नुं पवित्र झरणुं मुझ हैयामां वह्या करे।",
    shlokaHinglish: "Maitri Bhaav Nu Pavitra Jharanu Mujh Haiyama Vahya Kare",
    quoteHi: "मेरे हृदय में संसार के सभी प्राणियों के प्रति प्रेम और मित्रता का पावन झरना सदैव बहता रहे। किसी के प्रति ईर्ष्या न रहे।",
    quoteHinglish: "Sansar ke har jeev ke prati mere hriday mein sneh aur maitri ka bhav nitya bana rahe.",
    quoteEn: "May the pure spring of universal friendship flow ceaselessly in my heart towards every living being.",
    sourceHi: "जैन मैत्री भावना",
    sourceEn: "Maitri Bhavana Prayer",
    symbol: "lotus",
    tag: "मैत्री भावना",
    tagEn: "Universal Friendship",
  },

  // --- ADDITIONAL KRISHNA & GITA GEMS ---
  {
    id: "krishna-13",
    category: "krishna",
    tradition: "hindu",
    titleHi: "महामंत्र — हरे कृष्ण हरे राम",
    titleEn: "The Maha Mantra",
    shlokaOrSutra: "हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे॥",
    shlokaHinglish: "Hare Krishna Hare Krishna Krishna Krishna Hare Hare. Hare Rama Hare Rama Rama Rama Hare Hare.",
    quoteHi: "यह कलयुग का तारक महामंत्र समस्त कलुष, चिंता और भयों को मिटाकर हृदय में दिव्य प्रेम और शांति का प्राकट्य करता है।",
    quoteHinglish: "Hare Krishna Mahamantra ka jaap aatma ko anand aur Parmatma se jodta hai. Nitya prem se jap karein.",
    quoteEn: "This supreme Mahamantra cleanses the mirror of the heart, extinguishing all worldly anxieties and awakening divine love.",
    sourceHi: "कलिसंतरण उपनिषद्",
    sourceEn: "Kali Santarana Upanishad",
    symbol: "flute",
    tag: "महामंत्र",
    tagEn: "Maha Mantra",
  },
  {
    id: "krishna-14",
    category: "krishna",
    tradition: "hindu",
    titleHi: "सच्चा मित्र और निस्वार्थ प्रेम",
    titleEn: "True Friendship — Krishna & Sudama",
    shlokaOrSutra: "सुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति।",
    shlokaHinglish: "Suhridam Sarva-Bhutanam Jnatva Mam Shantim Ricchati",
    quoteHi: "श्री कृष्ण कहते हैं: मैं सभी प्राणियों का निस्वार्थ परम हितैषी और मित्र हूँ। जब प्रभु ही हमारे मित्र हैं, तो जीवन में अकेलापन कैसा?",
    quoteHinglish: "Bhagwan Shri Krishna sabhi ke sachhe sakha hain. Prabhu par poora vishwas rakhein.",
    quoteEn: "Knowing Me as the selfless benefactor and friend of all living beings, the seeker attains everlasting peace.",
    sourceHi: "श्रीमद्भगवद्गीता (अध्याय 5, श्लोक 29)",
    sourceEn: "Bhagavad Gita (5.29)",
    symbol: "flute",
    tag: "सच्चा सखा",
    tagEn: "Supreme Friend",
  },
  {
    id: "krishna-15",
    category: "krishna",
    tradition: "hindu",
    titleHi: "सत्यं परं धीमहि — भागवत संदेश",
    titleEn: "Meditating on Supreme Truth",
    shlokaOrSutra: "जन्माद्यस्य यतोऽन्वयादितरतश्चार्थेष्वभिज्ञः स्वराट्... सत्यं परं धीमहि॥",
    shlokaHinglish: "Janmady Asya Yato'nvayad Itaratash Chartheshv Abhijnah Swarat... Satyam Param Dheemahi.",
    quoteHi: "हम उस परम सत्य स्वरूप भगवान श्री कृष्ण का ध्यान करते हैं, जिनसे इस संपूर्ण ब्रह्मांड का सृजन, पालन और लय होता है।",
    quoteHinglish: "Hum us Param Satya Shri Krishna ka dhyan karte hain jo prem aur anand ke sagar hain.",
    quoteEn: "We meditate upon the Absolute Truth, Lord Krishna, the primordial source and eternal light of all existence.",
    sourceHi: "श्रीमद्भागवत महापुराण",
    sourceEn: "Srimad Bhagavatam (1.1.1)",
    symbol: "flute",
    tag: "भागवत ज्ञान",
    tagEn: "Bhagavata Wisdom",
  },

  // --- ADDITIONAL MAHADEV GEMS ---
  {
    id: "mahadev-8",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "रुद्राष्टकम — नमामीशमीशान",
    titleEn: "Rudrashtakam — Lord of Peace",
    shlokaOrSutra: "नमामीशमीशान निर्वाणरूपं विभुं व्यापकं ब्रह्मवेदस्वरूपम्। निजं निर्गुणं निर्विकल्पं निरीहं चिदाकाशमाकाशवासं भजेऽहम्॥",
    shlokaHinglish: "Namamishamishana Nirvana-Rupam Vibhum Vyapakam Brahma-Veda-Swaroopam.",
    quoteHi: "मैं ईशान दिशा के स्वामी, मोक्ष स्वरूप, सर्वव्यापी, निर्विकल्प और ज्ञान रूप भगवान शिव की स्तुति और वंदना करता हूँ।",
    quoteHinglish: "Sarvavyapi aur shant swaroop Mahadev ki sharan lene se man ke sabhi vikar door ho jaate hain.",
    quoteEn: "I adore Lord Shiva, the embodiment of liberation, all-pervading, beyond all duality, and serene as the infinite sky.",
    sourceHi: "श्री रुद्राष्टकम (गोस्वामी तुलसीदास)",
    sourceEn: "Rudrashtakam",
    symbol: "trishul",
    tag: "रुद्राष्टकम",
    tagEn: "Rudrashtakam",
  },
  {
    id: "mahadev-9",
    category: "mahadev",
    tradition: "hindu",
    titleHi: "लिंगाष्टकम — ब्रह्ममुरारि सुरार्चित",
    titleEn: "Lingashtakam — Worship of Shiva",
    shlokaOrSutra: "ब्रह्ममुरारिसुरार्चितलिङ्गं निर्मलभासितशोभितलिङ्गम्। जन्मजदुःखविनाशकलिङ्गं तत् प्रणमामि सदाशिवलिङ्गम्॥",
    shlokaHinglish: "Brahma-Murari-Surarchita-Lingam Nirmala-Bhasita-Shobhita-Lingam.",
    quoteHi: "ब्रह्मा और विष्णु द्वारा पूजित, समस्त जन्म-जन्मांतर के दुःखों का नाश करने वाले सदाशिव के पावन शिवलिंग को हम प्रणाम करते हैं।",
    quoteHinglish: "Dukhon ka nash karne wale aur shanti dene wale Sadashiv ke charnon mein naman.",
    quoteEn: "I bow before the sacred Shiva Lingam, worshipped by Brahma and Vishnu, the destroyer of all worldly sorrows.",
    sourceHi: "लिंगाष्टकम स्तोत्र",
    sourceEn: "Lingashtakam Stotram",
    symbol: "trishul",
    tag: "लिंगाष्टकम",
    tagEn: "Lingashtakam",
  },

  // --- ADDITIONAL HANUMAN GEMS ---
  {
    id: "hanuman-7",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "बजरंग बाण — अटूट विश्वास",
    titleEn: "Bajrang Baan — Unshakable Faith",
    shlokaOrSutra: "निश्चय प्रेम प्रतीति ते, बिनय करैं सनमान। तेहि के कारज सकल शुभ, सिद्ध करैं हनुमान॥",
    shlokaHinglish: "Nishchaya Prem Prateeti Te, Binay Karain Sanman. Tehi Ke Kaaraj Sakal Shubh, Siddh Karain Hanuman.",
    quoteHi: "जो पूर्ण प्रेम, विश्वास और श्रद्धा से हनुमान जी की प्रार्थना करता है, उसके सभी शुभ कार्य हनुमान जी स्वतः सिद्ध कर देते हैं।",
    quoteHinglish: "Pura vishwas aur shraddha rakhne wale bhakton ke sabhi sankat Hanuman Ji pal bhar mein door karte hain.",
    quoteEn: "Whoever approaches Hanuman with sincere love and unswerving faith finds all noble endeavors crowned with success.",
    sourceHi: "श्री बजरंग बाण",
    sourceEn: "Bajrang Baan",
    symbol: "gada",
    tag: "बजरंग बाण",
    tagEn: "Bajrang Baan",
  },
  {
    id: "hanuman-8",
    category: "hanuman",
    tradition: "hindu",
    titleHi: "अष्ट सिद्धि नव निधि के दाता",
    titleEn: "Master of All Eight Siddhis",
    shlokaOrSutra: "अष्ट सिद्धि नौ निधि के दाता। अस बर दीन जानकी माता॥",
    shlokaHinglish: "Ashta Siddhi Nau Nidhi Ke Data. Asa Bara Deen Janaki Mata.",
    quoteHi: "माता जानकी के वरदान से हनुमान जी अष्ट सिद्धियों और नौ निधियों के दाता हैं। वे अपने भक्तों को शक्ति, बुद्धि और समृद्धि देते हैं।",
    quoteHinglish: "Mata Sita ke aashirwad se Hanuman Ji sabhi sadhanaon aur riddhi-siddhiyon ke data hain.",
    quoteEn: "Blessed by Mother Sita, Hanuman is the gracious giver of all eight mystical powers and nine treasures of life.",
    sourceHi: "श्री हनुमान चालीसा",
    sourceEn: "Hanuman Chalisa",
    symbol: "gada",
    tag: "अष्ट सिद्धि",
    tagEn: "Eight Siddhis",
  },

  // --- ADDITIONAL RAM GEMS ---
  {
    id: "ram-7",
    category: "ram",
    tradition: "hindu",
    titleHi: "तुलसी मीठे बचन ते — सुख उपजत चहुँ ओर",
    titleEn: "Sweet Words Bring Harmony",
    shlokaOrSutra: "तुलसी मीठे बचन ते सुख उपजत चहुँ ओर। बसीकरन इक मंत्र है परिहरू बचन कठोर॥",
    shlokaHinglish: "Tulsi Meethe Bachan Te Sukh Upajat Chahun Oar. Baseekaran Ik Mantra Hai Pariharu Bachan Kathor.",
    quoteHi: "मीठे और प्रेमपूर्ण वचनों से चारों ओर सुख और सौहार्द फैलता है। कठोर वचनों को त्याग देना ही सबको अपना बनाने का सबसे बड़ा मंत्र है।",
    quoteHinglish: "Meethi vani bolne se sabhi ke dil jeete ja sakte hain. Kathor shabdon se bachein.",
    quoteEn: "Sweet speech radiates joy everywhere and wins every heart. Renounce harsh words and embrace gentle kindness.",
    sourceHi: "गोस्वामी तुलसीदास दोहावली",
    sourceEn: "Tulsidas Dohavali",
    symbol: "bow",
    tag: "तुलसी दोहा",
    tagEn: "Tulsidas Doha",
  },
  {
    id: "ram-8",
    category: "ram",
    tradition: "hindu",
    titleHi: "मंगल भवन अमंगल हारी",
    titleEn: "Mangal Bhavan Amangal Hari",
    shlokaOrSutra: "मंगल भवन अमंगल हारी। द्रवहु सुदसरथ अजिर बिहारी॥",
    shlokaHinglish: "Mangal Bhavan Amangal Hari. Dravahu Su-Dasaratha Ajira Bihari.",
    quoteHi: "कल्याण के धाम और समस्त अमंगल को हरने वाले भगवान श्री राम हमारे अंतःकरण के सभी क्लेशों को दूर कर जीवन में शुभता लाएं।",
    quoteHinglish: "Prabhu Shri Ram sabhi dukhon ko door kar hamare ghar aur man mein mangal aur shanti layein.",
    quoteEn: "May Lord Rama, the abode of all auspiciousness and dispeller of misfortune, grace our hearts with everlasting peace.",
    sourceHi: "श्रीरामचरितमानस",
    sourceEn: "Ramcharitmanas",
    symbol: "bow",
    tag: "मंगल भवन",
    tagEn: "Mangal Bhavan",
  },

  // --- ADDITIONAL DEVI GEMS ---
  {
    id: "devi-7",
    category: "devi",
    tradition: "hindu",
    titleHi: "माँ सिद्धिदात्री — समस्त सिद्धियों की प्रदाता",
    titleEn: "Maa Siddhidatri — Bestower of Siddhis",
    shlokaOrSutra: "सिद्धगन्धर्वयक्षाद्यैरसुरैरमरैरपि। सेव्यमाना सदा भूयात् सिद्धिदा सिद्धिदायिनी॥",
    shlokaHinglish: "Siddha-Gandharva-Yakshadyair Asurair Amarair Api. Sevyamana Sada Bhuyat Siddhida Siddhi-Dayini.",
    quoteHi: "माँ सिद्धिदात्री साधक को समस्त लौकिक और अलौकिक सिद्धियों, आत्मज्ञान और अंतर्मन की शांति का आशीर्वाद प्रदान करती हैं।",
    quoteHinglish: "Maa Siddhidatri aapke jeevan mein sabhi karyon ko safal banayein aur aatma gyan dein.",
    quoteEn: "May Mother Siddhidatri grant you supreme spiritual realization, inner clarity, and grand success in all noble pursuits.",
    sourceHi: "नवदुर्गा स्तोत्र",
    sourceEn: "Navadurga Stotram",
    symbol: "lotus",
    tag: "सिद्धिदात्री",
    tagEn: "Siddhidatri",
  },

  // --- ADDITIONAL GANESH GEMS ---
  {
    id: "ganesh-5",
    category: "ganesh",
    tradition: "hindu",
    titleHi: "गणपति अथर्वशीर्ष — त्वमेव प्रत्यक्षं तत्त्वमसि",
    titleEn: "Ganpati Atharvashirsha — Supreme Truth",
    shlokaOrSutra: "नमस्ते गणपतये। त्वमेव प्रत्यक्षं तत्त्वमसि। त्वमेव केवलं कर्ताऽसि। त्वमेव केवलं धर्ताऽसि॥",
    shlokaHinglish: "Namaste Ganapataye. Tvam Eva Pratyaksham Tattvam Asi. Tvam Eva Kevalam Karta'si.",
    quoteHi: "हे गणेश! आप ही साक्षात परब्रह्म तत्त्व हैं, आप ही संपूर्ण सृष्टि के कर्ता, धर्ता और पोषक हैं। हम आपको नमन करते हैं।",
    quoteHinglish: "Ganpati Bappa hi samast shrishti ke aadhar hain. Unki kripa se har mushkil aasan hoti hai.",
    quoteEn: "O Lord Ganesha, You alone are the visible Supreme Reality, the creator, maintainer, and protector of all cosmos.",
    sourceHi: "गणपति अथर्वशीर्ष",
    sourceEn: "Ganapati Atharvashirsha",
    symbol: "swastik",
    tag: "अथर्वशीर्ष",
    tagEn: "Atharvashirsha",
  },

  // --- ADDITIONAL SANT VANI GEMS ---
  {
    id: "sant-7",
    category: "sant",
    tradition: "universal",
    titleHi: "संत तुकाराम — दीन-दुखियों की सेवा",
    titleEn: "Sant Tukaram — Service to the Needy",
    shlokaOrSutra: "जे का रंजले गांजले, त्यांसी म्हणे जो आपुले। तोचि साधू ओळखावा, देव तेथेंचि जाणावा॥",
    shlokaHinglish: "Je Ka Ranjale Ganjale, Tyansi Mhane Jo Aapule. Tochi Sadhu Olakhava, Dev Tethechi Janava.",
    quoteHi: "जो पीड़ित और असहाय लोगों को अपना समझकर गले लगाता है, वही सच्चा संत है और वहीं साक्षात ईश्वर का वास होता है।",
    quoteHinglish: "Dukhion aur zarooratmand logon ki nishkam seva karna hi Ishwar ki sachhi pooja hai.",
    quoteEn: "Recognize that person as a true saint who embraces the suffering and downtrodden as their own; God dwells right there.",
    sourceHi: "संत तुकाराम अभंग",
    sourceEn: "Sant Tukaram Abhang",
    symbol: "lotus",
    tag: "तुकाराम अभंग",
    tagEn: "Tukaram Abhang",
  },
  {
    id: "sant-8",
    category: "sant",
    tradition: "universal",
    titleHi: "संत ज्ञानेश्वर — पसायदान (विश्व कल्याण)",
    titleEn: "Sant Dnyaneshwar — Universal Prayer (Pasaydan)",
    shlokaOrSutra: "आतां विश्वात्मकें देवें। येणें वाग्यज्ञें तोषावें। तोषोनि मज द्यावें। पसायदान हें॥",
    shlokaHinglish: "Aata Vishwatmake Devem, Yene Vagyajne Toshavem, Toshoni Maja Dyavem, Pasayadana Hem.",
    quoteHi: "दुष्टों की दुर्बुद्धि मिटे, सभी में सत्कर्मों के प्रति प्रेम जागे और संपूर्ण विश्व में परस्पर मैत्री व सुख का विस्तार हो।",
    quoteHinglish: "Sabhi ke dilon mein prem aur bhalai ka bhav jage. Poora vishwa shanti aur anand se bhar jaye.",
    quoteEn: "May evil thoughts vanish from the world, may righteousness flourish, and may all living beings dwell in mutual love.",
    sourceHi: "संत ज्ञानेश्वर (ज्ञानेश्वरी - पसायदान)",
    sourceEn: "Sant Dnyaneshwar (Pasaydan)",
    symbol: "lotus",
    tag: "पसायदान",
    tagEn: "Pasaydan",
  },
  {
    id: "sant-9",
    category: "sant",
    tradition: "universal",
    titleHi: "संत कबीर — सरलता और अहंकार मुक्ति",
    titleEn: "Sant Kabir — Humility and Pure Soul",
    shlokaOrSutra: "माटी कहे कुम्हार से, तू क्या रौंदे मोय। एक दिन ऐसा आएगा, मैं रौंदूंगी तोय॥",
    shlokaHinglish: "Maati Kahe Kumhar Se, Tu Kya Raunde Moy. Ek Din Aisa Aayega, Main Raundoongi Toy.",
    quoteHi: "जीवन नश्वर है, धन और रूप का कभी अहंकार मत करो। विनम्रता, करुणा और प्रभु भक्ति ही जीवन की सच्ची पूंजी हैं।",
    quoteHinglish: "Ahankar ko chhodkar sada vinamra rahein. Sachhi bhakti aur nishkapat hriday hi shreshth hai.",
    quoteEn: "Life is ephemeral. Shed pride of wealth and form; humility, kindness, and devotion are your only enduring treasures.",
    sourceHi: "संत कबीर दोहा",
    sourceEn: "Sant Kabir",
    symbol: "diya",
    tag: "कबीर साखी",
    tagEn: "Kabir Wisdom",
  },
  {
    id: "sant-10",
    category: "sant",
    tradition: "universal",
    titleHi: "रहीम के दोहे — संगति का प्रभाव",
    titleEn: "Rahim — Power of Noble Company",
    shlokaOrSutra: "जो रहीम उत्तम प्रकृति, का करि सकत कुसंग। चन्दन विष व्यापत नहीं, लपटे रहत भुजंग॥",
    shlokaHinglish: "Jo Rahim Uttam Prakriti, Ka Kari Sakat Kusang. Chandan Vish Vyapat Nahin, Lapate Rahat Bhujang.",
    quoteHi: "जिस व्यक्ति का चरित्र और संस्कार उत्तम होते हैं, बुरी संगति भी उसका कुछ नहीं बिगाड़ सकती; जैसे चंदन के पेड़ पर सर्प लिपटे रहने पर भी विष नहीं चढ़ता।",
    quoteHinglish: "Apne charitra aur sanskaron ko dridh rakhein. Sadbhav aur pavitrata hi sachha bal hai.",
    quoteEn: "One of noble character remains untainted even in corrupt surroundings, just as sandalwood stays fragrant despite serpents.",
    sourceHi: "रहीम दोहावली",
    sourceEn: "Rahim Dohavali",
    symbol: "lotus",
    tag: "रहीम दोहा",
    tagEn: "Rahim Wisdom",
  },

  // --- ADDITIONAL SUPRABHAT GEMS ---
  {
    id: "suprabhat-6",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "शुभ प्रभात — नया दिन, नई ऊर्जा",
    titleEn: "New Day, Divine Blessings",
    shlokaOrSutra: "प्रभाते करदर्शनम्।",
    shlokaHinglish: "Prabhate Kara-Darshanam",
    quoteHi: "हर नया दिन परमात्मा द्वारा लिखा गया एक नया पृष्ठ है। इसे कृतज्ञता, प्रेम, उत्साह और शुभ विचारों से भरें। आपका दिन मंगलमय हो!",
    quoteHinglish: "Har naya din Prabhu ka anmol vardaan hai. Ise muskaan, aasha aur prem ke sath jiyein. Shubh Prabhat!",
    quoteEn: "Every morning is a fresh canvas gifted by the Divine. Paint it with kindness, gratitude, and joy. Have a blessed day!",
    sourceHi: "दैनिक सुविचार",
    sourceEn: "Daily Morning Inspiration",
    symbol: "sun",
    tag: "शुभ प्रभात",
    tagEn: "Good Morning",
  },
  {
    id: "suprabhat-7",
    category: "suprabhat",
    tradition: "universal",
    titleHi: "प्रसन्नता — सबसे बड़ी औषधि",
    titleEn: "Joy is the Greatest Medicine",
    shlokaOrSutra: "प्रसादे सर्वदुःखानां हानिरस्योपजायते।",
    shlokaHinglish: "Prasade Sarva-Duhkhanam Hanir Asyopajayate",
    quoteHi: "मन की प्रसन्नता और सकारात्मकता समस्त दुःखों और रोगों का नाश कर देती है। आज का दिन मुस्कान और शांति के साथ बिताएं।",
    quoteHinglish: "Man ko sada prasanna aur aashavadi rakhein. Prasannata se har karya safal hota hai.",
    quoteEn: "Cheerfulness and peace of mind eradicate all grief and anxiety. Begin your day with a calm smile and inner confidence.",
    sourceHi: "श्रीमद्भगवद्गीता",
    sourceEn: "Bhagavad Gita",
    symbol: "sun",
    tag: "प्रसन्न मन",
    tagEn: "Inner Joy",
  },
];

